// Package feeds provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package feeds

// Defines values for LinkType.
const (
	LinkTypeEmail   LinkType = "email"
	LinkTypeId      LinkType = "id"
	LinkTypeWebsite LinkType = "website"
)

// Valid indicates whether the value is a known member of the LinkType enum.
func (e LinkType) Valid() bool {
	switch e {
	case LinkTypeEmail:
		return true
	case LinkTypeId:
		return true
	case LinkTypeWebsite:
		return true
	default:
		return false
	}
}

// Defines values for SourceType.
const (
	SourceTypeAtom     SourceType = "Atom"
	SourceTypeHTML     SourceType = "HTML"
	SourceTypeJSONFeed SourceType = "JSONFeed"
	SourceTypeRDF      SourceType = "RDF"
	SourceTypeRSS      SourceType = "RSS"
	SourceTypeUnknown  SourceType = "Unknown"
)

// Valid indicates whether the value is a known member of the SourceType enum.
func (e SourceType) Valid() bool {
	switch e {
	case SourceTypeAtom:
		return true
	case SourceTypeHTML:
		return true
	case SourceTypeJSONFeed:
		return true
	case SourceTypeRDF:
		return true
	case SourceTypeRSS:
		return true
	case SourceTypeUnknown:
		return true
	default:
		return false
	}
}

// Image represents a remote image.
type Image struct {
	// URL the URL to the image.
	URL string `json:"URL" validate:"required,url"`

	// Description is a description of the image (for example, the alt tag associated with the image).
	Description *string `json:"description,omitempty"`
}

// Link is an 'address', usually of a person. For example, an email, website or social media handle. An address has a type and a value and/or URI associated with it.
type Link struct {
	// Type is the type of address. While there are some canonical values for the type, they are not conclusive and the type can be any value, including one of the canonical types. However, a canonical type should be used whenever appropriate.
	Type LinkType `json:"type" validate:"required"`

	// Value is the link value. It can be a URI, email or any string that acts as a unique identifier (i.e., social media handle).
	Value string `json:"value" validate:"required|uri|email"`
}

// LinkType is the type of address. While there are some canonical values for the type, they are not conclusive and the type can be any value, including one of the canonical types. However, a canonical type should be used whenever appropriate.
type LinkType string

// Person represents a person.
type Person struct {
	// Bio is an optional short biography of the person.
	Bio *string `json:"bio,omitempty"`

	// Links are links associated with the person that provide more details about them.
	Links []Link `json:"links,omitempty" validate:"omitempty,dive,unique"`

	// Name is the person's name.
	Name string `json:"name" validate:"required"`
}

// SourceType is the type of source the feed or object came from. This can be used with abstractions that generalize different feed types into a common format to preserve information on the original.
type SourceType string
