# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/refs/heads/main/schemas/v3.0/schema.yaml
# Copyright 2025 Joshua Rich <joshua.rich@gmail.com>.
openapi: "3.0.3"
info:
  version: 1.0.0
  title: RSS Extensions Schema
  description: >
    RSS extensions for Syndication and Content modules.

    https://web.resource.org/rss/1.0/modules/syndication/

    http://purl.org/rss/1.0/modules/content/
  license:
    name: AGPL-3.0-or-later
    url: https://spdx.org/licenses/AGPL-3.0-only.html
paths: {}
components:
  schemas:
    ContentEncoded:
      description: >
        is an element whose contents are the entity-encoded or CDATA-escaped version of the content of the item.
      type: object
      required:
        - XMLName
        - value
      properties:
        XMLName:
          $ref: "types.yaml#/components/schemas/XMLName"
        value:
          $ref: "types.yaml#/components/schemas/RequiredValue"
      x-oapi-codegen-extra-tags:
        json: "content_encoded,omitempty"
        xml: "http://purl.org/rss/1.0/modules/content/ encoded,omitempty"
    SYUpdatePeriod:
      description: >
         is the period over which the channel format is updated.
      type: object
      required:
        - XMLName
        - value
      properties:
        XMLName:
          $ref: "types.yaml#/components/schemas/XMLName"
        value:
          type: string
          default: "daily"
          enum: ["hourly","daily","weekly","monthly","yearly"]
          x-enum-varnames: ["UpdatedHourly","UpdatedDaily","UpdatedWeekly","UpdatedMonthly","UpdatedYearly"]
          x-oapi-codegen-extra-tags:
            xml: ",chardata"
            # validate: "required,oneof=hourly daily weekly monthly yearly"
      x-oapi-codegen-extra-tags:
        json: "sy_updatePeriod,omitempty"
        xml: "http://purl.org/rss/1.0/modules/syndication/ updatePeriod,omitempty"
    SYUpdateFrequency:
      description: >
        describes the frequency of updates in relation to the update period.
      type: object
      required:
        - XMLName
        - value
      properties:
        XMLName:
          $ref: "types.yaml#/components/schemas/XMLName"
        value:
          type: integer
          minimum: 1
          default: 1
          x-oapi-codegen-extra-tags:
            json: "value"
            xml: ",chardata"
            validate: "omitempty,number,gte=1"
      x-oapi-codegen-extra-tags:
        json: "sy_updateFrequency,omitempty"
        xml: "http://purl.org/rss/1.0/modules/syndication/ updateFrequency,omitempty"
    SYUpdateBase:
      description: >
        is a base date to be used in concert with updatePeriod and updateFrequency to calculate the publishing schedule.
      type: object
      required:
        - XMLName
        - value
      properties:
        XMLName:
          $ref: "types.yaml#/components/schemas/XMLName"
        value:
          x-go-type: types.DateTime
          x-oapi-codegen-extra-tags:
            json: "value"
            xml: ",chardata"
            validate: "omitempty"
      x-oapi-codegen-extra-tags:
        json: "sy_updateBase,omitempty"
        xml: "http://purl.org/rss/1.0/modules/syndication/ updateBase,omitempty"
    SyndicationElements:
      description: >
        contains all syndication extension elements.
      type: object
      properties:
        SYUdatePeriod:
          $ref: "#/components/schemas/SYUpdatePeriod"
        SYUpdateFrequency:
          $ref: "#/components/schemas/SYUpdateFrequency"
        SYUpdateBase:
          $ref: "#/components/schemas/SYUpdateBase"
