// Package basicgeo provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package basicgeo

// Altitude is the meters above the local reference ellipsoid.
type Altitude = float64

// LatLong a flat, comma-separated alternative encoding of the latitude and longitude.
type LatLong struct {
	// Lat is the latitude in decimal degress
	Lat Latitude `json:"lat" validate:"omitempty,gte=-90,lte=90" xml:"http://www.w3.org/2003/01/geo/wgs84_pos# lat"`

	// Lon is the longitude in decimal degress
	Lon Longitude `json:"lon" validate:"omitempty,gte=-180,lte=180" xml:"http://www.w3.org/2003/01/geo/wgs84_pos# long"`
}

// Latitude is the latitude in decimal degress
type Latitude = float64

// Location is the relation between something and the point... where it is.
type Location struct {
	// Point is an instance of the geo:point class.
	Point Point `json:"Point"`
}

// Longitude is the longitude in decimal degress
type Longitude = float64

// Point is an instance of the geo:point class.
type Point struct {
	// About an rdf:about identifying this Point as its own addressable resource, e.g. for reuse via rdf:resource elsewhere in an RDF document.
	About *string `json:"about,omitempty" xml:"http://www.w3.org/1999/02/22-rdf-syntax-ns# about,attr,omitempty"`

	// Alt is the meters above the local reference ellipsoid.
	Alt *Altitude `json:"alt,omitempty" xml:"http://www.w3.org/2003/01/geo/wgs84_pos# alt,omitempty"`

	// Lat is the latitude in decimal degress
	Lat Latitude `json:"lat" validate:"omitempty,gte=-90,lte=90" xml:"http://www.w3.org/2003/01/geo/wgs84_pos# lat"`

	// Lon is the longitude in decimal degress
	Lon Longitude `json:"lon" validate:"omitempty,gte=-180,lte=180" xml:"http://www.w3.org/2003/01/geo/wgs84_pos# long"`
}

// Position is a position, typically described using a coordinate system relative to Earth. Uniquely identified by lat/long/alt.
type Position struct {
	// Alt is the meters above the local reference ellipsoid.
	Alt *Altitude `json:"alt,omitempty" xml:"http://www.w3.org/2003/01/geo/wgs84_pos# alt,omitempty"`

	// Lat is the latitude in decimal degress
	Lat *Latitude `json:"lat,omitempty" validate:"omitempty,gte=-90,lte=90" xml:"http://www.w3.org/2003/01/geo/wgs84_pos# lat"`

	// Lon is the longitude in decimal degress
	Lon *Longitude `json:"lon,omitempty" validate:"omitempty,gte=-180,lte=180" xml:"http://www.w3.org/2003/01/geo/wgs84_pos# long"`
}
