// Package rdf provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package rdf

import (
	"encoding/xml"

	externalRef0 "github.com/immanent-tech/go-syndication/extensions"
	externalRef1 "github.com/immanent-tech/go-syndication/extensions/dc"
	externalRef2 "github.com/immanent-tech/go-syndication/extensions/rss"
)

// Channel contains metadata describing the channel itself, including a title, brief description, and URL link to the described resource (the channel provider's home page, for instance). The {resource} URL of the channel element's rdf:about attribute must be unique with respect to any other rdf:about attributes in the RSS document and is a URI which identifies the channel. Most commonly, this is either the URL of the homepage being described or a URL where the RSS file can be found.
type Channel struct {
	// SYUdatePeriod is the period over which the channel format is updated.
	SYUdatePeriod *externalRef2.SYUpdatePeriod `json:"update_period,omitempty" xml:"http://purl.org/rss/1.0/modules/syndication/ updatePeriod,omitempty"`

	// SYUpdateBase is a base date to be used in concert with updatePeriod and updateFrequency to calculate the publishing schedule.
	SYUpdateBase *externalRef2.SYUpdateBase `json:"update_base,omitempty" xml:"http://purl.org/rss/1.0/modules/syndication/ updateBase,omitempty"`

	// SYUpdateFrequency describes the frequency of updates in relation to the update period.
	SYUpdateFrequency *externalRef2.SYUpdateFrequency `json:"update_frequency,omitempty" xml:"http://purl.org/rss/1.0/modules/syndication/ updateFrequency,omitempty"`
	XMLName           xml.Name                        `json:"XMLName" xml:"http://purl.org/rss/1.0/ channel"`
	About             string                          `json:"about" validate:"required" xml:"http://www.w3.org/1999/02/22-rdf-syntax-ns# about,attr"`

	// Contributor is an entity responsible for making contributions to the resource.
	// The guidelines for using names of persons or organizations as creators apply to contributors.
	Contributor *externalRef1.Contributor `json:"contributor,omitempty" xml:"http://purl.org/dc/elements/1.1/ contributor,omitempty"`

	// Coverage is the spatial or temporal topic of the resource, spatial applicability of the resource, or jurisdiction under which the resource is relevant.
	// Spatial topic and spatial applicability may be a named place or a location specified by its geographic coordinates. Temporal topic may be a named period, date, or date range. A jurisdiction may be a named administrative entity or a geographic place to which the resource applies. Recommended practice is to use a controlled vocabulary such as the Getty Thesaurus of Geographic Names [TGN]. Where appropriate, named places or time periods may be used in preference to numeric identifiers such as sets of coordinates or date ranges. Because coverage is so broadly defined, it is preferable to use the more specific subproperties Temporal Coverage and Spatial Coverage.
	Coverage *externalRef1.Coverage `json:"coverage,omitempty" xml:"http://purl.org/dc/elements/1.1/ coverage,omitempty"`

	// Creator is an entity responsible for making the resource.
	// Recommended practice is to identify the creator with a URI. If this is not possible or feasible, a literal value that identifies the creator may be provided.
	Creator *externalRef1.Creator `json:"creator,omitempty" xml:"http://purl.org/dc/elements/1.1/ creator,omitempty"`

	// Date is a point or period of time associated with an event in the lifecycle of the resource.
	// Date may be used to express temporal information at any level of granularity. Recommended practice is to express the date, date/time, or period of time according to ISO 8601-1 [ISO 8601-1] or a published profile of the ISO standard, such as the W3C Note on Date and Time Formats [W3CDTF] or the Extended Date/Time Format Specification [EDTF]. If the full date is unknown, month and year (YYYY-MM) or just year (YYYY) may be used. Date ranges may be specified using ISO 8601 period of time specification in which start and end dates are separated by a '/' (slash) character. Either the start or end date may be missing.
	Date *externalRef1.Date `json:"date,omitempty" xml:"http://purl.org/dc/elements/1.1/ date,omitempty"`

	// Description is a brief description of the channel's content, function, source, etc.
	Description string `json:"description" validate:"required,max=500" xml:"http://purl.org/rss/1.0/ description"`

	// Format is the file format, physical medium, or dimensions of the resource.
	// Recommended practice is to use a controlled vocabulary where available. For example, for file formats one could use the list of Internet Media Types [MIME]. Examples of dimensions include size and duration.
	Format *externalRef1.Format `json:"format,omitempty" xml:"http://purl.org/dc/elements/1.1/ format,omitempty"`

	// Identifier is an unambiguous reference to the resource within a given context.
	// Recommended practice is to identify the resource by means of a string conforming to an identification system. Examples include International Standard Book Number (ISBN), Digital Object Identifier (DOI), and Uniform Resource Name (URN). Persistent identifiers should be provided as HTTP URIs.
	Identifier *externalRef1.Identifier `json:"identifier,omitempty" xml:"http://purl.org/dc/elements/1.1/ identifier,omitempty"`

	// Image establishes an RDF association between the optional image element [5.4] and this particular RSS channel. The rdf:resource's {image_uri} must be the same as the image element's rdf:about {image_uri}.
	Image *ResourceRef `json:"image,omitempty" xml:"http://purl.org/rss/1.0/ image"`

	// Items are an RDF table of contents, associating the document's items [5.5] with this particular RSS channel. Each item's rdf:resource {item_uri} must be the same as the associated item element's rdf:about {item_uri}.
	// An RDF Seq (sequence) is used to contain all the items rather than an RDF Bag to denote item order for rendering and reconstruction.
	// Note that items appearing in the document but not as members of the channel level items sequence are likely to be discarded by RDF parsers.
	Items ItemRefs `json:"items" validate:"required" xml:"http://purl.org/rss/1.0/ items"`

	// Language is a language of the resource.
	// Recommended practice is to use either a non-literal value representing a language from a controlled vocabulary such as ISO 639-2 or ISO 639-3, or a literal value consisting of an IETF Best Current Practice 47 [IETF-BCP47] language tag.
	Language *externalRef1.Language `json:"language,omitempty" xml:"http://purl.org/dc/elements/1.1/ language,omitempty"`

	// Link is the URL to which an HTML rendering of the channel title will link, commonly the parent site's home or news page.
	Link string `json:"link" validate:"required,max=500,url" xml:"http://purl.org/rss/1.0/ link"`

	// Publisher is an entity responsible for making the resource available.
	Publisher *externalRef1.Publisher `json:"publisher,omitempty" xml:"http://purl.org/dc/elements/1.1/ publisher,omitempty"`

	// Relation is a related resource.
	// Recommended practice is to identify the related resource by means of a URI. If this is not possible or feasible, a string conforming to a formal identification system may be provided.
	Relation *externalRef1.Relation `json:"relation,omitempty" xml:"http://purl.org/dc/elements/1.1/ relation,omitempty"`

	// Rights is information about rights held in and over the resource.
	// Typically, rights information includes a statement about various property rights associated with the resource, including intellectual property rights. Recommended practice is to refer to a rights statement with a URI. If this is not possible or feasible, a literal value (name, label, or short text) may be provided.
	Rights *externalRef1.Rights `json:"rights,omitempty" xml:"http://purl.org/dc/elements/1.1/ rights,omitempty"`

	// Source is a related resource from which the described resource is derived.
	// This property is intended to be used with non-literal values. The described resource may be derived from the related resource in whole or in part. Best practice is to identify the related resource by means of a URI or a string conforming to a formal identification system.
	Source *externalRef1.Source `json:"source,omitempty" xml:"http://purl.org/dc/elements/1.1/ source,omitempty"`

	// Subject is a topic of the resource.
	// Recommended practice is to refer to the subject with a URI. If this is not possible or feasible, a literal value that identifies the subject may be provided. Both should preferably refer to a subject in a controlled vocabulary.
	Subject *externalRef1.Subject `json:"subject,omitempty" xml:"http://purl.org/dc/elements/1.1/ subject,omitempty"`

	// TextInput Establishes an RDF association between the optional textinput element [5.6] and this particular RSS channel. The {textinput_uri} rdf:resource must be the same as the textinput element's rdf:about {textinput_uri}.
	TextInput *ResourceRef `json:"textInput,omitempty" xml:"http://purl.org/rss/1.0/ textinput"`

	// Title is a descriptive title for the channel.
	Title string `json:"title" validate:"required,max=48" xml:"http://purl.org/rss/1.0/ title"`

	// Type is the nature or genre of the resource.
	// Recommended practice is to use a controlled vocabulary such as the DCMI Type Vocabulary [DCMI-TYPE]. To describe the file format, physical medium, or dimensions of the resource, use the property Format.
	Type *externalRef1.Type `json:"type,omitempty" xml:"http://purl.org/dc/elements/1.1/ type,omitempty"`
}

// Image is an image to be associated with an HTML rendering of the channel. This image should be of a format supported by the majority of Web browsers. While the later 0.91 specification allowed for a width of 1-144 and height of 1-400, convention (and the 0.9 specification) dictate 88x31.
type Image struct {
	XMLName xml.Name `json:"XMLName" xml:"http://purl.org/rss/1.0/ image"`
	About   string   `json:"about" validate:"required" xml:"http://www.w3.org/1999/02/22-rdf-syntax-ns# about,attr"`

	// Link is the URL to which an HTML rendering of the channel image will link. This, as with the channel's title link, is commonly the parent site's home or news page.
	Link string `json:"link" validate:"required,max=500,url" xml:"http://purl.org/rss/1.0/ link"`

	// Title is the alternative text ("alt" attribute) associated with the channel's image tag when rendered as HTML.
	Title string `json:"title" validate:"required,max=40" xml:"http://purl.org/rss/1.0/ title"`

	// URL is the URL of the image to used in the "src" attribute of the channel's image tag when rendered as HTML.
	URL string `json:"url" validate:"required,max=500,url" xml:"http://purl.org/rss/1.0/ url"`
}

// Item while commonly a news headline, with RSS 1.0's modular extensibility, this can be just about anything: discussion posting, job listing, software patch -- any object with a URI. There may be a minimum of one item per RSS document. While RSS 1.0 does not enforce an upper limit, for backward compatibility with RSS 0.9 and 0.91, a maximum of fifteen items is recommended.
// {item_uri} must be unique with respect to any other rdf:about attributes in the RSS document and is a URI which identifies the item. {item_uri} should be identical to the value of the <link> sub-element of the <item> element, if possible.
type Item struct {
	XMLName xml.Name `json:"XMLName" xml:"http://purl.org/rss/1.0/ item"`
	About   string   `json:"about" validate:"required" xml:"http://www.w3.org/1999/02/22-rdf-syntax-ns# about,attr"`

	// Contributor is an entity responsible for making contributions to the resource.
	// The guidelines for using names of persons or organizations as creators apply to contributors.
	Contributor *externalRef1.Contributor `json:"contributor,omitempty" xml:"http://purl.org/dc/elements/1.1/ contributor,omitempty"`

	// Coverage is the spatial or temporal topic of the resource, spatial applicability of the resource, or jurisdiction under which the resource is relevant.
	// Spatial topic and spatial applicability may be a named place or a location specified by its geographic coordinates. Temporal topic may be a named period, date, or date range. A jurisdiction may be a named administrative entity or a geographic place to which the resource applies. Recommended practice is to use a controlled vocabulary such as the Getty Thesaurus of Geographic Names [TGN]. Where appropriate, named places or time periods may be used in preference to numeric identifiers such as sets of coordinates or date ranges. Because coverage is so broadly defined, it is preferable to use the more specific subproperties Temporal Coverage and Spatial Coverage.
	Coverage *externalRef1.Coverage `json:"coverage,omitempty" xml:"http://purl.org/dc/elements/1.1/ coverage,omitempty"`

	// Creator is an entity responsible for making the resource.
	// Recommended practice is to identify the creator with a URI. If this is not possible or feasible, a literal value that identifies the creator may be provided.
	Creator *externalRef1.Creator `json:"creator,omitempty" xml:"http://purl.org/dc/elements/1.1/ creator,omitempty"`

	// Date is a point or period of time associated with an event in the lifecycle of the resource.
	// Date may be used to express temporal information at any level of granularity. Recommended practice is to express the date, date/time, or period of time according to ISO 8601-1 [ISO 8601-1] or a published profile of the ISO standard, such as the W3C Note on Date and Time Formats [W3CDTF] or the Extended Date/Time Format Specification [EDTF]. If the full date is unknown, month and year (YYYY-MM) or just year (YYYY) may be used. Date ranges may be specified using ISO 8601 period of time specification in which start and end dates are separated by a '/' (slash) character. Either the start or end date may be missing.
	Date *externalRef1.Date `json:"date,omitempty" xml:"http://purl.org/dc/elements/1.1/ date,omitempty"`

	// Description is a brief description/abstract of the item.
	Description *string `json:"description,omitempty" validate:"omitempty,max=500" xml:"http://purl.org/rss/1.0/ description"`

	// Format is the file format, physical medium, or dimensions of the resource.
	// Recommended practice is to use a controlled vocabulary where available. For example, for file formats one could use the list of Internet Media Types [MIME]. Examples of dimensions include size and duration.
	Format *externalRef1.Format `json:"format,omitempty" xml:"http://purl.org/dc/elements/1.1/ format,omitempty"`

	// Identifier is an unambiguous reference to the resource within a given context.
	// Recommended practice is to identify the resource by means of a string conforming to an identification system. Examples include International Standard Book Number (ISBN), Digital Object Identifier (DOI), and Uniform Resource Name (URN). Persistent identifiers should be provided as HTTP URIs.
	Identifier *externalRef1.Identifier `json:"identifier,omitempty" xml:"http://purl.org/dc/elements/1.1/ identifier,omitempty"`

	// Language is a language of the resource.
	// Recommended practice is to use either a non-literal value representing a language from a controlled vocabulary such as ISO 639-2 or ISO 639-3, or a literal value consisting of an IETF Best Current Practice 47 [IETF-BCP47] language tag.
	Language *externalRef1.Language `json:"language,omitempty" xml:"http://purl.org/dc/elements/1.1/ language,omitempty"`

	// Link is the item's URL.
	Link string `json:"link" validate:"required,max=500,url" xml:"http://purl.org/rss/1.0/ link"`

	// Publisher is an entity responsible for making the resource available.
	Publisher *externalRef1.Publisher `json:"publisher,omitempty" xml:"http://purl.org/dc/elements/1.1/ publisher,omitempty"`

	// Relation is a related resource.
	// Recommended practice is to identify the related resource by means of a URI. If this is not possible or feasible, a string conforming to a formal identification system may be provided.
	Relation *externalRef1.Relation `json:"relation,omitempty" xml:"http://purl.org/dc/elements/1.1/ relation,omitempty"`

	// Rights is information about rights held in and over the resource.
	// Typically, rights information includes a statement about various property rights associated with the resource, including intellectual property rights. Recommended practice is to refer to a rights statement with a URI. If this is not possible or feasible, a literal value (name, label, or short text) may be provided.
	Rights *externalRef1.Rights `json:"rights,omitempty" xml:"http://purl.org/dc/elements/1.1/ rights,omitempty"`

	// Source is a related resource from which the described resource is derived.
	// This property is intended to be used with non-literal values. The described resource may be derived from the related resource in whole or in part. Best practice is to identify the related resource by means of a URI or a string conforming to a formal identification system.
	Source *externalRef1.Source `json:"source,omitempty" xml:"http://purl.org/dc/elements/1.1/ source,omitempty"`

	// Subject is a topic of the resource.
	// Recommended practice is to refer to the subject with a URI. If this is not possible or feasible, a literal value that identifies the subject may be provided. Both should preferably refer to a subject in a controlled vocabulary.
	Subject *externalRef1.Subject `json:"subject,omitempty" xml:"http://purl.org/dc/elements/1.1/ subject,omitempty"`

	// Title is the item's title.
	Title string `json:"title" validate:"required,max=100" xml:"http://purl.org/rss/1.0/ title"`

	// Type is the nature or genre of the resource.
	// Recommended practice is to use a controlled vocabulary such as the DCMI Type Vocabulary [DCMI-TYPE]. To describe the file format, physical medium, or dimensions of the resource, use the property Format.
	Type *externalRef1.Type `json:"type,omitempty" xml:"http://purl.org/dc/elements/1.1/ type,omitempty"`
}

// ItemRefs are channel's <items><rdf:Seq><rdf:li resource="..."/>...</rdf:Seq></items> table of contents, presented to callers as a simple ordered []string of item URIs rather than the three-level RDF nesting on the wire.
type ItemRefs []string

// RDF represents an RDF document
type RDF struct {
	DefaultNamespace string `json:"DefaultNamespace"`

	// Channel contains metadata describing the channel itself, including a title, brief description, and URL link to the described resource (the channel provider's home page, for instance). The {resource} URL of the channel element's rdf:about attribute must be unique with respect to any other rdf:about attributes in the RSS document and is a URI which identifies the channel. Most commonly, this is either the URL of the homepage being described or a URL where the RSS file can be found.
	Channel Channel `json:"channel" xml:"http://purl.org/rss/1.0/ channel"`

	// Image is an image to be associated with an HTML rendering of the channel. This image should be of a format supported by the majority of Web browsers. While the later 0.91 specification allowed for a width of 1-144 and height of 1-400, convention (and the 0.9 specification) dictate 88x31.
	Image *Image `json:"image,omitempty" xml:"http://purl.org/rss/1.0/ image"`

	// Items is an RDF table of contents, associating the document's items [5.5] with this particular RSS channel. Each item's rdf:resource {item_uri} must be the same as the associated item element's rdf:about {item_uri}.
	// An RDF Seq (sequence) is used to contain all the items rather than an RDF Bag to denote item order for rendering and reconstruction.
	// Note that items appearing in the document but not as members of the channel level items sequence are likely to be discarded by RDF parsers.
	Items []Item `json:"items,omitempty" xml:"http://purl.org/rss/1.0/ item"`

	// Namespaces contains all namespaces in use by this RSS feed.
	Namespaces []externalRef0.Namespace `json:"namespaces,omitempty"`

	// TextInput affords a method for submitting form data to an arbitrary URL -- usually located at the parent website. The form processor at the receiving end only is assumed to handle the HTTP GET method.
	// The field is typically used as a search box or subscription form -- among others. While this is of some use when RSS documents are rendered as channels (see MNN) and accompanied by human readable title and description, the ambiguity in automatic determination of meaning of this overloaded element renders it otherwise not particularly useful. RSS 1.0 therefore suggests either deprecation or augmentation with some form of resource discovery of this element in future versions while maintaining it for backward compatiblity with RSS 0.9.
	// {textinput_uri} must be unique with respect to any other rdf:about attributes in the RSS document and is a URI which identifies the textinput. {textinput_uri} should be identical to the value of the <link> sub-element of the <textinput> element, if possible.
	TextInput *TextInput `json:"textInput,omitempty" xml:"http://purl.org/rss/1.0/ textinput"`
}

// RDFResource embeds the rdf:about attribute required on every top-level channel/image/item/textinput element ("Each second-level element... must include an rdf:about attribute").
type RDFResource struct {
	About string `json:"about" validate:"required" xml:"http://www.w3.org/1999/02/22-rdf-syntax-ns# about,attr"`
}

// ResourceRef is channel's <image rdf:resource="..."/> / <textinput rdf:resource="..."/>. It's an empty element whose only content is a pointer to another top-level element's rdf:about URI.
type ResourceRef struct {
	Resource string `json:"resource" xml:"http://www.w3.org/1999/02/22-rdf-syntax-ns# resource,attr"`
}

// TextInput affords a method for submitting form data to an arbitrary URL -- usually located at the parent website. The form processor at the receiving end only is assumed to handle the HTTP GET method.
// The field is typically used as a search box or subscription form -- among others. While this is of some use when RSS documents are rendered as channels (see MNN) and accompanied by human readable title and description, the ambiguity in automatic determination of meaning of this overloaded element renders it otherwise not particularly useful. RSS 1.0 therefore suggests either deprecation or augmentation with some form of resource discovery of this element in future versions while maintaining it for backward compatiblity with RSS 0.9.
// {textinput_uri} must be unique with respect to any other rdf:about attributes in the RSS document and is a URI which identifies the textinput. {textinput_uri} should be identical to the value of the <link> sub-element of the <textinput> element, if possible.
type TextInput struct {
	XMLName xml.Name `json:"XMLName" xml:"http://purl.org/rss/1.0/ textinput"`
	About   string   `json:"about" validate:"required" xml:"http://www.w3.org/1999/02/22-rdf-syntax-ns# about,attr"`

	// Description is a brief description of the textinput field's purpose. For example: "Subscribe to our newsletter for..." or "Search our site's archive of..."
	Description string `json:"description" validate:"omitempty,max=100" xml:"http://purl.org/rss/1.0/ description"`

	// Link is the URL to which a textinput submission will be directed (using GET).
	Link string `json:"link" validate:"required,max=500,url" xml:"http://purl.org/rss/1.0/ link"`

	// Name is the text input field's (variable) name.
	Name string `json:"name" validate:"required,max=500" xml:"http://purl.org/rss/1.0/ name"`

	// Title is a descriptive title for the textinput field. For example: "Subscribe" or "Search!"
	Title string `json:"title" validate:"required,max=40" xml:"http://purl.org/rss/1.0/ title"`
}
