// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package types

// Language is the primary language encapsulated in the element. Language codes possible are detailed in RFC 3066.
type Language = string

// URL is a URL link.
type URL = string
