// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package types

import (
	externalRef0 "github.com/immanent-tech/go-syndication/extensions/georss"
)

// Defines values for LinkType.
const (
	LinkTypeEmail   LinkType = "email"
	LinkTypeId      LinkType = "id"
	LinkTypeWebsite LinkType = "website"
)

// Valid indicates whether the value is a known member of the LinkType enum.
func (e LinkType) Valid() bool {
	switch e {
	case LinkTypeEmail:
		return true
	case LinkTypeId:
		return true
	case LinkTypeWebsite:
		return true
	default:
		return false
	}
}

// Defines values for Source.
const (
	SourceAtom     Source = "Atom"
	SourceHTML     Source = "HTML"
	SourceJSONFeed Source = "JSONFeed"
	SourceRDF      Source = "RDF"
	SourceRSS      Source = "RSS"
	SourceUnknown  Source = "Unknown"
)

// Valid indicates whether the value is a known member of the Source enum.
func (e Source) Valid() bool {
	switch e {
	case SourceAtom:
		return true
	case SourceHTML:
		return true
	case SourceJSONFeed:
		return true
	case SourceRDF:
		return true
	case SourceRSS:
		return true
	case SourceUnknown:
		return true
	default:
		return false
	}
}

// GeoInfo contains geographical information.
type GeoInfo = externalRef0.GeoRSSSimple

// Image represents a remote image.
type Image struct {
	// Title is a description of the image (for example, the alt tag associated with the image).
	Title *string `json:"title,omitempty"`

	// URL the URL to the image.
	URL string `json:"url" validate:"required,url"`
}

// Link is an 'address', usually of a person. For example, an email, website or social media handle. An address has a type and a value and/or URI associated with it.
type Link struct {
	// Type is the type of address. While there are some canonical values for the type, they are not conclusive and the type can be any value, including one of the canonical types. However, a canonical type should be used whenever appropriate.
	Type LinkType `json:"type" validate:"required"`

	// Value is the link value. It can be a URI, email or any string that acts as a unique identifier (i.e., social media handle).
	Value string `json:"value" validate:"required|uri|email"`
}

// LinkType is the type of address. While there are some canonical values for the type, they are not conclusive and the type can be any value, including one of the canonical types. However, a canonical type should be used whenever appropriate.
type LinkType string

// Person represents a person.
type Person struct {
	// Bio is an optional short biography of the person.
	Bio *string `json:"bio,omitempty"`

	// Links are links associated with the person that provide more details about them.
	Links []Link `json:"links,omitempty" validate:"omitempty,dive,unique"`

	// Name is the person's name.
	Name string `json:"name" validate:"required"`
}

// Source is the type of source the feed or object came from. This can be used with abstractions that generalize different feed types into a common format to preserve information on the original.
type Source string
