// Package opml provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package opml

import (
	"encoding/xml"
	"time"

	externalRef0 "github.com/immanent-tech/go-syndication/extensions"
)

// Defines values for RSSOutlineVersion.
const (
	RSS           RSSOutlineVersion = "RSS"
	RSS1          RSSOutlineVersion = "RSS1"
	RSS2          RSSOutlineVersion = "RSS2"
	ScriptingNews RSSOutlineVersion = "scriptingNews"
)

// Valid indicates whether the value is a known member of the RSSOutlineVersion enum.
func (e RSSOutlineVersion) Valid() bool {
	switch e {
	case RSS:
		return true
	case RSS1:
		return true
	case RSS2:
		return true
	case ScriptingNews:
		return true
	default:
		return false
	}
}

// Body represents the OPML <body> element.
type Body []Outline

// Categories is a string of comma-separated, slash-delimited category strings.
// e.g. []string{"/Boston/Weather"} or {"/Harvard/Berkman", "/Politics"}.
type Categories []string

// ExpansionState is a comma-separated list of line numbers.
type ExpansionState []int

// Head represents the OPML <head> element.
type Head struct {
	// DateCreated is a date-time, indicating when the document was created.
	DateCreated *RFC822Time `json:"dateCreated,omitempty" xml:"dateCreated,omitempty"`

	// DateModified is a date-time, indicating when the document was last modified.
	DateModified *RFC822Time `json:"dateModified,omitempty" xml:"dateModified,omitempty"`

	// Docs is the http address of documentation for the format used in the OPML file. It's probably a pointer to this page for people who might stumble across the file on a web server 25 years from now and wonder what it is.
	Docs *string `json:"docs,omitempty" validate:"omitempty,url" xml:"docs,omitempty"`

	// ExpansionState is a comma-separated list of line numbers that are expanded. The line numbers in the list tell you which headlines to expand. The order is important. For each element in the list, X, starting at the first summit, navigate flatdown X times and expand. Repeat for each element in the list.
	ExpansionState ExpansionState `json:"expansionState,omitempty" xml:"expansionState,omitempty"`

	// OwnerEmail is the email address of the owner of the document.
	OwnerEmail *string `json:"ownerEmail,omitempty" validate:"omitempty,email" xml:"ownerEmail,omitempty"`

	// OwnerID is the http address of a web page that contains information that allows a human reader to communicate with the author of the document via email or other means. It also may be used to identify the author. No two authors have the same ownerId.
	OwnerID *string `json:"ownerId,omitempty" validate:"omitempty,url" xml:"ownerId,omitempty"`

	// OwnerName is the owner of the document.
	OwnerName *string `json:"ownerName,omitempty" xml:"ownerName,omitempty"`

	// Title is the title of the document.
	Title *string `json:"title,omitempty" xml:"title,omitempty"`

	// VertScrollState is a number, saying which line of the outline is displayed on the top line of the window. This number is calculated with the expansion state already applied.
	VertScrollState *int `json:"vertScrollState,omitempty" xml:"vertScrollState,omitempty"`

	// WindowBottom is a number, the pixel location of the bottom edge of the window.
	WindowBottom *int `json:"windowBottom,omitempty" xml:"windowBottom,omitempty"`

	// WindowLeft is a number, the pixel location of the left edge of the window.
	WindowLeft *int `json:"windowLeft,omitempty" xml:"windowLeft,omitempty"`

	// WindowRight is a number, the pixel location of the right edge of the window.
	WindowRight *int `json:"windowRight,omitempty" xml:"windowRight,omitempty"`

	// WindowTop is a number, the pixel location of the top edge of the window.
	WindowTop *int `json:"windowTop,omitempty" xml:"windowTop,omitempty"`
}

// OPML represents an OPML document.
type OPML struct {
	// Body represents the OPML <body> element.
	Body Body `json:"body" validate:"required,gte=1" xml:"body>outline"`

	// Head represents the OPML <head> element.
	Head       *Head                    `json:"head,omitempty" validate:"required" xml:"head"`
	Namespaces []externalRef0.Namespace `json:"namespaces,omitempty" xml:"-"`
	Version    string                   `json:"version" xml:"-"`
}

// Outline is an XML element containing at least one required attribute, text, and zero or more additional attributes. An <outline> may contain zero or more <outline> sub-elements. No attribute may be repeated within the same <outline> element.
type Outline struct {
	// Text is a textual description of the element.
	Text string `json:"text" validate:"required" xml:"text,attr"`

	// Type defines how the other attributes of the element are interpreted.
	Type *string `json:"type,omitempty" xml:"type,omitempty,attr"`

	// IsComment indicates whether the outline is commented or not. By convention if an outline is commented, all subordinate outlines are considered to also be commented. If it's not present, the value is false.
	IsComment *bool `json:"isComment,omitempty" xml:"isComment,omitempty,attr"`

	// IsBreakpoint indicates whether a breakpoint is set on this outline. This attribute is mainly necessary for outlines used to edit scripts. If it's not present, the value is false.
	IsBreakpoint *bool `json:"isBreakpoint,omitempty" xml:"isBreakpoint,omitempty,attr"`

	// Created is the date-time that the outline node was created.
	Created *RFC822AttrTime `json:"created,omitempty" xml:"created,omitempty,attr"`

	// Category is a string of comma-separated slash-delimited category strings, in the format defined by the RSS 2.0 category element. To represent a "tag," the category string should contain no slashes.
	Category Categories `json:"category,omitempty" xml:"category,omitempty,attr"`

	// Attrs is a catch-all for xmlUrl/htmlUrl/description/language/title/version.
	Attrs []xml.Attr `json:"attrs,omitempty" validate:"omitempty,unique" xml:",any,attr"`

	// Outlines contains any nested outlines of this outline.
	Outlines []Outline `json:"outlines,omitempty" validate:"omitempty,dive,validateFn" xml:"outline,omitempty"`

	// Extensions is a catch-all for any additional extensions.
	Extensions []externalRef0.Extension `json:"extensions,omitempty" xml:",any"`
}

// RFC822AttrTime is the ATTRIBUTE-context version (outline's "created" attribute).
type RFC822AttrTime struct {
	Time time.Time `json:"time"`
}

// RFC822Time is the ELEMENT-context version (dateCreated, dateModified).
type RFC822Time struct {
	Time time.Time `json:"time"`
}

// RSSOutline is a possibly multiple-level list of subscriptions to feeds. Each sub-element of the body of the OPML document is a node of type rss or an outline element that contains nodes of type rss.
type RSSOutline struct {
	// Description is the top-level description element from the feed.
	Description *string `json:"description,omitempty" xml:"description,omitempty,attr"`

	// HTMLURL is the top-level link element.
	HTMLURL *string `json:"htmlUrl,omitempty" validate:"omitempty,url" xml:"htmlUrl,omitempty,attr"`

	// Language is the value of the top-level language element.
	Language *string `json:"language,omitempty" xml:"language,omitempty,attr"`

	// Title contains the top-level title element from the feed.
	Title *string `json:"title,omitempty" xml:"title,omitempty,attr"`

	// Version is the top-level description element from the feed.
	Version *RSSOutlineVersion `json:"version,omitempty" validate:"omitempty,oneof=RSS2 RSS1 RSS scriptingNews" xml:"version,omitempty,attr"`

	// XMLURL is the http address of the feed.
	XMLURL string `json:"xmlUrl" validate:"required,url" xml:"xmlUrl,attr"`
}

// RSSOutlineVersion is the top-level description element from the feed.
type RSSOutlineVersion string
