// Package extensions provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package extensions

import (
	"encoding/xml"
)

// Extension represents an element that is not defined in the schema.
type Extension struct {
	XMLName xml.Name `json:"xml" validate:"required"`

	// Attributes are any attributes of the element.
	Attributes []xml.Attr `json:"attributes,omitempty" xml:",any,attr"`

	// Content is the element value.
	Content string `json:"content" validate:"required" xml:",innerxml"`
}

// Namespace is a single xmlns:prefix="uri" declaration.
type Namespace struct {
	// Prefix the unique prefix of the namespace.
	Prefix string `json:"prefix"`

	// URI the URI that points to the namespace.
	URI string `json:"uri"`
}
