// Package extensions provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package extensions

// Namespace is a single xmlns:prefix="uri" declaration.
type Namespace struct {
	// Prefix the unique prefix of the namespace.
	Prefix string `json:"prefix"`

	// URI the URI that points to the namespace.
	URI string `json:"uri"`
}
