// Package rss provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package rss

import (
	"github.com/joshuar/go-feed-me/models/feeds/types"
	externalRef1 "github.com/joshuar/go-feed-me/models/feeds/types"
)

// Defines values for SYUpdatePeriodValue.
const (
	UpdatedDaily   SYUpdatePeriodValue = "daily"
	UpdatedHourly  SYUpdatePeriodValue = "hourly"
	UpdatedMonthly SYUpdatePeriodValue = "monthly"
	UpdatedWeekly  SYUpdatePeriodValue = "weekly"
	UpdatedYearly  SYUpdatePeriodValue = "yearly"
)

// ContentEncoded is an element whose contents are the entity-encoded or CDATA-escaped version of the content of the item.
type ContentEncoded struct {
	// XMLName represents the XML namespace of an element.
	XMLName externalRef1.XMLName `json:"xml" validate:"required"`

	// Value is an element value that is required.
	Value externalRef1.RequiredValue `json:"value" validate:"required" xml:",chardata"`
}

// SYUpdateBase is a base date to be used in concert with updatePeriod and updateFrequency to calculate the publishing schedule.
type SYUpdateBase struct {
	// XMLName represents the XML namespace of an element.
	XMLName externalRef1.XMLName `json:"xml" validate:"required"`
	Value   types.DateTime       `json:"value" validate:"omitempty" xml:",chardata"`
}

// SYUpdateFrequency describes the frequency of updates in relation to the update period.
type SYUpdateFrequency struct {
	// XMLName represents the XML namespace of an element.
	XMLName externalRef1.XMLName `json:"xml" validate:"required"`
	Value   int                  `json:"value" validate:"omitempty,number,gte=1" xml:",chardata"`
}

// SYUpdatePeriod is the period over which the channel format is updated.
type SYUpdatePeriod struct {
	// XMLName represents the XML namespace of an element.
	XMLName externalRef1.XMLName `json:"xml" validate:"required"`
	Value   SYUpdatePeriodValue  `json:"value" xml:",chardata"`
}

// SYUpdatePeriodValue defines model for SYUpdatePeriod.Value.
type SYUpdatePeriodValue string

// SyndicationElements contains all syndication extension elements.
type SyndicationElements struct {
	// SYUdatePeriod is the period over which the channel format is updated.
	SYUdatePeriod *SYUpdatePeriod `json:"sy_updatePeriod,omitempty" xml:"http://purl.org/rss/1.0/modules/syndication/ updatePeriod,omitempty"`

	// SYUpdateBase is a base date to be used in concert with updatePeriod and updateFrequency to calculate the publishing schedule.
	SYUpdateBase *SYUpdateBase `json:"sy_updateBase,omitempty" xml:"http://purl.org/rss/1.0/modules/syndication/ updateBase,omitempty"`

	// SYUpdateFrequency describes the frequency of updates in relation to the update period.
	SYUpdateFrequency *SYUpdateFrequency `json:"sy_updateFrequency,omitempty" xml:"http://purl.org/rss/1.0/modules/syndication/ updateFrequency,omitempty"`
}
