// Package rss provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package rss

import (
	"encoding/xml"
	"time"

	externalRef0 "github.com/immanent-tech/go-syndication/atom"
	externalRef1 "github.com/immanent-tech/go-syndication/extensions"
	externalRef2 "github.com/immanent-tech/go-syndication/extensions/basicgeo"
	externalRef3 "github.com/immanent-tech/go-syndication/extensions/dc"
	externalRef4 "github.com/immanent-tech/go-syndication/extensions/georss"
	externalRef5 "github.com/immanent-tech/go-syndication/extensions/googleplay"
	externalRef6 "github.com/immanent-tech/go-syndication/extensions/itunes"
	externalRef7 "github.com/immanent-tech/go-syndication/extensions/media"
	externalRef8 "github.com/immanent-tech/go-syndication/extensions/rss"
	externalRef9 "github.com/immanent-tech/go-syndication/extensions/source"
)

// Defines values for CloudProtocol.
const (
	HttpPost CloudProtocol = "http-post"
	Soap     CloudProtocol = "soap"
	XmlRpc   CloudProtocol = "xml-rpc"
)

// Valid indicates whether the value is a known member of the CloudProtocol enum.
func (e CloudProtocol) Valid() bool {
	switch e {
	case HttpPost:
		return true
	case Soap:
		return true
	case XmlRpc:
		return true
	default:
		return false
	}
}

// Defines values for RSSVersion.
const (
	N091 RSSVersion = "0.91"
	N092 RSSVersion = "0.92"
	N20  RSSVersion = "2.0"
	N201 RSSVersion = "2.0.1"
)

// Valid indicates whether the value is a known member of the RSSVersion enum.
func (e RSSVersion) Valid() bool {
	switch e {
	case N091:
		return true
	case N092:
		return true
	case N20:
		return true
	case N201:
		return true
	default:
		return false
	}
}

// Defines values for SkipDaysDay.
const (
	SkipFriday    SkipDaysDay = "Friday"
	SkipMonday    SkipDaysDay = "Monday"
	SkipSaturday  SkipDaysDay = "Saturday"
	SkipSunday    SkipDaysDay = "Sunday"
	SkipThursday  SkipDaysDay = "Thursday"
	SkipTuesday   SkipDaysDay = "Tuesday"
	SkipWednesday SkipDaysDay = "Wednesday"
)

// Valid indicates whether the value is a known member of the SkipDaysDay enum.
func (e SkipDaysDay) Valid() bool {
	switch e {
	case SkipFriday:
		return true
	case SkipMonday:
		return true
	case SkipSaturday:
		return true
	case SkipSunday:
		return true
	case SkipThursday:
		return true
	case SkipTuesday:
		return true
	case SkipWednesday:
		return true
	default:
		return false
	}
}

// AtomLink defines a relationship between a web resource (such as a page) and an RSS channel or item.
type AtomLink = externalRef0.Link

// Author is the email address of the author of the item. For newspapers and magazines syndicating via RSS, the author is the person who wrote the article that the <item> describes. For collaborative weblogs, the author of the item might be different from the managing editor or webmaster. For a weblog authored by a single individual it would make sense to omit the <author> element.
type Author = string

// Category allows a taxonomy to be set on the channel or item.
type Category struct {
	// Domain is a string that identifies a categorization taxonomy.
	Domain *string `json:"domain,omitempty" xml:"domain,attr,omitempty"`
	Value  string  `json:"value" xml:",chardata"`
}

// Channel is the element containing metadata (Channel elements) and items.
type Channel struct {
	// GooglePlayCategory a taxonomy for the object.
	GooglePlayCategory *externalRef5.Category `json:"googleplay_category" xml:"http://www.google.com/schemas/play-podcasts/1.0 category,omitempty"`

	// ItunesAuthor is the author of the show content.
	ItunesAuthor *externalRef6.Author `json:"itunes_author" xml:"http://www.itunes.com/dtds/podcast-1.0.dtd author,omitempty"`

	// ItunesCategory is the set of all taxonomies that represent the show.
	ItunesCategory *externalRef6.Categories `json:"itunes_category" xml:"http://www.itunes.com/dtds/podcast-1.0.dtd category,omitempty"`

	// ItunesExplicit indicates whether the content is explicit in nature.
	ItunesExplicit *externalRef6.Explicit `json:"itunes_explicit" xml:"http://www.itunes.com/dtds/podcast-1.0.dtd explicit,omitempty"`

	// ItunesImage is the artwork for the show.
	ItunesImage *externalRef6.Image `json:"itunes_image" xml:"http://www.itunes.com/dtds/podcast-1.0.dtd image,omitempty"`
	ItunesOwner *externalRef6.Owner `json:"itunes_owner" xml:"http://www.itunes.com/dtds/podcast-1.0.dtd owner,omitempty"`

	// ItunesSubtitle is a subtitle for the show content.
	ItunesSubtitle *externalRef6.Subtitle `json:"itunes_subtitle" xml:"http://www.itunes.com/dtds/podcast-1.0.dtd subtitle,omitempty"`

	// ItunesSummary is a summary of the show content.
	ItunesSummary *externalRef6.Summary `json:"itunes_summary" xml:"http://www.itunes.com/dtds/podcast-1.0.dtd summary,omitempty"`

	// ItunesType is the type of show
	ItunesType *externalRef6.Type `json:"itunes_type" xml:"http://www.itunes.com/dtds/podcast-1.0.dtd type,omitempty"`

	// MediaBackLinks allows inclusion of all the URLs pointing to a media object.
	MediaBackLinks externalRef7.MediaBacklinks `json:"media_backlinks,omitempty" xml:"http://search.yahoo.com/mrss/ backLink,omitempty"`

	// MediaCategory allows a taxonomy to be set that gives an indication of the type of media content, and its particular contents.
	MediaCategory *externalRef7.MediaCategory `json:"media_category" xml:"http://search.yahoo.com/mrss/ category,omitempty"`

	// MediaComments is a list of comments the media object has received.
	MediaComments externalRef7.MediaComments `json:"media_comments"`

	// MediaCommunity stands for the community related content. This allows inclusion of the user perception about a media object in the form of view count, ratings and tags.
	MediaCommunity *externalRef7.MediaCommunity `json:"media_community" xml:"http://search.yahoo.com/mrss/ community,omitempty"`

	// MediaContent can be used to publish any type of media.
	MediaContent *externalRef7.MediaContent `json:"media_content,omitempty" validate:"omitempty,validateFn" xml:"http://search.yahoo.com/mrss/ content,omitempty"`

	// MediaCopyright is copyright information for the media object.
	MediaCopyright *externalRef7.MediaCopyright `json:"media_copyright" xml:"media copyright,omitempty"`

	// MediaCredits a list of credits for the object.
	MediaCredits externalRef7.MediaCredits `json:"media_credits" xml:"credit,omitempty"`

	// MediaDescription is a short description describing the media object typically a sentence in length.
	MediaDescription *externalRef7.MediaDescription `json:"media_description" xml:"http://search.yahoo.com/mrss/ description,omitempty"`

	// MediaEmbed allows inclusion of player-specific information in the form of key-value (Param) pairs.
	MediaEmbed *externalRef7.MediaEmbed `json:"media_embed" xml:"http://search.yahoo.com/mrss/ embed,omitempty"`

	// MediaGroup allows grouping of <media:content> elements that are effectively the same content, yet different representations. For instance: the same song recorded in both the WAV and MP3 format.
	MediaGroup *externalRef7.MediaGroup `json:"media_group,omitempty" xml:"http://search.yahoo.com/mrss/ group,omitempty"`

	// MediaHashes a list of hashes for the object.
	MediaHashes externalRef7.MediaHashes `json:"media_hashes" xml:"hash,omitempty"`

	// MediaKeywords are highly relevant keywords describing the media object with typically a maximum of 10 words. The keywords and phrases should be comma-delimited.
	MediaKeywords *externalRef7.MediaKeywords `json:"media_keywords" xml:"http://search.yahoo.com/mrss/ keywords,omitempty"`

	// MediaLicense link to specify the machine-readable license associated with the content.
	MediaLicense *externalRef7.MediaLicense `json:"media_license" xml:"http://search.yahoo.com/mrss/ license,omitempty"`

	// MediaPeerLink contains P2P link.
	MediaPeerLink *externalRef7.MediaPeerLink `json:"media_peerlink" xml:"http://search.yahoo.com/mrss/ peerLink,omitempty"`

	// MediaPlayer allows the media object to be accessed through a web browser media player console.
	MediaPlayer *externalRef7.MediaPlayer `json:"media_player" xml:"http://search.yahoo.com/mrss/ player,omitempty"`

	// MediaPrice includes pricing information about a media object. If this tag is not present, the media object is supposed to be free.
	MediaPrice *externalRef7.MediaPrice `json:"media_price" xml:"http://search.yahoo.com/mrss/ price,omitempty"`

	// MediaRating allows the permissible audience to be declared. If this element is not included, it assumes that no restrictions are necessary.
	MediaRating *externalRef7.MediaRating `json:"media_rating" xml:"http://search.yahoo.com/mrss/ rating,omitempty"`

	// MediaResponses allows inclusion of a list of all media responses a media object has received.
	MediaResponses externalRef7.MediaResponses `json:"media_responses" xml:"http://search.yahoo.com/mrss/ response,omitempty"`

	// MediaRestriction allows restrictions to be placed on the aggregator rendering the media in the feed.
	MediaRestriction *externalRef7.MediaRestriction `json:"media_restriction" validate:"omitempty,validateFn" xml:"http://search.yahoo.com/mrss/ restriction,omitempty"`

	// MediaRights specifies the rights information of a media object.
	MediaRights *externalRef7.MediaRights `json:"media_rights" xml:"http://search.yahoo.com/mrss/ rights,omitempty"`

	// MediaScenes specifies various scenes within a media object.
	MediaScenes externalRef7.MediaScenes `json:"media_scenes" xml:"http://search.yahoo.com/mrss/ scene,omitempty"`

	// MediaStatus specifies the status of a media object -- whether it's still active or it has been blocked/deleted.
	MediaStatus *externalRef7.MediaStatus `json:"media_status" xml:"http://search.yahoo.com/mrss/ status,omitempty"`

	// MediaSubTitle contains subtitle/CC link.
	MediaSubTitle *externalRef7.MediaSubTitle `json:"media_subtitle,omitempty" xml:"http://search.yahoo.com/mrss/ subTitle,omitempty"`

	// MediaTexts a list of texts for the object.
	MediaTexts externalRef7.MediaTexts `json:"media_texts" xml:"text,omitempty"`

	// MediaThumbnails a list of thumbnails for the object.
	MediaThumbnails externalRef7.MediaThumbnails `json:"media_thumbnails" xml:"thumbnail,omitempty"`

	// MediaTitle is the title of the particular media object.
	MediaTitle *externalRef7.MediaTitle `json:"media_title" xml:"http://search.yahoo.com/mrss/ title,omitempty"`

	// SYUdatePeriod is the period over which the channel format is updated.
	SYUdatePeriod *externalRef8.SYUpdatePeriod `json:"update_period,omitempty" validate:"omitempty,oneof=hourly daily weekly monthly yearly" xml:"http://purl.org/rss/1.0/modules/syndication/ updatePeriod,omitempty"`

	// SYUpdateBase is a base date to be used in concert with updatePeriod and updateFrequency to calculate the publishing schedule.
	SYUpdateBase *externalRef8.SYUpdateBase `json:"update_base,omitempty" xml:"http://purl.org/rss/1.0/modules/syndication/ updateBase,omitempty"`

	// SYUpdateFrequency describes the frequency of updates in relation to the update period.
	SYUpdateFrequency *externalRef8.SYUpdateFrequency `json:"update_frequency,omitempty" validate:"omitempty,number,gte=1" xml:"http://purl.org/rss/1.0/modules/syndication/ updateFrequency,omitempty"`
	SourceAccount     []externalRef9.Account          `json:"SourceAccount,omitempty" xml:"https://source.scripting.com/ account,omitempty"`

	// SourceArchive is links to the calendar-structured archive for the feed.  The folder pointed to by this address contains one folder for each year, 2009, 2010, 2011, etc. Each of those folders contains one folder for each month, 01, 02, 03, 04, 05, 06, 07, 08, 09, 10, 11, 12. The month folders must be zero-padded to two places. Folders may be missing, indicating that there is no archived content for the month. Each of the month folders contains folders for the days of the month. Day folder names are also zero-padded to two places and may be missing if there were no updates on the given day. Each day folder contains a file named rss.xml, unless the optional <source:filename> sub-element is supplied, which overrides the default. This makes it possible for a single calendar structure to store the archive of more than one feed.
	SourceArchive *externalRef9.Archive `json:"source_archive,omitempty" xml:"https://source.scripting.com/ archive,omitempty"`

	// SourceBlogroll points to the blogroll for the site associated with the feed, an OPML subscription list.
	SourceBlogroll *externalRef9.Blogroll `json:"source_blogroll,omitempty" validate:"omitempty,url" xml:"https://source.scripting.com/ blogroll,omitempty"`

	// SourceCloud provides a lot of information about the cloud server in a verbose way, specifying the domain, port, path and protocol.
	SourceCloud *externalRef9.Cloud `json:"source_cloud,omitempty" validate:"omitempty,url" xml:"https://source.scripting.com/ cloud,omitempty"`

	// SourceLikes is an instance of the the scripting.com likes software (a Node application) or a server that emulates its API.
	// Feed readers can use the server URL to form a like icon for each item that integrates with other feed readers. Perhaps the beginning of a way to build a connection between people who read a blog via various feed reader software. A demo app provides example code in JavaScript.
	SourceLikes *externalRef9.Likes `json:"source_likes,omitempty" xml:"https://source.scripting.com/ likes,omitempty"`

	// SourceLocalTime is a simple entirely human-readable way for the editor of the site to see what time, in his or her time zone, the feed was last updated. Must-have for debugging and sanity-preservation if you have trouble converting GMT to local time in your head (as I do). The format here is entirely up to the editor of the site.
	SourceLocalTime *externalRef9.LocalTime `json:"source_localTime,omitempty" xml:"https://source.scripting.com/ localTime,omitempty"`

	// SourceSelf is the canonical URL for the feed.
	SourceSelf             *externalRef9.Self              `json:"source_self,omitempty" validate:"omitempty,url" xml:"https://source.scripting.com/ self,omitempty"`
	SourceSubscriptionList []externalRef9.SubscriptionList `json:"SourceSubscriptionList,omitempty" xml:"https://source.scripting.com/ subscriptionList,omitempty"`
	XMLName                xml.Name                        `json:"XMLName" validate:"required" xml:"channel"`
	AtomLink               *AtomLink                       `json:"atom_link" validate:"omitempty" xml:"http://www.w3.org/2005/Atom link,omitempty"`

	// Categories is a list of categories associated with the channel.
	Categories []Category `json:"category,omitempty" xml:"category,omitempty"`

	// Cloud specifies a web service that supports the rssCloud interface which can be implemented in HTTP-POST, XML-RPC or SOAP 1.1.
	// Its purpose is to allow processes to register with a cloud to be notified of updates to the channel, implementing a lightweight publish-subscribe protocol for RSS feeds.
	Cloud *Cloud `json:"cloud,omitempty" xml:"cloud,omitempty"`

	// Copyright Copyright notice for content in the channel.
	Copyright *string `json:"copyright,omitempty,omitzero" xml:"copyright,omitempty"`

	// DcContributor is an entity responsible for making contributions to the resource.
	// The guidelines for using names of persons or organizations as creators apply to contributors.
	DcContributor externalRef3.Contributor `json:"dc_contributor,omitempty" xml:"http://purl.org/dc/elements/1.1/ contributor,omitempty"`

	// DcCoverage is the spatial or temporal topic of the resource, spatial applicability of the resource, or jurisdiction under which the resource is relevant.
	// Spatial topic and spatial applicability may be a named place or a location specified by its geographic coordinates. Temporal topic may be a named period, date, or date range. A jurisdiction may be a named administrative entity or a geographic place to which the resource applies. Recommended practice is to use a controlled vocabulary such as the Getty Thesaurus of Geographic Names [TGN]. Where appropriate, named places or time periods may be used in preference to numeric identifiers such as sets of coordinates or date ranges. Because coverage is so broadly defined, it is preferable to use the more specific subproperties Temporal Coverage and Spatial Coverage.
	DcCoverage externalRef3.Coverage `json:"dc_coverage,omitempty" xml:"http://purl.org/dc/elements/1.1/ coverage,omitempty"`

	// DcCreator is an entity responsible for making the resource.
	// Recommended practice is to identify the creator with a URI. If this is not possible or feasible, a literal value that identifies the creator may be provided.
	DcCreator externalRef3.Creator `json:"dc_creator,omitempty" xml:"http://purl.org/dc/elements/1.1/ creator,omitempty"`

	// DcDate is a point or period of time associated with an event in the lifecycle of the resource.
	// Date may be used to express temporal information at any level of granularity. Recommended practice is to express the date, date/time, or period of time according to ISO 8601-1 [ISO 8601-1] or a published profile of the ISO standard, such as the W3C Note on Date and Time Formats [W3CDTF] or the Extended Date/Time Format Specification [EDTF]. If the full date is unknown, month and year (YYYY-MM) or just year (YYYY) may be used. Date ranges may be specified using ISO 8601 period of time specification in which start and end dates are separated by a '/' (slash) character. Either the start or end date may be missing.
	DcDate externalRef3.Date `json:"dc_date,omitempty" xml:"http://purl.org/dc/elements/1.1/ date,omitempty"`

	// DcDescription is an account of the resource.
	// Description may include but is not limited to: an abstract, a table of contents, a graphical representation, or a free-text account of the resource.
	DcDescription externalRef3.Description `json:"dc_description,omitempty" xml:"http://purl.org/dc/elements/1.1/ description,omitempty"`

	// DcFormat is the file format, physical medium, or dimensions of the resource.
	// Recommended practice is to use a controlled vocabulary where available. For example, for file formats one could use the list of Internet Media Types [MIME]. Examples of dimensions include size and duration.
	DcFormat externalRef3.Format `json:"dc_format,omitempty" xml:"http://purl.org/dc/elements/1.1/ format,omitempty"`

	// DcIdentifier is an unambiguous reference to the resource within a given context.
	// Recommended practice is to identify the resource by means of a string conforming to an identification system. Examples include International Standard Book Number (ISBN), Digital Object Identifier (DOI), and Uniform Resource Name (URN). Persistent identifiers should be provided as HTTP URIs.
	DcIdentifier externalRef3.Identifier `json:"dc_identifier,omitempty" xml:"http://purl.org/dc/elements/1.1/ identifier,omitempty"`

	// DcLanguage is a language of the resource.
	// Recommended practice is to use either a non-literal value representing a language from a controlled vocabulary such as ISO 639-2 or ISO 639-3, or a literal value consisting of an IETF Best Current Practice 47 [IETF-BCP47] language tag.
	DcLanguage externalRef3.Language `json:"dc_language,omitempty" xml:"http://purl.org/dc/elements/1.1/ language,omitempty"`

	// DcPublisher is an entity responsible for making the resource available.
	DcPublisher externalRef3.Publisher `json:"dc_publisher,omitempty" xml:"http://purl.org/dc/elements/1.1/ publisher,omitempty"`

	// DcRelation is a related resource.
	// Recommended practice is to identify the related resource by means of a URI. If this is not possible or feasible, a string conforming to a formal identification system may be provided.
	DcRelation externalRef3.Relation `json:"dc_relation,omitempty" xml:"http://purl.org/dc/elements/1.1/ relation,omitempty"`

	// DcRights is information about rights held in and over the resource.
	// Typically, rights information includes a statement about various property rights associated with the resource, including intellectual property rights. Recommended practice is to refer to a rights statement with a URI. If this is not possible or feasible, a literal value (name, label, or short text) may be provided.
	DcRights externalRef3.Rights `json:"dc_rights,omitempty" xml:"http://purl.org/dc/elements/1.1/ rights,omitempty"`

	// DcSource is a related resource from which the described resource is derived.
	// This property is intended to be used with non-literal values. The described resource may be derived from the related resource in whole or in part. Best practice is to identify the related resource by means of a URI or a string conforming to a formal identification system.
	DcSource externalRef3.Source `json:"dc_source,omitempty" xml:"http://purl.org/dc/elements/1.1/ source,omitempty"`

	// DcSubject is a topic of the resource.
	// Recommended practice is to refer to the subject with a URI. If this is not possible or feasible, a literal value that identifies the subject may be provided. Both should preferably refer to a subject in a controlled vocabulary.
	DcSubject externalRef3.Subject `json:"dc_subject,omitempty" xml:"http://purl.org/dc/elements/1.1/ subject,omitempty"`

	// DcTitle is a name given to the resource.
	DcTitle externalRef3.Title `json:"dc_title,omitempty" xml:"http://purl.org/dc/elements/1.1/ title,omitempty"`

	// DcType is the nature or genre of the resource.
	// Recommended practice is to use a controlled vocabulary such as the DCMI Type Vocabulary [DCMI-TYPE]. To describe the file format, physical medium, or dimensions of the resource, use the property Format.
	DcType externalRef3.Type `json:"dc_type,omitempty" xml:"http://purl.org/dc/elements/1.1/ type,omitempty"`

	// Description is a phrase or sentence describing the channel.
	Description string `json:"description" validate:"required" xml:"description"`

	// Docs A URL that points to the documentation for the format used in the RSS file. It's probably a pointer to this page. It's for people who might stumble across an RSS file on a Web server 25 years from now and wonder what it is.
	Docs *string `json:"docs,omitempty,omitzero" validate:"omitempty,url" xml:"docs,omitempty"`

	// Generator is a string indicating the program used to generate the channel.
	Generator *string `json:"generator,omitempty,omitzero" xml:"generator,omitempty"`

	// Image contains details of a GIF, JPEG or PNG image that can be displayed with the channel.
	Image *Image `json:"image,omitempty" xml:"image,omitempty"`

	// Items is a list of the current items published to the channel.
	Items []Item `json:"items,omitempty" validate:"omitempty,dive,validateFn" xml:"item,omitempty"`

	// Language is the language the channel is written in. This allows aggregators to group all Italian language sites, for example, on a single page.
	Language *string `json:"language,omitempty,omitzero" validate:"omitempty,iso3166_1_alpha2|iso3166_1_alpha3|bcp47_language_tag" xml:"language,omitempty"`

	// LastBuildDate is the last time the content of the channel changed.
	LastBuildDate *LastBuildDate `json:"last_build_date" validate:"omitempty" xml:"lastBuildDate,omitempty"`

	// Link is the URL to the HTML website corresponding to the channel.
	Link string `json:"link" validate:"required,url" xml:"link"`

	// ManagingEditor is the email address for person responsible for editorial content.
	ManagingEditor *string `json:"managing_editor" xml:"managingEditor,omitempty"`

	// PubDate is the publication date of the content.
	PubDate *PubDate `json:"pub_date" validate:"omitempty" xml:"pubDate,omitempty"`

	// Rating contains a rating for the element.
	Rating *Rating `json:"rating,omitempty" xml:"rating,omitempty"`

	// SkipDays is a hint for aggregators telling them which days they can skip. This
	SkipDays *SkipDays `json:"skip_days" xml:"skipDays"`

	// SkipHours is a hint for aggregators telling them which hours they can skip.
	SkipHours *SkipHours `json:"skip_hours" xml:"skipHours,omitempty"`

	// TextInput The purpose of the <textInput> element is something of a mystery. You can use it to specify a search engine box. Or to allow a reader to provide feedback. Most aggregators ignore it.
	TextInput *TextInput `json:"textInput,omitempty" xml:"textInput,omitempty"`

	// Title is the name of the channel. It's how people refer to your service. If you have an HTML website that contains the same information as your RSS file, the title of your channel should be the same as the title of your website.
	Title string `json:"title" validate:"required" xml:"title"`

	// TTL stands for time to live. It's a number of minutes that indicates how long a channel can be cached before refreshing from the source.
	TTL TTL `json:"ttl,omitempty" validate:"omitempty,gte=1" xml:"ttl,omitempty"`

	// WebMaster is the email address for person responsible for technical issues relating to channel.
	WebMaster *string `json:"web_master" xml:"webMaster,omitempty"`
}

// Cloud specifies a web service that supports the rssCloud interface which can be implemented in HTTP-POST, XML-RPC or SOAP 1.1.
// Its purpose is to allow processes to register with a cloud to be notified of updates to the channel, implementing a lightweight publish-subscribe protocol for RSS feeds.
type Cloud struct {
	Domain            string        `json:"domain" validate:"required" xml:"domain,attr"`
	Path              string        `json:"path" validate:"required" xml:"path,attr"`
	Port              int           `json:"port" validate:"required" xml:"port,attr"`
	Protocol          CloudProtocol `json:"protocol" validate:"required" xml:"protocol,attr"`
	RegisterProcedure string        `json:"registerProcedure" validate:"omitempty,required" xml:"registerProcedure,attr"`
}

// CloudProtocol defines model for Cloud.Protocol.
type CloudProtocol string

// Comments is the URL of the comments page for the item.
type Comments = string

// Enclosure describes a media object.
type Enclosure struct {
	// Length indicates how big the enclosure is in bytes.
	Length int `json:"length" validate:"number" xml:"length,attr"`

	// Type indicates the MIME type of the enclosure.
	Type string `json:"type" validate:"required" xml:"type,attr"`

	// URL indicates where the enclosure is located.
	URL string `json:"url" validate:"required,uri" xml:"url,attr"`
}

// GUID is a string that uniquely identifies an item.
type GUID struct {
	// IsPermaLink If true the guid is assumed to be a URL. If its value is false, the guid may not be assumed to be a url, or a url to anything in particular.
	IsPermaLink bool   `json:"is_permalink" xml:"isPermaLink,attr,omitempty"`
	Value       string `json:"value" xml:",chardata"`
}

// Image contains details of a GIF, JPEG or PNG image that can be displayed with the channel.
type Image struct {
	// Description contains text that is included in the TITLE attribute of the link formed around the image in the HTML rendering.
	Description *string `json:"description,omitempty" xml:"description,omitempty"`

	// Height indicates the height of the image in pixels.
	Height *int `json:"height,omitempty" validate:"omitempty,gt=0,lte=400" xml:"height,omitempty"`

	// Link is the URL of the site, when the channel is rendered, the image is a link to the site. (Note, in practice the image <title> and <link> should have the same value as the channel's <title> and <link>.
	Link string `json:"link" validate:"required_without=URL,omitempty,url" xml:"link,omitempty"`

	// Title describes the image, it's used in the ALT attribute of the HTML <img> tag when the channel is rendered in HTML.
	Title string `json:"title" validate:"required" xml:"title"`

	// URL is the URL of a GIF, JPEG or PNG image that represents the channel.
	URL string `json:"url" validate:"required_without=link,omitempty,url" xml:"url"`

	// Width indicates the width of the image in pixels.
	Width *int `json:"width,omitempty" validate:"omitempty,gt=0,lte=144" xml:"width,omitempty"`
}

// Item An item may represent a "story" -- much like a story in a newspaper or magazine; if so its description is a synopsis of the story, and the link points to the full story. An item may also be complete in itself, if so, the description contains the text (entity-encoded HTML is allowed; see examples), and the link and title may be omitted. All elements of an item are optional, however at least one of title or description must be present.
type Item struct {
	// ContentEncoded is an element whose contents are the entity-encoded or CDATA-escaped version of the content of the item.
	ContentEncoded *externalRef8.ContentEncoded `json:"content_encoded,omitempty" xml:"http://purl.org/rss/1.0/modules/content/ encoded,omitempty"`

	// MediaBackLinks allows inclusion of all the URLs pointing to a media object.
	MediaBackLinks externalRef7.MediaBacklinks `json:"media_backlinks,omitempty" xml:"http://search.yahoo.com/mrss/ backLink,omitempty"`

	// MediaCategory allows a taxonomy to be set that gives an indication of the type of media content, and its particular contents.
	MediaCategory *externalRef7.MediaCategory `json:"media_category" xml:"http://search.yahoo.com/mrss/ category,omitempty"`

	// MediaComments is a list of comments the media object has received.
	MediaComments externalRef7.MediaComments `json:"media_comments"`

	// MediaCommunity stands for the community related content. This allows inclusion of the user perception about a media object in the form of view count, ratings and tags.
	MediaCommunity *externalRef7.MediaCommunity `json:"media_community" xml:"http://search.yahoo.com/mrss/ community,omitempty"`

	// MediaContent can be used to publish any type of media.
	MediaContent *externalRef7.MediaContent `json:"media_content,omitempty" validate:"omitempty,validateFn" xml:"http://search.yahoo.com/mrss/ content,omitempty"`

	// MediaCopyright is copyright information for the media object.
	MediaCopyright *externalRef7.MediaCopyright `json:"media_copyright" xml:"media copyright,omitempty"`

	// MediaCredits a list of credits for the object.
	MediaCredits externalRef7.MediaCredits `json:"media_credits" xml:"credit,omitempty"`

	// MediaDescription is a short description describing the media object typically a sentence in length.
	MediaDescription *externalRef7.MediaDescription `json:"media_description" xml:"http://search.yahoo.com/mrss/ description,omitempty"`

	// MediaEmbed allows inclusion of player-specific information in the form of key-value (Param) pairs.
	MediaEmbed *externalRef7.MediaEmbed `json:"media_embed" xml:"http://search.yahoo.com/mrss/ embed,omitempty"`

	// MediaGroup allows grouping of <media:content> elements that are effectively the same content, yet different representations. For instance: the same song recorded in both the WAV and MP3 format.
	MediaGroup *externalRef7.MediaGroup `json:"media_group,omitempty" xml:"http://search.yahoo.com/mrss/ group,omitempty"`

	// MediaHashes a list of hashes for the object.
	MediaHashes externalRef7.MediaHashes `json:"media_hashes" xml:"hash,omitempty"`

	// MediaKeywords are highly relevant keywords describing the media object with typically a maximum of 10 words. The keywords and phrases should be comma-delimited.
	MediaKeywords *externalRef7.MediaKeywords `json:"media_keywords" xml:"http://search.yahoo.com/mrss/ keywords,omitempty"`

	// MediaLicense link to specify the machine-readable license associated with the content.
	MediaLicense *externalRef7.MediaLicense `json:"media_license" xml:"http://search.yahoo.com/mrss/ license,omitempty"`

	// MediaPeerLink contains P2P link.
	MediaPeerLink *externalRef7.MediaPeerLink `json:"media_peerlink" xml:"http://search.yahoo.com/mrss/ peerLink,omitempty"`

	// MediaPlayer allows the media object to be accessed through a web browser media player console.
	MediaPlayer *externalRef7.MediaPlayer `json:"media_player" xml:"http://search.yahoo.com/mrss/ player,omitempty"`

	// MediaPrice includes pricing information about a media object. If this tag is not present, the media object is supposed to be free.
	MediaPrice *externalRef7.MediaPrice `json:"media_price" xml:"http://search.yahoo.com/mrss/ price,omitempty"`

	// MediaRating allows the permissible audience to be declared. If this element is not included, it assumes that no restrictions are necessary.
	MediaRating *externalRef7.MediaRating `json:"media_rating" xml:"http://search.yahoo.com/mrss/ rating,omitempty"`

	// MediaResponses allows inclusion of a list of all media responses a media object has received.
	MediaResponses externalRef7.MediaResponses `json:"media_responses" xml:"http://search.yahoo.com/mrss/ response,omitempty"`

	// MediaRestriction allows restrictions to be placed on the aggregator rendering the media in the feed.
	MediaRestriction *externalRef7.MediaRestriction `json:"media_restriction" validate:"omitempty,validateFn" xml:"http://search.yahoo.com/mrss/ restriction,omitempty"`

	// MediaRights specifies the rights information of a media object.
	MediaRights *externalRef7.MediaRights `json:"media_rights" xml:"http://search.yahoo.com/mrss/ rights,omitempty"`

	// MediaScenes specifies various scenes within a media object.
	MediaScenes externalRef7.MediaScenes `json:"media_scenes" xml:"http://search.yahoo.com/mrss/ scene,omitempty"`

	// MediaStatus specifies the status of a media object -- whether it's still active or it has been blocked/deleted.
	MediaStatus *externalRef7.MediaStatus `json:"media_status" xml:"http://search.yahoo.com/mrss/ status,omitempty"`

	// MediaSubTitle contains subtitle/CC link.
	MediaSubTitle *externalRef7.MediaSubTitle `json:"media_subtitle,omitempty" xml:"http://search.yahoo.com/mrss/ subTitle,omitempty"`

	// MediaTexts a list of texts for the object.
	MediaTexts externalRef7.MediaTexts `json:"media_texts" xml:"text,omitempty"`

	// MediaThumbnails a list of thumbnails for the object.
	MediaThumbnails externalRef7.MediaThumbnails `json:"media_thumbnails" xml:"thumbnail,omitempty"`

	// MediaTitle is the title of the particular media object.
	MediaTitle *externalRef7.MediaTitle `json:"media_title" xml:"http://search.yahoo.com/mrss/ title,omitempty"`

	// PermaLink is defined as a URL for a resource that is always available (similar to a PURL). Some weblogs cycle through articles and a URL may become invalid after a period of time. Permalinks provide a link that is always available to and should be provided within RSS so that clients can use this instead of a temporary link.
	PermaLink *externalRef8.PermaLink `json:"link_permalink,omitempty" xml:"http://purl.org/rss/1.0/modules/link/ permalink,omitempty"`

	// SourceComments are links to comments for this item.
	SourceComments *externalRef9.Comments `json:"source_comments,omitempty" xml:"https://source.scripting.com/ comments,omitempty"`

	// SourceInReplyTo identifies the item that this item is in reply to.
	SourceInReplyTo *externalRef9.InReplyTo `json:"source_inReplyTo,omitempty" xml:"https://source.scripting.com/ inReplyTo,omitempty"`

	// SourceLinkFill is the unshortened version of <link>.
	SourceLinkFill *externalRef9.LinkFull `json:"source_linkFull,omitempty" xml:"https://source.scripting.com/ linkFull,omitempty"`

	// SourceMarkdown is the source of the item-level description sub-element using Markdown to encode styling and links. If your feed presenter can understand Markdown, you should use this as the source for the display of the item.
	SourceMarkdown *externalRef9.Markdown `json:"source_markdown,omitempty" xml:"https://source.scripting.com/ markdown,omitempty"`
	SourceOutline  *externalRef9.Outline  `json:"source_outline,omitempty" xml:"https://source.scripting.com/ outline,omitempty"`

	// Alt is the meters above the local reference ellipsoid.
	Alt      *externalRef2.Altitude `json:"alt,omitempty" xml:"http://www.w3.org/2003/01/geo/wgs84_pos# alt,omitempty"`
	AtomLink *AtomLink              `json:"atom_link" validate:"omitempty" xml:"http://www.w3.org/2005/Atom link,omitempty"`

	// Author is the email address of the author of the item. For newspapers and magazines syndicating via RSS, the author is the person who wrote the article that the <item> describes. For collaborative weblogs, the author of the item might be different from the managing editor or webmaster. For a weblog authored by a single individual it would make sense to omit the <author> element.
	Author *Author `json:"author,omitempty" xml:"author,omitempty"`

	// Box is a bounding box as two coordinate pairs: the lower (southwest) corner, then the upper (northeast) corner (georss:box).
	Box *externalRef4.Box `json:"box,omitempty" xml:"http://www.georss.org/georss box"`

	// Categories is a list of categories associated with the channel.
	Categories []Category `json:"categories,omitempty" xml:"category,omitempty"`

	// Circle a center point plus a radius in meters (georss:circle).
	Circle *externalRef4.Circle `json:"circle,omitempty" xml:"http://www.georss.org/georss circle"`

	// Comments is the URL of the comments page for the item.
	Comments *Comments `json:"comments,omitempty" validate:"omitempty,url" xml:"comments,omitempty"`

	// DcContributor is an entity responsible for making contributions to the resource.
	// The guidelines for using names of persons or organizations as creators apply to contributors.
	DcContributor externalRef3.Contributor `json:"dc_contributor,omitempty" xml:"http://purl.org/dc/elements/1.1/ contributor,omitempty"`

	// DcCoverage is the spatial or temporal topic of the resource, spatial applicability of the resource, or jurisdiction under which the resource is relevant.
	// Spatial topic and spatial applicability may be a named place or a location specified by its geographic coordinates. Temporal topic may be a named period, date, or date range. A jurisdiction may be a named administrative entity or a geographic place to which the resource applies. Recommended practice is to use a controlled vocabulary such as the Getty Thesaurus of Geographic Names [TGN]. Where appropriate, named places or time periods may be used in preference to numeric identifiers such as sets of coordinates or date ranges. Because coverage is so broadly defined, it is preferable to use the more specific subproperties Temporal Coverage and Spatial Coverage.
	DcCoverage externalRef3.Coverage `json:"dc_coverage,omitempty" xml:"http://purl.org/dc/elements/1.1/ coverage,omitempty"`

	// DcCreator is an entity responsible for making the resource.
	// Recommended practice is to identify the creator with a URI. If this is not possible or feasible, a literal value that identifies the creator may be provided.
	DcCreator externalRef3.Creator `json:"dc_creator,omitempty" xml:"http://purl.org/dc/elements/1.1/ creator,omitempty"`

	// DcDate is a point or period of time associated with an event in the lifecycle of the resource.
	// Date may be used to express temporal information at any level of granularity. Recommended practice is to express the date, date/time, or period of time according to ISO 8601-1 [ISO 8601-1] or a published profile of the ISO standard, such as the W3C Note on Date and Time Formats [W3CDTF] or the Extended Date/Time Format Specification [EDTF]. If the full date is unknown, month and year (YYYY-MM) or just year (YYYY) may be used. Date ranges may be specified using ISO 8601 period of time specification in which start and end dates are separated by a '/' (slash) character. Either the start or end date may be missing.
	DcDate externalRef3.Date `json:"dc_date,omitempty" xml:"http://purl.org/dc/elements/1.1/ date,omitempty"`

	// DcDescription is an account of the resource.
	// Description may include but is not limited to: an abstract, a table of contents, a graphical representation, or a free-text account of the resource.
	DcDescription externalRef3.Description `json:"dc_description,omitempty" xml:"http://purl.org/dc/elements/1.1/ description,omitempty"`

	// DcFormat is the file format, physical medium, or dimensions of the resource.
	// Recommended practice is to use a controlled vocabulary where available. For example, for file formats one could use the list of Internet Media Types [MIME]. Examples of dimensions include size and duration.
	DcFormat externalRef3.Format `json:"dc_format,omitempty" xml:"http://purl.org/dc/elements/1.1/ format,omitempty"`

	// DcIdentifier is an unambiguous reference to the resource within a given context.
	// Recommended practice is to identify the resource by means of a string conforming to an identification system. Examples include International Standard Book Number (ISBN), Digital Object Identifier (DOI), and Uniform Resource Name (URN). Persistent identifiers should be provided as HTTP URIs.
	DcIdentifier externalRef3.Identifier `json:"dc_identifier,omitempty" xml:"http://purl.org/dc/elements/1.1/ identifier,omitempty"`

	// DcLanguage is a language of the resource.
	// Recommended practice is to use either a non-literal value representing a language from a controlled vocabulary such as ISO 639-2 or ISO 639-3, or a literal value consisting of an IETF Best Current Practice 47 [IETF-BCP47] language tag.
	DcLanguage externalRef3.Language `json:"dc_language,omitempty" xml:"http://purl.org/dc/elements/1.1/ language,omitempty"`

	// DcPublisher is an entity responsible for making the resource available.
	DcPublisher externalRef3.Publisher `json:"dc_publisher,omitempty" xml:"http://purl.org/dc/elements/1.1/ publisher,omitempty"`

	// DcRelation is a related resource.
	// Recommended practice is to identify the related resource by means of a URI. If this is not possible or feasible, a string conforming to a formal identification system may be provided.
	DcRelation externalRef3.Relation `json:"dc_relation,omitempty" xml:"http://purl.org/dc/elements/1.1/ relation,omitempty"`

	// DcRights is information about rights held in and over the resource.
	// Typically, rights information includes a statement about various property rights associated with the resource, including intellectual property rights. Recommended practice is to refer to a rights statement with a URI. If this is not possible or feasible, a literal value (name, label, or short text) may be provided.
	DcRights externalRef3.Rights `json:"dc_rights,omitempty" xml:"http://purl.org/dc/elements/1.1/ rights,omitempty"`

	// DcSource is a related resource from which the described resource is derived.
	// This property is intended to be used with non-literal values. The described resource may be derived from the related resource in whole or in part. Best practice is to identify the related resource by means of a URI or a string conforming to a formal identification system.
	DcSource externalRef3.Source `json:"dc_source,omitempty" xml:"http://purl.org/dc/elements/1.1/ source,omitempty"`

	// DcSubject is a topic of the resource.
	// Recommended practice is to refer to the subject with a URI. If this is not possible or feasible, a literal value that identifies the subject may be provided. Both should preferably refer to a subject in a controlled vocabulary.
	DcSubject externalRef3.Subject `json:"dc_subject,omitempty" xml:"http://purl.org/dc/elements/1.1/ subject,omitempty"`

	// DcTitle is a name given to the resource.
	DcTitle externalRef3.Title `json:"dc_title,omitempty" xml:"http://purl.org/dc/elements/1.1/ title,omitempty"`

	// DcType is the nature or genre of the resource.
	// Recommended practice is to use a controlled vocabulary such as the DCMI Type Vocabulary [DCMI-TYPE]. To describe the file format, physical medium, or dimensions of the resource, use the property Format.
	DcType externalRef3.Type `json:"dc_type,omitempty" xml:"http://purl.org/dc/elements/1.1/ type,omitempty"`

	// Description is a short description of the item.
	Description ItemDescription `json:"description,omitzero" validate:"required_without=Title" xml:"description"`

	// Elev contains “common” GPS elevation readings, i.e. height in meters referenced to the WGS84 ellipsoid. This is a reading that should be easy to get from any GPS device.
	Elev *float64 `json:"elev,omitempty" xml:"http://www.georss.org/georss elev"`

	// Enclosure describes a media object.
	Enclosure      *Enclosure `json:"enclosure,omitempty" xml:"enclosure,omitempty"`
	FeatureName    *string    `json:"featureName,omitempty" xml:"http://www.georss.org/georss featurename,omitempty"`
	FeatureTypeTag *string    `json:"featureTypeTag,omitempty" xml:"http://www.georss.org/georss featuretypetag,omitempty"`

	// Floor contains the floor number of a building. In some countries the numbering is different than in other countries, but since we’ll know the location of the building, it should be fairly unambiguous. The definition of “floor” as used in GeoRSS is consistent with the IETF[3] and NENA definitions as required for the Next Generation 911 system in the US.
	Floor *int `json:"floor,omitempty" xml:"http://www.georss.org/georss floor"`

	// GUID is a string that uniquely identifies an item.
	GUID *GUID `json:"guid,omitempty" xml:"guid,omitempty"`

	// Image contains details of a GIF, JPEG or PNG image that can be displayed with the channel.
	Image *Image `json:"image,omitempty" xml:"image,omitempty"`

	// Lat is the latitude in decimal degress
	Lat externalRef2.Latitude `json:"lat" validate:"required,gte=-90,lte=90" xml:"http://www.w3.org/2003/01/geo/wgs84_pos# lat"`

	// Line is an ordered sequence of two or more coordinate pairs (a LineString, georss:line).
	Line externalRef4.Line `json:"line,omitempty" xml:"http://www.georss.org/georss line"`

	// Link is the URL of the item.
	Link string `json:"link,omitzero" validate:"required_without=Description,url" xml:"link,omitempty"`

	// Lon is the longitude in decimal degress
	Lon externalRef2.Longitude `json:"lon" validate:"required,gte=-180,lte=180" xml:"http://www.w3.org/2003/01/geo/wgs84_pos# long"`

	// Point a single coordinate pair (georss:point).
	Point *externalRef4.Point `json:"point,omitempty" xml:"http://www.georss.org/georss point"`

	// Polygon a closed linear ring -- four or more coordinate pairs, with the first and last identical.
	Polygon externalRef4.Polygon `json:"polygon,omitempty" xml:"http://www.georss.org/georss polygon"`

	// PubDate is the publication date of the content.
	PubDate *PubDate `json:"pub_date" validate:"omitempty" xml:"pubDate,omitempty"`

	// Radius indicates the size in meters of a radius or buffer around the geometry object, for example, radius of circular area around a point geometry.
	Radius          *float64 `json:"radius,omitempty" xml:"http://www.georss.org/georss radius"`
	RelationshipTag *string  `json:"relationshipTag,omitempty" xml:"http://www.georss.org/georss relationshiptag,omitempty"`

	// Source The RSS channel that the item came from.
	Source *Source `json:"source,omitempty" xml:"source,omitempty"`

	// Title is the title of the item.
	Title string `json:"title,omitzero" validate:"required_without=Description" xml:"title,omitempty"`

	// Where wraps exactly one of the four GML geometries (georss:where).
	Where *externalRef4.Where `json:"where,omitempty" xml:"http://www.georss.org/georss where"`
}

// ItemDescription is a short description of the item.
type ItemDescription struct {
	// CDATA indicates whether the data was CDATA encoded.
	CDATA bool `json:"cdata"`

	// Value is the actual value.
	Value string `json:"value"`
}

// LastBuildDate is the last time the content of the channel changed.
type LastBuildDate = Timestamp

// PubDate is the publication date of the content.
type PubDate = Timestamp

// RSS represents an RSS document.
type RSS struct {
	// Channel is the element containing metadata (Channel elements) and items.
	Channel Channel `json:"channel" validate:"required" xml:"channel"`

	// Namespaces contains all namespaces in use by this RSS feed.
	Namespaces []externalRef1.Namespace `json:"namespaces,omitempty"`

	// Version specifies the version of RSS that the document conforms to.
	Version RSSVersion `json:"version" validate:"required,oneof=0.91 0.92 2.0 2.0.1" xml:"version,attr"`
}

// RSSVersion specifies the version of RSS that the document conforms to.
type RSSVersion string

// Rating contains a rating for the element.
type Rating = string

// SkipDays is a hint for aggregators telling them which days they can skip. This
type SkipDays struct {
	Day *[]SkipDaysDay `json:"day,omitempty" validate:"omitempty,dive,oneof=Monday Tuesday Wednesday Thursday Friday Saturday Sunday" xml:"day"`
}

// SkipDaysDay is a day of the week to skip.
type SkipDaysDay string

// SkipHours is a hint for aggregators telling them which hours they can skip.
type SkipHours struct {
	Hour []int `json:"hour,omitempty" validate:"omitempty,dive,gte=0,lte=23" xml:"hour,omitempty"`
}

// Source The RSS channel that the item came from.
type Source struct {
	URL   string `json:"url" validate:"required,url" xml:"url,attr"`
	Value string `json:"value" xml:",chardata"`
}

// TTL stands for time to live. It's a number of minutes that indicates how long a channel can be cached before refreshing from the source.
type TTL = int

// TextInput The purpose of the <textInput> element is something of a mystery. You can use it to specify a search engine box. Or to allow a reader to provide feedback. Most aggregators ignore it.
type TextInput struct {
	// Description explains the text input area.
	Description string `json:"description" validate:"required" xml:"description"`

	// Link is the URL of the CGI script that processes text input requests.
	Link string `json:"link" validate:"required,uri" xml:"link"`

	// Name is the name of the text object in the text input area.
	Name string `json:"name" validate:"required" xml:"name"`

	// Title is the label of the Submit button in the text input area.
	Title string `json:"title" validate:"required" xml:"title"`
}

// Timestamp represents a timestamp for an object
type Timestamp struct {
	// Value is the timestamp value
	Value time.Time `json:"value"`
}
