// Package source provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package source

import (
	"encoding/xml"
	"time"
)

// Account The value of source:account is the username or screenname of the author of the feed on the indicated service.
type Account struct {
	// Service is the name of a service such as "instagram" or "mastodon". The value is case insensitive, so Bluesky is the same as blueSky.
	Service string `json:"service" validate:"required" xml:"service,attr"`

	// Value is the account name or id.
	Value string `json:"value" validate:"required" xml:",chardata"`
}

// Archive is links to the calendar-structured archive for the feed.  The folder pointed to by this address contains one folder for each year, 2009, 2010, 2011, etc. Each of those folders contains one folder for each month, 01, 02, 03, 04, 05, 06, 07, 08, 09, 10, 11, 12. The month folders must be zero-padded to two places. Folders may be missing, indicating that there is no archived content for the month. Each of the month folders contains folders for the days of the month. Day folder names are also zero-padded to two places and may be missing if there were no updates on the given day. Each day folder contains a file named rss.xml, unless the optional <source:filename> sub-element is supplied, which overrides the default. This makes it possible for a single calendar structure to store the archive of more than one feed.
type Archive struct {
	// URL is the address of the archive.
	URL string `json:"URL" validate:"required,url" xml:"https://source.scripting.com/ url"`

	// EndDay is a hyphen-delimited date (yyyy-mm-dd) for the last element in the archive.
	EndDay *ArchiveDay `json:"endDay,omitempty" xml:"https://source.scripting.com/ endDay"`

	// Filename is the filename in the directory.
	Filename *string `json:"filename,omitempty" xml:"https://source.scripting.com/ filename,omitempty"`

	// StartDay is a hyphen-delimited date, formatted as yyyy-mm-dd, for the first element of the archive.
	StartDay ArchiveDay `json:"startDay" validate:"required" xml:"https://source.scripting.com/ startDay"`
}

// ArchiveDay is source:archive's startDay/endDay: a bare yyyy-mm-dd date (no time-of-day or zone).
type ArchiveDay struct {
	Time time.Time `json:"time"`
}

// Blogroll points to the blogroll for the site associated with the feed, an OPML subscription list.
type Blogroll = string

// ChannelSource contains all channel-level items in the source namespace.
type ChannelSource struct {
	SourceAccount []Account `json:"SourceAccount,omitempty" xml:"https://source.scripting.com/ account,omitempty"`

	// SourceArchive is links to the calendar-structured archive for the feed.  The folder pointed to by this address contains one folder for each year, 2009, 2010, 2011, etc. Each of those folders contains one folder for each month, 01, 02, 03, 04, 05, 06, 07, 08, 09, 10, 11, 12. The month folders must be zero-padded to two places. Folders may be missing, indicating that there is no archived content for the month. Each of the month folders contains folders for the days of the month. Day folder names are also zero-padded to two places and may be missing if there were no updates on the given day. Each day folder contains a file named rss.xml, unless the optional <source:filename> sub-element is supplied, which overrides the default. This makes it possible for a single calendar structure to store the archive of more than one feed.
	SourceArchive *Archive `json:"archive,omitempty" xml:"https://source.scripting.com/ archive,omitempty"`

	// SourceBlogroll points to the blogroll for the site associated with the feed, an OPML subscription list.
	SourceBlogroll *Blogroll `json:"blogroll,omitempty" validate:"omitempty,url" xml:"https://source.scripting.com/ blogroll,omitempty"`

	// SourceCloud provides a lot of information about the cloud server in a verbose way, specifying the domain, port, path and protocol.
	SourceCloud *Cloud `json:"cloud,omitempty" validate:"omitempty,url" xml:"https://source.scripting.com/ cloud,omitempty"`

	// SourceLikes is an instance of the the scripting.com likes software (a Node application) or a server that emulates its API.
	// Feed readers can use the server URL to form a like icon for each item that integrates with other feed readers. Perhaps the beginning of a way to build a connection between people who read a blog via various feed reader software. A demo app provides example code in JavaScript.
	SourceLikes *Likes `json:"likes,omitempty" xml:"https://source.scripting.com/ likes,omitempty"`

	// SourceLocalTime is a simple entirely human-readable way for the editor of the site to see what time, in his or her time zone, the feed was last updated. Must-have for debugging and sanity-preservation if you have trouble converting GMT to local time in your head (as I do). The format here is entirely up to the editor of the site.
	SourceLocalTime *LocalTime `json:"localTime,omitempty" xml:"https://source.scripting.com/ localTime,omitempty"`

	// SourceSelf is the canonical URL for the feed.
	SourceSelf             *Self              `json:"self,omitempty" validate:"omitempty,url" xml:"https://source.scripting.com/ self,omitempty"`
	SourceSubscriptionList []SubscriptionList `json:"SourceSubscriptionList,omitempty" xml:"https://source.scripting.com/ subscriptionList,omitempty"`
}

// Cloud provides a lot of information about the cloud server in a verbose way, specifying the domain, port, path and protocol.
type Cloud = string

// Comments are links to comments for this item.
type Comments struct {
	// Count is a number which says how many comments there are on this item.
	Count int `json:"count" validate:"required,gte=0" xml:"count,attr"`

	// FeedURL is the address of the feed containing the comments.
	FeedURL string `json:"feedURL" validate:"required,url" xml:"feedUrl,attr"`
}

// InReplyTo identifies the item that this item is in reply to.
type InReplyTo struct {
	// IsPermalink indicates whether the value is a permalink.
	IsPermalink *bool `json:"isPermalink,omitempty" xml:"isPermalink,attr"`

	// Value is a URL to the the original item.
	Value string `json:"value" validate:"required,url" xml:",chardata"`
}

// ItemSource contains all item-level items in the source namespace.
type ItemSource struct {
	// SourceComments are links to comments for this item.
	SourceComments *Comments `json:"comments,omitempty" xml:"https://source.scripting.com/ comments,omitempty"`

	// SourceInReplyTo identifies the item that this item is in reply to.
	SourceInReplyTo *InReplyTo `json:"inReplyTo,omitempty" xml:"https://source.scripting.com/ inReplyTo,omitempty"`

	// SourceLinkFill is the unshortened version of <link>.
	SourceLinkFill *LinkFull `json:"linkFull,omitempty" xml:"https://source.scripting.com/ linkFull,omitempty"`

	// SourceMarkdown is the source of the item-level description sub-element using Markdown to encode styling and links. If your feed presenter can understand Markdown, you should use this as the source for the display of the item.
	SourceMarkdown *Markdown `json:"markdown,omitempty" xml:"https://source.scripting.com/ markdown,omitempty"`
	SourceOutline  *Outline  `json:"outline,omitempty" xml:"https://source.scripting.com/ outline,omitempty"`
}

// Likes is an instance of the the scripting.com likes software (a Node application) or a server that emulates its API.
// Feed readers can use the server URL to form a like icon for each item that integrates with other feed readers. Perhaps the beginning of a way to build a connection between people who read a blog via various feed reader software. A demo app provides example code in JavaScript.
type Likes struct {
	// Server is the server URL.
	Server string `json:"server" validate:"required,url" xml:"server,attr"`
}

// LinkFull is the unshortened version of <link>.
type LinkFull = string

// LocalTime is a simple entirely human-readable way for the editor of the site to see what time, in his or her time zone, the feed was last updated. Must-have for debugging and sanity-preservation if you have trouble converting GMT to local time in your head (as I do). The format here is entirely up to the editor of the site.
type LocalTime = string

// Markdown is the source of the item-level description sub-element using Markdown to encode styling and links. If your feed presenter can understand Markdown, you should use this as the source for the display of the item.
type Markdown struct {
	// AsCDATA indicates the content is CDATA encoded.
	AsCDATA bool `json:"as_cdata"`

	// Value is the markdown content.
	Value string `json:"value" validate:"required"`
}

// Outline defines model for Outline.
type Outline struct {
	Attrs    []xml.Attr `json:"attrs,omitempty" xml:",any,attr"`
	Created  *string    `json:"created,omitempty" xml:"created,attr,omitempty"`
	Outlines []Outline  `json:"outlines,omitempty" xml:"https://source.scripting.com/ outline,omitempty"`
	Text     *string    `json:"text,omitempty" xml:"text,attr,omitempty"`
}

// Self is the canonical URL for the feed.
type Self = string

// SubscriptionList is the list of feeds the author of the feed follows.
type SubscriptionList struct {
	// URL is the http address of an OPML subscription list.
	URL string `json:"URL" validate:"required,url" xml:"url,attr"`

	// Value is the account name or id.
	Value *string `json:"value,omitempty" xml:",chardata"`
}
