---
openapi: '3.0.3'
info:
  version: 1.0.0
  title: Dublin Core RSS Extension
  description: >
    RDF Site Summary 1.0 Modules: Dublin Core OpenAPI model schema.

    https://web.resource.org/rss/1.0/modules/dc/
  contact:
    name: "Joshua Rich"
    email: joshua.rich@gmail.com
  license:
    identifier: AGPL-3.0-or-later
components:
  schemas:
    DCTitle:
      description: >
        is a name by which the resource is formally known.
      x-go-type: 'types.String'
      x-oapi-codegen-extra-tags:
        json: 'dc_title,omitempty'
        xml: 'http://purl.org/dc/elements/1.1/ title,omitempty'
      x-go-type-skip-optional-pointer: false
    DCDescription:
      description: >
        may include but is not limited to: an abstract, table of contents, reference to a graphical representation of
        content or a free-text account of the content.
      x-go-type: 'types.String'
      x-oapi-codegen-extra-tags:
        json: 'dc_description,omitempty'
        xml: 'http://purl.org/dc/elements/1.1/ description,omitempty'
      x-go-type-skip-optional-pointer: false
    DCContributor:
      description: >
        is an entity responsible for making contributions to the resource.
      x-go-type: 'types.String'
      x-oapi-codegen-extra-tags:
        json: 'dc_contributor,omitempty'
        xml: 'http://purl.org/dc/elements/1.1/ contributor,omitempty'
      x-go-type-skip-optional-pointer: false
    DCCreator:
      description: >
        is an entity primarily responsible for making the resource.
      x-go-type: 'types.String'
      x-oapi-codegen-extra-tags:
        json: 'dc_creator,omitempty'
        xml: 'http://purl.org/dc/elements/1.1/ creator,omitempty'
      x-go-type-skip-optional-pointer: false
    DCCoverage:
      description: >
        is the spatial or temporal topic of the resource, spatial applicability of the resource, or jurisdiction under
        which the resource is relevant.
      x-go-type: 'types.String'
      x-oapi-codegen-extra-tags:
        json: 'dc_coverage,omitempty'
        xml: 'http://purl.org/dc/elements/1.1/ coverage,omitempty'
      x-go-type-skip-optional-pointer: false
    DCFormat:
      description: >
        is the file format, physical medium, or dimensions of the resource.
      x-go-type: 'types.String'
      x-oapi-codegen-extra-tags:
        json: 'dc_format,omitempty'
        xml: 'http://purl.org/dc/elements/1.1/ format,omitempty'
      x-go-type-skip-optional-pointer: false
    DCIdentifier:
      description: >
        is an unambiguous reference to the resource within a given context.
      x-go-type: 'types.String'
      x-oapi-codegen-extra-tags:
        json: 'dc_identifier,omitempty'
        xml: 'http://purl.org/dc/elements/1.1/ identifier,omitempty'
      x-go-type-skip-optional-pointer: false
    DCPublisher:
      description: >
        is an entity responsible for making the resource available.
      x-go-type: 'types.String'
      x-oapi-codegen-extra-tags:
        json: 'dc_publisher,omitempty'
        xml: 'http://purl.org/dc/elements/1.1/ publisher,omitempty'
      x-go-type-skip-optional-pointer: false
    DCRelation:
      description: >
        is a related resource.
      x-go-type: 'types.String'
      x-oapi-codegen-extra-tags:
        json: 'dc_relation,omitempty'
        xml: 'http://purl.org/dc/elements/1.1/ relation,omitempty'
      x-go-type-skip-optional-pointer: false
    DCRights:
      description: >
        is information about rights held in and over the resource.
      type: object
      x-go-type: 'types.String'
      x-oapi-codegen-extra-tags:
        json: 'dc_rights,omitempty'
        xml: 'http://purl.org/dc/elements/1.1/ rights,omitempty'
      x-go-type-skip-optional-pointer: false
    DCSubject:
      description: >
        is the topic of the resource.
      x-go-type: 'types.String'
      x-oapi-codegen-extra-tags:
        json: 'dc_subject,omitempty'
        xml: 'http://purl.org/dc/elements/1.1/ subject,omitempty'
      x-go-type-skip-optional-pointer: false
    DCType:
      description: >
        is the nature or genre of the resource.
      x-go-type: 'types.String'
      x-oapi-codegen-extra-tags:
        json: 'dc_type,omitempty'
        xml: 'http://purl.org/dc/elements/1.1/ type,omitempty'
      x-go-type-skip-optional-pointer: false
    DCSource:
      description: >
        is a related resource from which the described resource is derived.
      x-go-type: 'types.String'
      x-oapi-codegen-extra-tags:
        json: 'dc_source,omitempty'
        xml: 'http://purl.org/dc/elements/1.1/ source,omitempty'
      x-go-type-skip-optional-pointer: false
    DCLanguage:
      description: >
        identifies the language used by the related resource using an HTML language code.
      allOf:
        - $ref: 'types-elements.yaml#/components/schemas/Language'
      x-oapi-codegen-extra-tags:
        json: 'dc_language,omitempty'
        xml: 'http://purl.org/dc/elements/1.1/ language,omitempty'
        validate: 'omitempty,bcp47_language_tag'
    DCDate:
      description: >
        is a point or period of time associated with an event in the lifecycle of the resource.
      x-go-type: types.DateTime
      x-oapi-codegen-extra-tags:
        json: 'dc_date,omitempty'
        xml: 'http://purl.org/dc/elements/1.1/ date,omitempty'
      x-go-type-skip-optional-pointer: false
    DublinCoreElements:
      description: >
        contains Dublin Core extension elements.
      type: object
      properties:
        DCTitle:
          $ref: '#/components/schemas/DCTitle'
        DCDescription:
          $ref: '#/components/schemas/DCDescription'
        DCContributor:
          $ref: '#/components/schemas/DCContributor'
        DCCreator:
          $ref: '#/components/schemas/DCCreator'
        DCCoverage:
          $ref: '#/components/schemas/DCCoverage'
        DCFormat:
          $ref: '#/components/schemas/DCFormat'
        DCIdentifier:
          $ref: '#/components/schemas/DCIdentifier'
        DCPublisher:
          $ref: '#/components/schemas/DCPublisher'
        DCRelation:
          $ref: '#/components/schemas/DCRelation'
        DCRights:
          $ref: '#/components/schemas/DCRights'
        DCSubject:
          $ref: '#/components/schemas/DCSubject'
        DCType:
          $ref: '#/components/schemas/DCType'
        DCSource:
          $ref: '#/components/schemas/DCSource'
        DCLanguage:
          $ref: '#/components/schemas/DCLanguage'
        DCDate:
          $ref: '#/components/schemas/DCDate'
