---
openapi: '3.1.0'
info:
  version: 1.0.0
  title: Extensions Plumbing Code
  description: >
    Additional types and methods that provide plumbing for specific extensions functionality.
  contact:
    name: 'Joshua Rich'
    email: joshua.rich@gmail.com
  license:
    identifier: MIT
components:
  schemas:
    Namespace:
      description: >
        is a single xmlns:prefix="uri" declaration.
      type: object
      required:
        - prefix
        - uri
      properties:
        prefix:
          description: the unique prefix of the namespace.
          type: string
        uri:
          description: the URI that points to the namespace.
          type: string
          x-go-name: URI
    Extension:
      description: >
        represents an element that is not defined in the schema.
      type: object
      required:
        - XMLName
        - content
      properties:
        XMLName:
          x-go-type: 'xml.Name'
          x-oapi-codegen-extra-tags:
            json: 'xml'
            validate: 'required'
        content:
          description: is the element value.
          type: string
          x-oapi-codegen-extra-tags:
            xml: ',innerxml'
            validate: 'required'
        attributes:
          description: are any attributes of the element.
          type: array
          items:
            x-go-type: xml.Attr
          x-go-type-skip-optional-pointer: true
          x-oapi-codegen-extra-tags:
            xml: ',any,attr'
