# Copyright 2025 Joshua Rich <joshua.rich@gmail.com>.
# SPDX-License-Identifier: 	AGPL-3.0-or-later

openapi: '3.0.3'
info:
  version: 1.0.0
  title: OPML
  description: >
    OPML specification.
    Based on https://opml.org/spec2.opml
paths: {}
components:
  schemas:
    Date:
      description: >
        is a date-time.
      x-go-type: types.DateTime
    OPML:
      description: >
        represents an OPML document.
      type: object
      required:
        - XMLName
        - head
        - body
        - version
      properties:
        XMLName:
          $ref: 'types.yaml#/components/schemas/XMLName'
        head:
          $ref: '#/components/schemas/Head'
        body:
          $ref: '#/components/schemas/Body'
        version:
          type: string
          x-oapi-codegen-extra-tags:
            xml: 'version,attr'
          xml:
            attribute: true
      xml:
        name: 'opml'
    Head:
      description: >
        represents the OPML <head> element.
      type: object
      xml:
        name: 'head'
      x-oapi-codegen-extra-tags:
        xml: 'head'
        validate: 'required'
      properties:
        title:
          description: >
            is the title of the document.
          type: string
          x-oapi-codegen-extra-tags:
            xml: 'title,omitempty'
        dateCreated:
          description: >
            is a date-time, indicating when the document was created.
          allOf:
            - $ref: '#/components/schemas/Date'
          x-oapi-codegen-extra-tags:
            xml: 'dateCreated,omitempty'
            validate: 'omitempty'
        dateModified:
          description: >
            is a date-time, indicating when the document was last modified.
          allOf:
            - $ref: '#/components/schemas/Date'
          x-oapi-codegen-extra-tags:
            xml: 'dateModified,omitempty'
            validate: 'omitempty,datetime'
        ownerName:
          description: >
            is the owner of the document.
          type: string
          x-oapi-codegen-extra-tags:
            xml: 'ownerName,omitempty'
        ownerEmail:
          description: >
            is the email address of the owner of the document.
          type: string
          x-oapi-codegen-extra-tags:
            xml: 'ownerEmail,omitempty'
            validate: 'omitempty,email'
        ownerId:
          description: >
            is the http address of a web page that contains information that
            allows a human reader to communicate with the author of the document
            via email or other means. It also may be used to identify the
            author. No two authors have the same ownerId.
          type: string
          x-go-name: OwnerID
          x-oapi-codegen-extra-tags:
            xml: 'ownerId,omitempty'
            validate: 'omitempty,url'
        docs:
          description: >
            is the http address of documentation for the format used in the OPML
            file. It's probably a pointer to this page for people who might
            stumble across the file on a web server 25 years from now and wonder
            what it is.
          type: string
          x-oapi-codegen-extra-tags:
            xml: 'docs,omitempty'
            validate: 'omitempty,url'
        expansionState:
          description: >
            is a comma-separated list of line numbers that are expanded. The
            line numbers in the list tell you which headlines to expand. The
            order is important. For each element in the list, X, starting at the
            first summit, navigate flatdown X times and expand. Repeat for each
            element in the list.
          type: string
          x-oapi-codegen-extra-tags:
            xml: 'expansionState,omitempty'
        vertScrollState:
          description: >
            is a number, saying which line of the outline is displayed on the
            top line of the window. This number is calculated with the expansion
            state already applied.
          type: string
          x-oapi-codegen-extra-tags:
            xml: 'vertScrollState,omitempty'
        windowTop:
          description: >
            is a number, the pixel location of the top edge of the window.
          type: string
          x-oapi-codegen-extra-tags:
            xml: 'windowTop,omitempty'
        windowLeft:
          description: >
            is a number, the pixel location of the left edge of the window.
          type: string
          x-oapi-codegen-extra-tags:
            xml: 'windowLeft,omitempty'
        windowBottom:
          description: >
            is a number, the pixel location of the bottom edge of the window.
          type: string
          x-oapi-codegen-extra-tags:
            xml: 'windowBottom,omitempty'
        windowRight:
          description: >
            is a number, the pixel location of the right edge of the window.
          type: string
          x-oapi-codegen-extra-tags:
            xml: 'windowRight,omitempty'
    Body:
      description: >
        represents the OPML <body> element.
      type: array
      items:
        $ref: '#/components/schemas/Outline'
      xml:
        name: 'body'
      x-oapi-codegen-extra-tags:
        xml: 'body>outline'
        validate: 'required,dive'
    Outline:
      description: >
        is an XML element containing at least one required attribute, text, and
        zero or more additional attributes. An <outline> may contain zero or
        more <outline> sub-elements. No attribute may be repeated within the
        same <outline> element.
      allOf:
        - $ref: '#/components/schemas/RSSOutline'
        - type: object
          required:
            - text
          properties:
            text:
              description: >
                is a textual description of the element.
              type: string
              x-oapi-codegen-extra-tags:
                xml: 'text,attr'
                validate: 'required'
              xml:
                attribute: true
            type:
              description: >
                defines how the other attributes of the element are interpreted.
              type: string
              x-oapi-codegen-extra-tags:
                xml: 'type,omitempty,attr'
              xml:
                attribute: true
            isComment:
              description: >
                is a string, either "true" or "false", indicating whether the outline
                is commented or not. By convention if an outline is commented, all
                subordinate outlines are considered to also be commented. If it's
                not present, the value is false.
              type: string
              enum: ['true', 'false']
              default: 'false'
              xml:
                attribute: true
              x-enum-varnames: ['Commented', 'NotCommented']
              x-go-type-name: CommentState
              x-oapi-codegen-extra-tags:
                xml: 'isComment,omitempty,attr'
            isBreakpoint:
              description: >
                is a string, either "true" or "false", indicating whether a
                breakpoint is set on this outline. This attribute is mainly
                necessary for outlines used to edit scripts. If it's not present,
                the value is false.
              type: string
              enum: ['true', 'false']
              default: 'false'
              xml:
                attribute: true
              x-enum-varnames: ['Breakpoint', 'NoBreakpoint']
              x-go-type-name: BreakpointState
              x-oapi-codegen-extra-tags:
                xml: 'isBreakpoint,omitempty,attr'
            created:
              description: >
                is the date-time that the outline node was created.
              type: string
              xml:
                attribute: true
              x-oapi-codegen-extra-tags:
                xml: 'created,omitempty,attr'
            category:
              description: >
                is a string of comma-separated slash-delimited category strings, in
                the format defined by the RSS 2.0 category element. To represent a
                "tag," the category string should contain no slashes.
              type: string
              xml:
                attribute: true
              x-oapi-codegen-extra-tags:
                xml: 'category,omitempty,attr'
            outlines:
              description: >
                contains any nested outlines of this outline.
              type: array
              items:
                $ref: '#/components/schemas/Outline'
              x-oapi-codegen-extra-tags:
                xml: outline
      xml:
        name: outline
      x-oapi-codegen-extra-tags:
        xml: 'outline'
        validate: 'omitempty'
    RSSOutline:
      description: >
        is a possibly multiple-level list of subscriptions to feeds. Each
        sub-element of the body of the OPML document is a node of type rss or an
        outline element that contains nodes of type rss.
      type: object
      required:
        - xmlUrl
      properties:
        xmlUrl:
          description: >
            is the http address of the feed.
          type: string
          x-oapi-codegen-extra-tags:
            xml: 'xmlUrl,attr'
            validate: 'required,url'
          xml:
            attribute: true
          x-go-name: XMLURL
        htmlUrl:
          description: >
            is the top-level link element.
          type: string
          x-oapi-codegen-extra-tags:
            xml: 'htmlUrl,omitempty,attr'
            validate: 'omitempty,url'
          xml:
            attribute: true
          x-go-name: HTMLURL
        title:
          description: >
            contains the top-level title element from the feed.
          type: string
          x-oapi-codegen-extra-tags:
            xml: 'title,omitempty,attr'
          xml:
            attribute: true
        description:
          description: >
            is the top-level description element from the feed.
          type: string
          x-oapi-codegen-extra-tags:
            xml: 'description,omitempty,attr'
          xml:
            attribute: true
        language:
          description: >
            is the value of the top-level language element.
          type: string
          x-oapi-codegen-extra-tags:
            xml: 'language,omitempty,attr'
          xml:
            attribute: true
        version:
          description: >
            is the top-level description element from the feed.
          type: string
          enum: ['RSS2', 'RSS1', 'RSS', 'scriptingNews']
          x-oapi-codegen-extra-tags:
            xml: 'version,omitempty,attr'
            validate: 'omitempty,oneof=RSS2 RSS1 RSS scriptingNews'
          xml:
            attribute: true
