---
openapi: '3.0.3'
info:
  version: 1.0.0
  title: Common Elements
  description: >
    Common/shared elements across different syndication formats.
  contact:
    name: "Joshua Rich"
    email: joshua.rich@gmail.com
  license:
    identifier: MIT
components:
  schemas:
    Language:
      description: >
        is the primary language encapsulated in the element.
      type: string
      x-oapi-codegen-extra-tags:
        xml: 'language,omitempty'
        validate: 'omitempty,iso3166_1_alpha2|iso3166_1_alpha3|bcp47_language_tag'
    URL:
      description: >
        is a URL link.
      type: string
      x-go-name: URL
      x-oapi-codegen-extra-tags:
        xml: 'url'
        validate: 'omitempty,url'
