---
openapi: '3.1.0'
info:
  version: 1.0.0
  title: Common Types
  description: >
    Common/shared types across schemas.
  contact:
    name: 'Joshua Rich'
    email: joshua.rich@gmail.com
  license:
    identifier: MIT
components:
  schemas:
    ImageInfo:
      description: >
        is an abstraction of an Image across different types of specifications.
      type: object
      required:
        - url
      properties:
        title:
          description: >
            the description of the image
          type: string
        url:
          description: >
            is the URL to the image.
          type: string
          x-go-name: URL
          x-oapi-codegen-extra-tags:
            xml: ',chardata'
            validate: 'required,url'
      x-oapi-codegen-extra-tags:
        validate: 'omitempty'
