---
openapi: '3.0.3'
info:
  version: 1.0.0
  title: Common Types
  description: >
    Common/shared types across schemas.
  contact:
    name: "Joshua Rich"
    email: joshua.rich@gmail.com
  license:
    identifier: AGPL-3.0-or-later
components:
  schemas:
    RequiredValue:
      description: >
        is an element value that is required.
      type: string
      x-oapi-codegen-extra-tags:
        xml: ',chardata'
        validate: 'required'
    OptionalValue:
      description: >
        is an element value that is optional.
      type: string
      x-oapi-codegen-extra-tags:
        xml: ',chardata'
    Attributes:
      description: >
        are any attributes of the element.
      type: array
      items:
        x-go-type: xml.Attr
      x-oapi-codegen-extra-tags:
        xml: ',any,attr'
        json: 'attributes'
      x-go-type-skip-optional-pointer: true
    Extension:
      description: >
        represents an element that is not defined in the schema.
      type: object
      required:
        - XMLName
      properties:
        XMLName:
          description: >
            represents the XML namespace of an element.
          x-go-type: 'xml.Name'
          x-oapi-codegen-extra-tags:
            json: 'xml'
            validate: 'required'
        value:
          $ref: '#/components/schemas/OptionalValue'
        attributes:
          $ref: '#/components/schemas/Attributes'
        extensions:
          descriptions: >
            are any child extensions.
          type: array
          items:
            $ref: '#/components/schemas/Extension'
          x-oapi-codegen-extra-tags:
            json: 'extensions,omitempty'
            xml: ',any'
          x-go-type-skip-optional-pointer: true
    Extensions:
      description: >
        records any elements that are unknown extensions to the schema.
      type: array
      items:
        $ref: '#/components/schemas/Extension'
      x-oapi-codegen-extra-tags:
        json: 'extensions,omitempty'
        xml: ',any'
      x-go-type-skip-optional-pointer: true
    ImageInfo:
      description: >
        is an abstraction of an Image across different types of specifications.
      type: object
      required:
        - url
      properties:
        title:
          description: >
            the description of the image
          type: string
        url:
          description: >
            is the URL to the image.
          type: string
          x-go-name: URL
          x-oapi-codegen-extra-tags:
            xml: ',chardata'
            validate: 'required,url'
      x-oapi-codegen-extra-tags:
        validate: 'omitempty'
