# Copyright 2025 Joshua Rich <joshua.rich@gmail.com>.
# SPDX-License-Identifier: 	AGPL-3.0-or-later

openapi: '3.0.3'
info:
  version: 1.0.0
  title: Common Types
  description: >
    Common/shared types across schemas.
  license:
    name: AGPL-3.0-or-later
    url: https://spdx.org/licenses/AGPL-3.0-only.html
components:
  schemas:
    XMLName:
      description: >
        represents the XML namespace of an element.
      x-go-type: 'xml.Name'
      x-oapi-codegen-extra-tags:
        json: 'xml'
        validate: 'required'
    NameSpace:
      description: >
        maps namespace URL identifiers to a easy-to-use string type.
      type: string
      enum:
        - 'http://purl.org/dc/elements/1.1/'
        - 'http://search.yahoo.com/mrss/'
        - 'http://purl.org/rss/1.0/modules/syndication/'
        - 'http://purl.org/rss/1.0/modules/content/'
        - 'http://www.w3.org/2005/Atom'
      x-enum-varnames:
        - DublinCore
        - MediaRSS
        - Syndication
        - Content
        - Atom
    RequiredValue:
      description: >
        is an element value that is required.
      type: string
      x-oapi-codegen-extra-tags:
        xml: ',chardata'
        validate: 'required'
    OptionalValue:
      description: >
        is an element value that is optional.
      type: string
      x-oapi-codegen-extra-tags:
        xml: ',chardata'
    Attributes:
      description: >
        are any attributes of the element.
      type: array
      items:
        x-go-type: xml.Attr
      x-oapi-codegen-extra-tags:
        xml: ',any,attr'
        json: 'attributes'
      x-go-type-skip-optional-pointer: true
    Extension:
      description: >
        represents an element that is not defined in the schema.
      type: object
      required:
        - XMLName
      properties:
        XMLName:
          description: >
            represents the XML namespace of an element.
          x-go-type: 'xml.Name'
          x-oapi-codegen-extra-tags:
            json: 'xml'
            validate: 'required'
        value:
          $ref: '#/components/schemas/OptionalValue'
        attributes:
          $ref: '#/components/schemas/Attributes'
        extensions:
          descriptions: >
            are any child extensions.
          type: array
          items:
            $ref: '#/components/schemas/Extension'
          x-oapi-codegen-extra-tags:
            json: 'extensions,omitempty'
            xml: ',any'
          x-go-type-skip-optional-pointer: true
    Extensions:
      description: >
        records any elements that are unknown extensions to the schema.
      type: array
      items:
        $ref: '#/components/schemas/Extension'
      x-oapi-codegen-extra-tags:
        json: 'extensions,omitempty'
        xml: ',any'
      x-go-type-skip-optional-pointer: true
    CustomTypeBase:
      dscription: >
        is a base type used by custom types containing their common fields.
      type: object
      required:
        - value
      properties:
        value:
          $ref: '#/components/schemas/RequiredValue'
        attributes:
          $ref: '#/components/schemas/Attributes'
    ImageInfo:
      description: >
        is an abstraction of an Image across different types of specifications.
      type: object
      required:
        - url
      properties:
        title:
          description: >
            the description of the image
          type: string
        url:
          description: >
            is the URL to the image.
          type: string
          x-go-name: URL
          x-oapi-codegen-extra-tags:
            xml: ',chardata'
            validate: 'required,url'
      x-oapi-codegen-extra-tags:
        validate: 'omitempty'
    CharData:
      description: >
        represents character data of an element.
      type: object
      required:
        - XMLName
        - value
      properties:
        XMLName:
          $ref: '#/components/schemas/XMLName'
        value:
          x-go-type: 'xml.CharData'
      x-oapi-codegen-extra-tags:
        xml: ',chardata'
    StringData:
      description: >
        represents string data of an element.
      type: object
      required:
        - XMLName
        - value
      properties:
        XMLName:
          $ref: '#/components/schemas/XMLName'
        value:
          type: string
      x-oapi-codegen-extra-tags:
        xml: ',chardata'
