---
openapi: "3.1.0"
info:
  version: 1.0.0
  title: Common Types
  description: >
    Common/shared types across schemas.
  contact:
    name: "Joshua Rich"
    email: joshua.rich@gmail.com
  license:
    identifier: MIT
components:
  schemas:
    Source:
      description: >
        is the type of source the feed or object came from. This can be used with abstractions that generalize different
        feed types into a common format to preserve information on the original.
      type: string
      enum: ["HTML", "RSS", "Atom", "JSONFeed", "RDF", "Unknown"]
      x-oapi-codegen-extra-tags:
        validate: "oneof=HTML RSS Atom JSONFeed RDF Unknown"
    Image:
      description: represents a remote image.
      type: object
      required:
        - url
      properties:
        url:
          description: the URL to the image.
          type: string
          x-go-name: URL
          x-oapi-codegen-extra-tags:
            validate: "required,url"
        title:
          description: is a description of the image (for example, the alt tag associated with the image).
          type: string
    Link:
      description: >
        is an 'address', usually of a person. For example, an email, website or social media handle. An address has a
        type and a value and/or URI associated with it.
      type: object
      required:
        - type
        - value
      properties:
        type:
          description: >
            is the type of address. While there are some canonical values for the type, they are not conclusive and the
            type can be any value, including one of the canonical types. However, a canonical type should be used
            whenever appropriate.
          type: string
          enum: ["email", "website", "id"]
          x-oapi-codegen-extra-tags:
            validate: "required"
        value:
          description: >
            is the link value. It can be a URI, email or any string that acts as a unique identifier (i.e.,
            social media handle).
          type: string
          x-oapi-codegen-extra-tags:
            validate: "required|uri|email"
    Person:
      description: represents a person.
      type: object
      required:
        - name
      properties:
        name:
          description: is the person's name.
          type: string
          x-oapi-codegen-extra-tags:
            validate: "required"
        bio:
          description: is an optional short biography of the person.
          type: string
        links:
          description: are links associated with the person that provide more details about them.
          type: array
          items:
            $ref: "#/components/schemas/Link"
          x-go-type-skip-optional-pointer: true
          x-oapi-codegen-extra-tags:
            validate: "omitempty,dive,unique"
    GeoInfo:
      description: contains geographical information.
      type: object
      allOf:
        - $ref: "georss.yaml#/components/schemas/GeoRSSSimple"
