// Package georss provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package georss

// Altitude is the meters above the local reference ellipsoid.
type Altitude = float64

// Box is a bounding box as two coordinate pairs: the lower (southwest) corner, then the upper (northeast) corner (georss:box).
type Box struct {
	// Lower is a single WGS84 latitude/longitude pair, decimal degrees.
	Lower Coord `json:"lower"`

	// Upper is a single WGS84 latitude/longitude pair, decimal degrees.
	Upper Coord `json:"upper"`
}

// Circle a center point plus a radius in meters (georss:circle).
type Circle struct {
	// Center is a single WGS84 latitude/longitude pair, decimal degrees.
	Center Coord `json:"center"`

	// Radius is the radius in meters.
	Radius float64 `json:"radius"`
}

// Coord is a single WGS84 latitude/longitude pair, decimal degrees.
type Coord struct {
	// Lat is the latitude in decimal degress
	Lat Latitude `json:"lat" validate:"required,gte=-90,lte=90"`

	// Lon is the longitude in decimal degress
	Lon Longitude `json:"lon" validate:"required,gte=-180,lte=180"`
}

// GMLEnvelope is a bounding box that defines a rectangular region. This object is often used to define the extents of a map or define a rough area of interest. A GML box is called an Envelope. It consists of an <Envelope> element with a child <lowerCorner> element and a child <upperCorner> element.
type GMLEnvelope struct {
	// LowerCorner is a single WGS84 latitude/longitude pair, decimal degrees.
	LowerCorner Coord `json:"lowerCorner" xml:"http://www.opengis.net/gml lowerCorner"`

	// UpperCorner is a single WGS84 latitude/longitude pair, decimal degrees.
	UpperCorner Coord `json:"upperCorner" xml:"http://www.opengis.net/gml upperCorner"`
}

// GMLExterior defines model for GMLExterior.
type GMLExterior struct {
	// LinearRing consists of a GML <LineString> element with a child <posList> element. Within <posList> the coordinates of the points on the line are entered as pairs of latitude and longitude coordinate values, separated by spaces. There must be at least two pairs. No two pairs may be separated by more than 179 degrees in either latitude or longitude.
	LinearRing GMLLinearRing `json:"linearRing" xml:"http://www.opengis.net/gml LinearRing"`
}

// GMLLineString consists of a GML <LineString> element with a child <posList> element. Within <posList> the coordinates of the points on the line are entered as pairs of latitude and longitude coordinate values, separated by spaces. There must be at least two pairs. No two pairs may be separated by more than 179 degrees in either latitude or longitude.
type GMLLineString struct {
	// PosList is gml:posList's content -- a flat, space-separated run of coordinate pairs, used for both LineString and LinearRing.
	PosList GMLPosList `json:"posList" xml:"http://www.opengis.net/gml posList"`
}

// GMLLinearRing consists of a GML <LineString> element with a child <posList> element. Within <posList> the coordinates of the points on the line are entered as pairs of latitude and longitude coordinate values, separated by spaces. There must be at least two pairs. No two pairs may be separated by more than 179 degrees in either latitude or longitude.
type GMLLinearRing struct {
	// PosList is gml:posList's content -- a flat, space-separated run of coordinate pairs, used for both LineString and LinearRing.
	PosList GMLPosList `json:"posList" xml:"http://www.opengis.net/gml posList"`
}

// GMLPoint consists of a GML <Point> element with a child <pos> element. Within<pos> the latitude and longitude coordinate values are separated by a space.
type GMLPoint struct {
	// Pos is gml:pos's content such as a Point, a single coordinate pair.
	Pos GMLPos `json:"pos" xml:"http://www.opengis.net/gml pos"`
}

// GMLPolygon consists of a <Polygon> element with a child <exterior>, <LinearRing> and <posList> elements. There must be at least four coordinate pairs with the last being identical to the first. (A boundary has a minimum of three actual points.) No two pairs may be separated by more than 179 degrees in either latitude or longitude.
type GMLPolygon struct {
	Exterior GMLExterior `json:"exterior" xml:"http://www.opengis.net/gml exterior"`
}

// GMLPos is gml:pos's content such as a Point, a single coordinate pair.
type GMLPos = Coord

// GMLPosList is gml:posList's content -- a flat, space-separated run of coordinate pairs, used for both LineString and LinearRing.
type GMLPosList = Line

// GeoRSSSimple is the full set of GeoRSS Simple elements (including the GML-profile georss:where as an alternative to the Simple geometries), bundled once for embedding.
type GeoRSSSimple struct {
	// Box is a bounding box as two coordinate pairs: the lower (southwest) corner, then the upper (northeast) corner (georss:box).
	Box *Box `json:"box,omitempty" xml:"http://www.georss.org/georss box"`

	// Circle a center point plus a radius in meters (georss:circle).
	Circle *Circle `json:"circle,omitempty" xml:"http://www.georss.org/georss circle"`

	// Elev contains “common” GPS elevation readings, i.e. height in meters referenced to the WGS84 ellipsoid. This is a reading that should be easy to get from any GPS device.
	Elev           *float64 `json:"elev,omitempty" xml:"http://www.georss.org/georss elev"`
	FeatureName    *string  `json:"featureName,omitempty" xml:"http://www.georss.org/georss featurename,omitempty"`
	FeatureTypeTag *string  `json:"featureTypeTag,omitempty" xml:"http://www.georss.org/georss featuretypetag,omitempty"`

	// Floor contains the floor number of a building. In some countries the numbering is different than in other countries, but since we’ll know the location of the building, it should be fairly unambiguous. The definition of “floor” as used in GeoRSS is consistent with the IETF[3] and NENA definitions as required for the Next Generation 911 system in the US.
	Floor *int `json:"floor,omitempty" xml:"http://www.georss.org/georss floor"`

	// Line is an ordered sequence of two or more coordinate pairs (a LineString, georss:line).
	Line Line `json:"line,omitempty" xml:"http://www.georss.org/georss line"`

	// Point a single coordinate pair (georss:point).
	Point *Point `json:"point,omitempty" xml:"http://www.georss.org/georss point"`

	// Polygon a closed linear ring -- four or more coordinate pairs, with the first and last identical.
	Polygon Polygon `json:"polygon,omitempty" xml:"http://www.georss.org/georss polygon"`

	// Radius indicates the size in meters of a radius or buffer around the geometry object, for example, radius of circular area around a point geometry.
	Radius          *float64 `json:"radius,omitempty" xml:"http://www.georss.org/georss radius"`
	RelationshipTag *string  `json:"relationshipTag,omitempty" xml:"http://www.georss.org/georss relationshiptag,omitempty"`

	// Where wraps exactly one of the four GML geometries (georss:where).
	Where *Where `json:"where,omitempty" xml:"http://www.georss.org/georss where"`
}

// Latitude is the latitude in decimal degress
type Latitude = float64

// Line is an ordered sequence of two or more coordinate pairs (a LineString, georss:line).
type Line []Coord

// Longitude is the longitude in decimal degress
type Longitude = float64

// Point a single coordinate pair (georss:point).
type Point = Coord

// Polygon a closed linear ring -- four or more coordinate pairs, with the first and last identical.
type Polygon []Coord

// Where wraps exactly one of the four GML geometries (georss:where).
type Where struct {
	// Envelope is a bounding box that defines a rectangular region. This object is often used to define the extents of a map or define a rough area of interest. A GML box is called an Envelope. It consists of an <Envelope> element with a child <lowerCorner> element and a child <upperCorner> element.
	Envelope *GMLEnvelope `json:"envelope,omitempty" xml:"http://www.opengis.net/gml Envelope"`

	// LineString consists of a GML <LineString> element with a child <posList> element. Within <posList> the coordinates of the points on the line are entered as pairs of latitude and longitude coordinate values, separated by spaces. There must be at least two pairs. No two pairs may be separated by more than 179 degrees in either latitude or longitude.
	LineString *GMLLineString `json:"lineString,omitempty" xml:"http://www.opengis.net/gml LineString"`

	// Point consists of a GML <Point> element with a child <pos> element. Within<pos> the latitude and longitude coordinate values are separated by a space.
	Point *GMLPoint `json:"point,omitempty" xml:"http://www.opengis.net/gml Point"`

	// Polygon consists of a <Polygon> element with a child <exterior>, <LinearRing> and <posList> elements. There must be at least four coordinate pairs with the last being identical to the first. (A boundary has a minimum of three actual points.) No two pairs may be separated by more than 179 degrees in either latitude or longitude.
	Polygon *GMLPolygon `json:"polygon,omitempty" xml:"http://www.opengis.net/gml Polygon"`
}
