// Package atom provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package atom

import (
	"encoding/xml"
	"time"

	externalRef0 "github.com/immanent-tech/go-syndication/extensions"
	externalRef1 "github.com/immanent-tech/go-syndication/extensions/basicgeo"
	externalRef2 "github.com/immanent-tech/go-syndication/extensions/dc"
	externalRef3 "github.com/immanent-tech/go-syndication/extensions/georss"
	externalRef4 "github.com/immanent-tech/go-syndication/extensions/media"
	externalRef5 "github.com/immanent-tech/go-syndication/extensions/source"
)

// Defines values for ContentType.
const (
	ContentTypeHtml  ContentType = "html"
	ContentTypeText  ContentType = "text"
	ContentTypeXhtml ContentType = "xhtml"
)

// Valid indicates whether the value is a known member of the ContentType enum.
func (e ContentType) Valid() bool {
	switch e {
	case ContentTypeHtml:
		return true
	case ContentTypeText:
		return true
	case ContentTypeXhtml:
		return true
	default:
		return false
	}
}

// Defines values for LinkRel.
const (
	LinkRelAlternate                     LinkRel = "alternate"
	LinkRelEdit                          LinkRel = "edit"
	LinkRelEnclosure                     LinkRel = "enclosure"
	LinkRelHttpschemasGoogleComg2005Feed LinkRel = "http://schemas.google.com/g/2005#feed"
	LinkRelHub                           LinkRel = "hub"
	LinkRelNext                          LinkRel = "next"
	LinkRelRelated                       LinkRel = "related"
	LinkRelSelf                          LinkRel = "self"
	LinkRelStandout                      LinkRel = "standout"
	LinkRelVia                           LinkRel = "via"
)

// Valid indicates whether the value is a known member of the LinkRel enum.
func (e LinkRel) Valid() bool {
	switch e {
	case LinkRelAlternate:
		return true
	case LinkRelEdit:
		return true
	case LinkRelEnclosure:
		return true
	case LinkRelHttpschemasGoogleComg2005Feed:
		return true
	case LinkRelHub:
		return true
	case LinkRelNext:
		return true
	case LinkRelRelated:
		return true
	case LinkRelSelf:
		return true
	case LinkRelStandout:
		return true
	case LinkRelVia:
		return true
	default:
		return false
	}
}

// Defines values for TextConstructType.
const (
	TextConstructTypeHtml  TextConstructType = "html"
	TextConstructTypeText  TextConstructType = "text"
	TextConstructTypeXhtml TextConstructType = "xhtml"
)

// Valid indicates whether the value is a known member of the TextConstructType enum.
func (e TextConstructType) Valid() bool {
	switch e {
	case TextConstructTypeHtml:
		return true
	case TextConstructTypeText:
		return true
	case TextConstructTypeXhtml:
		return true
	default:
		return false
	}
}

// Authors a list of persons who maintain authorship of the feed.
type Authors = []PersonConstruct

// Categories a list of categories associated with the feed.
type Categories = []Category

// Category is an element that conveys information about a category associated with an entry or feed.
type Category struct {
	// Base establishes the base URI (or IRI) for resolving any relative references found within the effective scope of the xml:base attribute.
	Base *string `json:"base,omitempty" validate:"omitempty" xml:"xml:base,attr,omitempty"`

	// Lang indicates the natural language for the element and its descendents.
	Lang *string `json:"lang,omitempty" validate:"omitempty,iso3166_1_alpha2|iso3166_1_alpha3|bcp47_language_tag" xml:"xml:lang,attr,omitempty"`

	// Attributes are any additional attributes of the element.
	Attributes []xml.Attr `json:"attributes" xml:",any,attr"`

	// Extensions represents any additional, undefined content for this element.
	Extensions []externalRef0.Extension `json:"extensions,omitempty" xml:",any"`

	// Label provides a human-readable label for display in end-user applications.
	Label *xml.Attr `json:"label,omitempty" xml:"label,attr,omitempty"`

	// Scheme is an IRI that identifies a categorization scheme.
	Scheme *xml.Attr `json:"scheme,omitempty" xml:"scheme,attr,omitempty"`

	// Term is a string that identifies the category to which the entry or feed belongs.
	Term xml.Attr `json:"term" validate:"required" xml:"term,attr"`
}

// CommonAttributes are common attributes across Atom elements.
type CommonAttributes struct {
	// Base establishes the base URI (or IRI) for resolving any relative references found within the effective scope of the xml:base attribute.
	Base *string `json:"base,omitempty" validate:"omitempty" xml:"xml:base,attr,omitempty"`

	// Lang indicates the natural language for the element and its descendents.
	Lang *string `json:"lang,omitempty" validate:"omitempty,iso3166_1_alpha2|iso3166_1_alpha3|bcp47_language_tag" xml:"xml:lang,attr,omitempty"`

	// Attributes are any additional attributes of the element.
	Attributes []xml.Attr `json:"attributes" xml:",any,attr"`
}

// Content either contains or links to the content of the entry.
type Content struct {
	// Base establishes the base URI (or IRI) for resolving any relative references found within the effective scope of the xml:base attribute.
	Base *string `json:"base,omitempty" validate:"omitempty" xml:"xml:base,attr,omitempty"`

	// Base64 contains the value when any other MIME type: out-of-band binary content.
	Base64 []byte `json:"Base64,omitempty"`

	// Lang indicates the natural language for the element and its descendents.
	Lang *string `json:"lang,omitempty" validate:"omitempty,iso3166_1_alpha2|iso3166_1_alpha3|bcp47_language_tag" xml:"xml:lang,attr,omitempty"`

	// XHTML contains the value when Type == "xhtml": inner markup of the <div>.
	XHTML *string `json:"XHTML,omitempty"`

	// XML contains the value when Type ends in "+xml" or "/xml" (and isn't "text/..."): embedded XML, raw.
	XML *string `json:"XML,omitempty"`

	// Attributes are any additional attributes of the element.
	Attributes []xml.Attr `json:"attributes" xml:",any,attr"`

	// Source is an attribute that links to the source content.
	Source *string `json:"src,omitempty" validate:"omitempty,required_without=Value,uri" xml:"src,attr,omitempty"`

	// Text contains the value when Type is "text"/"html", or a "text/*" MIME type.
	Text *string `json:"text,omitempty"`

	// Type represents what the content of the element is.
	Type *ContentType `json:"type,omitempty" validate:"omitnil,oneof=text html xhtml|mimetype_string" xml:"type,attr,omitempty"`
}

// ContentType represents what the content of the element is.
type ContentType string

// Contributors a list of persons who contributed to the feed.
type Contributors = []PersonConstruct

// DateConstruct is an element whose content MUST conform to the "date-time" production in [RFC3339].
type DateConstruct struct {
	// Base establishes the base URI (or IRI) for resolving any relative references found within the effective scope of the xml:base attribute.
	Base *string `json:"base,omitempty" validate:"omitempty" xml:"xml:base,attr,omitempty"`

	// Lang indicates the natural language for the element and its descendents.
	Lang *string `json:"lang,omitempty" validate:"omitempty,iso3166_1_alpha2|iso3166_1_alpha3|bcp47_language_tag" xml:"xml:lang,attr,omitempty"`

	// Attributes are any additional attributes of the element.
	Attributes []xml.Attr `json:"attributes" xml:",any,attr"`

	// Value is the value of the date construct.
	Value time.Time `json:"value"`
}

// Entry represents an individual entry, acting as a container for metadata and data associated with the entry.
type Entry struct {
	// Base establishes the base URI (or IRI) for resolving any relative references found within the effective scope of the xml:base attribute.
	Base *string `json:"base,omitempty" validate:"omitempty" xml:"xml:base,attr,omitempty"`

	// Extensions records any elements that are unknown extensions to the schema.
	Extensions []externalRef0.Extension `json:"extensions,omitempty" xml:",any"`

	// ID is an element that conveys a permanent, universally unique identifier for an entry or feed.
	ID ID `json:"id" validate:"required" xml:"http://www.w3.org/2005/Atom id"`

	// Lang indicates the natural language for the element and its descendents.
	Lang *string `json:"lang,omitempty" validate:"omitempty,iso3166_1_alpha2|iso3166_1_alpha3|bcp47_language_tag" xml:"xml:lang,attr,omitempty"`

	// MediaBackLinks allows inclusion of all the URLs pointing to a media object.
	MediaBackLinks externalRef4.MediaBacklinks `json:"media_backlinks,omitempty" xml:"http://search.yahoo.com/mrss/ backLink,omitempty"`

	// MediaCategory allows a taxonomy to be set that gives an indication of the type of media content, and its particular contents.
	MediaCategory *externalRef4.MediaCategory `json:"media_category" xml:"http://search.yahoo.com/mrss/ category,omitempty"`

	// MediaComments is a list of comments the media object has received.
	MediaComments externalRef4.MediaComments `json:"media_comments"`

	// MediaCommunity stands for the community related content. This allows inclusion of the user perception about a media object in the form of view count, ratings and tags.
	MediaCommunity *externalRef4.MediaCommunity `json:"media_community" xml:"http://search.yahoo.com/mrss/ community,omitempty"`

	// MediaCopyright is copyright information for the media object.
	MediaCopyright *externalRef4.MediaCopyright `json:"media_copyright" xml:"media copyright,omitempty"`

	// MediaCredits a list of credits for the object.
	MediaCredits externalRef4.MediaCredits `json:"media_credits" xml:"credit,omitempty"`

	// MediaDescription is a short description describing the media object typically a sentence in length.
	MediaDescription *externalRef4.MediaDescription `json:"media_description" xml:"http://search.yahoo.com/mrss/ description,omitempty"`

	// MediaEmbed allows inclusion of player-specific information in the form of key-value (Param) pairs.
	MediaEmbed *externalRef4.MediaEmbed `json:"media_embed" xml:"http://search.yahoo.com/mrss/ embed,omitempty"`

	// MediaGroup allows grouping of <media:content> elements that are effectively the same content, yet different representations. For instance: the same song recorded in both the WAV and MP3 format.
	MediaGroup *externalRef4.MediaGroup `json:"media_group,omitempty" xml:"http://search.yahoo.com/mrss/ group,omitempty"`

	// MediaHashes a list of hashes for the object.
	MediaHashes externalRef4.MediaHashes `json:"media_hashes" xml:"hash,omitempty"`

	// MediaKeywords are highly relevant keywords describing the media object with typically a maximum of 10 words. The keywords and phrases should be comma-delimited.
	MediaKeywords *externalRef4.MediaKeywords `json:"media_keywords" xml:"http://search.yahoo.com/mrss/ keywords,omitempty"`

	// MediaLicense link to specify the machine-readable license associated with the content.
	MediaLicense *externalRef4.MediaLicense `json:"media_license" xml:"http://search.yahoo.com/mrss/ license,omitempty"`

	// MediaPeerLink contains P2P link.
	MediaPeerLink *externalRef4.MediaPeerLink `json:"media_peerlink" xml:"http://search.yahoo.com/mrss/ peerLink,omitempty"`

	// MediaPlayer allows the media object to be accessed through a web browser media player console.
	MediaPlayer *externalRef4.MediaPlayer `json:"media_player" xml:"http://search.yahoo.com/mrss/ player,omitempty"`

	// MediaPrice includes pricing information about a media object. If this tag is not present, the media object is supposed to be free.
	MediaPrice *externalRef4.MediaPrice `json:"media_price" xml:"http://search.yahoo.com/mrss/ price,omitempty"`

	// MediaRating allows the permissible audience to be declared. If this element is not included, it assumes that no restrictions are necessary.
	MediaRating *externalRef4.MediaRating `json:"media_rating" xml:"http://search.yahoo.com/mrss/ rating,omitempty"`

	// MediaResponses allows inclusion of a list of all media responses a media object has received.
	MediaResponses externalRef4.MediaResponses `json:"media_responses" xml:"http://search.yahoo.com/mrss/ response,omitempty"`

	// MediaRestriction allows restrictions to be placed on the aggregator rendering the media in the feed.
	MediaRestriction *externalRef4.MediaRestriction `json:"media_restriction" validate:"omitempty,validateFn" xml:"http://search.yahoo.com/mrss/ restriction,omitempty"`

	// MediaRights specifies the rights information of a media object.
	MediaRights *externalRef4.MediaRights `json:"media_rights" xml:"http://search.yahoo.com/mrss/ rights,omitempty"`

	// MediaScenes specifies various scenes within a media object.
	MediaScenes externalRef4.MediaScenes `json:"media_scenes" xml:"http://search.yahoo.com/mrss/ scene,omitempty"`

	// MediaStatus specifies the status of a media object -- whether it's still active or it has been blocked/deleted.
	MediaStatus *externalRef4.MediaStatus `json:"media_status" xml:"http://search.yahoo.com/mrss/ status,omitempty"`

	// MediaSubTitle contains subtitle/CC link.
	MediaSubTitle *externalRef4.MediaSubTitle `json:"media_subtitle,omitempty" xml:"http://search.yahoo.com/mrss/ subTitle,omitempty"`

	// MediaTexts a list of texts for the object.
	MediaTexts externalRef4.MediaTexts `json:"media_texts" xml:"text,omitempty"`

	// MediaThumbnails a list of thumbnails for the object.
	MediaThumbnails externalRef4.MediaThumbnails `json:"media_thumbnails" xml:"thumbnail,omitempty"`

	// MediaTitle is the title of the particular media object.
	MediaTitle *externalRef4.MediaTitle `json:"media_title" xml:"http://search.yahoo.com/mrss/ title,omitempty"`

	// SourceComments are links to comments for this item.
	SourceComments *externalRef5.Comments `json:"comments,omitempty" xml:"https://source.scripting.com/ comments,omitempty"`

	// SourceInReplyTo identifies the item that this item is in reply to.
	SourceInReplyTo *externalRef5.InReplyTo `json:"inReplyTo,omitempty" xml:"https://source.scripting.com/ inReplyTo,omitempty"`

	// SourceLinkFill is the unshortened version of <link>.
	SourceLinkFill *externalRef5.LinkFull `json:"linkFull,omitempty" xml:"https://source.scripting.com/ linkFull,omitempty"`

	// SourceMarkdown is the source of the item-level description sub-element using Markdown to encode styling and links. If your feed presenter can understand Markdown, you should use this as the source for the display of the item.
	SourceMarkdown *externalRef5.Markdown `json:"markdown,omitempty" xml:"https://source.scripting.com/ markdown,omitempty"`
	SourceOutline  *externalRef5.Outline  `json:"outline,omitempty" xml:"https://source.scripting.com/ outline,omitempty"`

	// Alt is the meters above the local reference ellipsoid.
	Alt *externalRef1.Altitude `json:"alt,omitempty" xml:"http://www.w3.org/2003/01/geo/wgs84_pos# alt,omitempty"`

	// Attributes are any additional attributes of the element.
	Attributes []xml.Attr `json:"attributes" xml:",any,attr"`

	// Authors a list of persons who maintain authorship of the feed.
	Authors Authors `json:"authors,omitempty" validate:"gt=0,dive,validateFn" xml:"http://www.w3.org/2005/Atom author,omitempty"`

	// Box is a bounding box as two coordinate pairs: the lower (southwest) corner, then the upper (northeast) corner (georss:box).
	Box *externalRef3.Box `json:"box,omitempty" xml:"http://www.georss.org/georss box"`

	// Categories a list of categories associated with the feed.
	Categories Categories `json:"categories,omitempty" validate:"dive,validateFn" xml:"category,omitempty"`

	// Circle a center point plus a radius in meters (georss:circle).
	Circle *externalRef3.Circle `json:"circle,omitempty" xml:"http://www.georss.org/georss circle"`

	// Content either contains or links to the content of the entry.
	Content *Content `json:"content,omitempty" validate:"omitempty,validateFn" xml:"http://www.w3.org/2005/Atom content,omitempty"`

	// Contributors a list of persons who contributed to the feed.
	Contributors Contributors `json:"contributors,omitempty" validate:"omitempty,gt=0,dive,validateFn" xml:"http://www.w3.org/2005/Atom contributor,omitempty"`

	// DcContributor is an entity responsible for making contributions to the resource.
	// The guidelines for using names of persons or organizations as creators apply to contributors.
	DcContributor externalRef2.Contributor `json:"dc_contributor,omitempty" xml:"http://purl.org/dc/elements/1.1/ contributor,omitempty"`

	// DcCoverage is the spatial or temporal topic of the resource, spatial applicability of the resource, or jurisdiction under which the resource is relevant.
	// Spatial topic and spatial applicability may be a named place or a location specified by its geographic coordinates. Temporal topic may be a named period, date, or date range. A jurisdiction may be a named administrative entity or a geographic place to which the resource applies. Recommended practice is to use a controlled vocabulary such as the Getty Thesaurus of Geographic Names [TGN]. Where appropriate, named places or time periods may be used in preference to numeric identifiers such as sets of coordinates or date ranges. Because coverage is so broadly defined, it is preferable to use the more specific subproperties Temporal Coverage and Spatial Coverage.
	DcCoverage externalRef2.Coverage `json:"dc_coverage,omitempty" xml:"http://purl.org/dc/elements/1.1/ coverage,omitempty"`

	// DcCreator is an entity responsible for making the resource.
	// Recommended practice is to identify the creator with a URI. If this is not possible or feasible, a literal value that identifies the creator may be provided.
	DcCreator externalRef2.Creator `json:"dc_creator,omitempty" xml:"http://purl.org/dc/elements/1.1/ creator,omitempty"`

	// DcDate is a point or period of time associated with an event in the lifecycle of the resource.
	// Date may be used to express temporal information at any level of granularity. Recommended practice is to express the date, date/time, or period of time according to ISO 8601-1 [ISO 8601-1] or a published profile of the ISO standard, such as the W3C Note on Date and Time Formats [W3CDTF] or the Extended Date/Time Format Specification [EDTF]. If the full date is unknown, month and year (YYYY-MM) or just year (YYYY) may be used. Date ranges may be specified using ISO 8601 period of time specification in which start and end dates are separated by a '/' (slash) character. Either the start or end date may be missing.
	DcDate externalRef2.Date `json:"dc_date,omitempty" xml:"http://purl.org/dc/elements/1.1/ date,omitempty"`

	// DcDescription is an account of the resource.
	// Description may include but is not limited to: an abstract, a table of contents, a graphical representation, or a free-text account of the resource.
	DcDescription externalRef2.Description `json:"dc_description,omitempty" xml:"http://purl.org/dc/elements/1.1/ description,omitempty"`

	// DcFormat is the file format, physical medium, or dimensions of the resource.
	// Recommended practice is to use a controlled vocabulary where available. For example, for file formats one could use the list of Internet Media Types [MIME]. Examples of dimensions include size and duration.
	DcFormat externalRef2.Format `json:"dc_format,omitempty" xml:"http://purl.org/dc/elements/1.1/ format,omitempty"`

	// DcIdentifier is an unambiguous reference to the resource within a given context.
	// Recommended practice is to identify the resource by means of a string conforming to an identification system. Examples include International Standard Book Number (ISBN), Digital Object Identifier (DOI), and Uniform Resource Name (URN). Persistent identifiers should be provided as HTTP URIs.
	DcIdentifier externalRef2.Identifier `json:"dc_identifier,omitempty" xml:"http://purl.org/dc/elements/1.1/ identifier,omitempty"`

	// DcLanguage is a language of the resource.
	// Recommended practice is to use either a non-literal value representing a language from a controlled vocabulary such as ISO 639-2 or ISO 639-3, or a literal value consisting of an IETF Best Current Practice 47 [IETF-BCP47] language tag.
	DcLanguage externalRef2.Language `json:"dc_language,omitempty" xml:"http://purl.org/dc/elements/1.1/ language,omitempty"`

	// DcPublisher is an entity responsible for making the resource available.
	DcPublisher externalRef2.Publisher `json:"dc_publisher,omitempty" xml:"http://purl.org/dc/elements/1.1/ publisher,omitempty"`

	// DcRelation is a related resource.
	// Recommended practice is to identify the related resource by means of a URI. If this is not possible or feasible, a string conforming to a formal identification system may be provided.
	DcRelation externalRef2.Relation `json:"dc_relation,omitempty" xml:"http://purl.org/dc/elements/1.1/ relation,omitempty"`

	// DcRights is information about rights held in and over the resource.
	// Typically, rights information includes a statement about various property rights associated with the resource, including intellectual property rights. Recommended practice is to refer to a rights statement with a URI. If this is not possible or feasible, a literal value (name, label, or short text) may be provided.
	DcRights externalRef2.Rights `json:"dc_rights,omitempty" xml:"http://purl.org/dc/elements/1.1/ rights,omitempty"`

	// DcSource is a related resource from which the described resource is derived.
	// This property is intended to be used with non-literal values. The described resource may be derived from the related resource in whole or in part. Best practice is to identify the related resource by means of a URI or a string conforming to a formal identification system.
	DcSource externalRef2.Source `json:"dc_source,omitempty" xml:"http://purl.org/dc/elements/1.1/ source,omitempty"`

	// DcSubject is a topic of the resource.
	// Recommended practice is to refer to the subject with a URI. If this is not possible or feasible, a literal value that identifies the subject may be provided. Both should preferably refer to a subject in a controlled vocabulary.
	DcSubject externalRef2.Subject `json:"dc_subject,omitempty" xml:"http://purl.org/dc/elements/1.1/ subject,omitempty"`

	// DcTitle is a name given to the resource.
	DcTitle externalRef2.Title `json:"dc_title,omitempty" xml:"http://purl.org/dc/elements/1.1/ title,omitempty"`

	// DcType is the nature or genre of the resource.
	// Recommended practice is to use a controlled vocabulary such as the DCMI Type Vocabulary [DCMI-TYPE]. To describe the file format, physical medium, or dimensions of the resource, use the property Format.
	DcType externalRef2.Type `json:"dc_type,omitempty" xml:"http://purl.org/dc/elements/1.1/ type,omitempty"`

	// Elev contains “common” GPS elevation readings, i.e. height in meters referenced to the WGS84 ellipsoid. This is a reading that should be easy to get from any GPS device.
	Elev           *float64 `json:"elev,omitempty" xml:"http://www.georss.org/georss elev"`
	FeatureName    *string  `json:"featureName,omitempty" xml:"http://www.georss.org/georss featurename,omitempty"`
	FeatureTypeTag *string  `json:"featureTypeTag,omitempty" xml:"http://www.georss.org/georss featuretypetag,omitempty"`

	// Floor contains the floor number of a building. In some countries the numbering is different than in other countries, but since we’ll know the location of the building, it should be fairly unambiguous. The definition of “floor” as used in GeoRSS is consistent with the IETF[3] and NENA definitions as required for the Next Generation 911 system in the US.
	Floor *int `json:"floor,omitempty" xml:"http://www.georss.org/georss floor"`

	// Lat is the latitude in decimal degress
	Lat externalRef1.Latitude `json:"lat" validate:"required,gte=-90,lte=90" xml:"http://www.w3.org/2003/01/geo/wgs84_pos# lat"`

	// Line is an ordered sequence of two or more coordinate pairs (a LineString, georss:line).
	Line externalRef3.Line `json:"line,omitempty" xml:"http://www.georss.org/georss line"`

	// Links a list of links associated with the feed.
	Links Links `json:"links,omitempty" validate:"dive,validateFn" xml:"link,omitempty"`

	// Lon is the longitude in decimal degress
	Lon externalRef1.Longitude `json:"lon" validate:"required,gte=-180,lte=180" xml:"http://www.w3.org/2003/01/geo/wgs84_pos# long"`

	// Point a single coordinate pair (georss:point).
	Point *externalRef3.Point `json:"point,omitempty" xml:"http://www.georss.org/georss point"`

	// Polygon a closed linear ring -- four or more coordinate pairs, with the first and last identical.
	Polygon externalRef3.Polygon `json:"polygon,omitempty" xml:"http://www.georss.org/georss polygon"`

	// Published is an element of type Date construct indicating an instant in time associated with an event early in the life cycle of the entry.
	Published *Published `json:"published,omitempty" xml:"http://www.w3.org/2005/Atom published,omitempty"`

	// Radius indicates the size in meters of a radius or buffer around the geometry object, for example, radius of circular area around a point geometry.
	Radius          *float64 `json:"radius,omitempty" xml:"http://www.georss.org/georss radius"`
	RelationshipTag *string  `json:"relationshipTag,omitempty" xml:"http://www.georss.org/georss relationshiptag,omitempty"`

	// Rights is an element of type Text construct that conveys information about rights held in and over an entry or feed.
	Rights *Rights `json:"rights,omitempty" xml:"http://www.w3.org/2005/Atom rights,omitempty"`

	// Source contains the metadata from the source feed for the entry.
	Source *Source `json:"source,omitempty" validate:"omitempty"`

	// Summary is an element of type Text construct that conveys a short summary, abstract, or excerpt of an entry.
	Summary *Summary `json:"summary,omitempty" xml:"http://www.w3.org/2005/Atom summary,omitempty"`

	// Title is an element of type Text construct that conveys a human-readable title for an entry or feed.
	Title Title `json:"title" validate:"required" xml:"http://www.w3.org/2005/Atom title"`

	// Updated is an element of type Date construct indicating the most recent instant in time when an entry or feed was modified in a way the publisher considers significant.
	Updated Updated `json:"updated" validate:"required" xml:"http://www.w3.org/2005/Atom updated"`

	// Where wraps exactly one of the four GML geometries (georss:where).
	Where *externalRef3.Where `json:"where,omitempty" xml:"http://www.georss.org/georss where"`
}

// Feed is the document (i.e., top-level) element of an Atom Feed Document, acting as a container for metadata and data associated with the feed.
type Feed struct {
	// Base establishes the base URI (or IRI) for resolving any relative references found within the effective scope of the xml:base attribute.
	Base             *string `json:"base,omitempty" validate:"omitempty" xml:"xml:base,attr,omitempty"`
	DefaultNamespace *string `json:"DefaultNamespace,omitempty" xml:"-"`

	// Extensions represents any additional, undefined content for this element.
	Extensions []externalRef0.Extension `json:"extensions,omitempty" xml:",any"`

	// ID is an element that conveys a permanent, universally unique identifier for an entry or feed.
	ID ID `json:"id" validate:"required" xml:"http://www.w3.org/2005/Atom id"`

	// Lang indicates the natural language for the element and its descendents.
	Lang *string `json:"lang,omitempty" validate:"omitempty,iso3166_1_alpha2|iso3166_1_alpha3|bcp47_language_tag" xml:"xml:lang,attr,omitempty"`

	// MediaBackLinks allows inclusion of all the URLs pointing to a media object.
	MediaBackLinks externalRef4.MediaBacklinks `json:"media_backlinks,omitempty" xml:"http://search.yahoo.com/mrss/ backLink,omitempty"`

	// MediaCategory allows a taxonomy to be set that gives an indication of the type of media content, and its particular contents.
	MediaCategory *externalRef4.MediaCategory `json:"media_category" xml:"http://search.yahoo.com/mrss/ category,omitempty"`

	// MediaComments is a list of comments the media object has received.
	MediaComments externalRef4.MediaComments `json:"media_comments"`

	// MediaCommunity stands for the community related content. This allows inclusion of the user perception about a media object in the form of view count, ratings and tags.
	MediaCommunity *externalRef4.MediaCommunity `json:"media_community" xml:"http://search.yahoo.com/mrss/ community,omitempty"`

	// MediaCopyright is copyright information for the media object.
	MediaCopyright *externalRef4.MediaCopyright `json:"media_copyright" xml:"media copyright,omitempty"`

	// MediaCredits a list of credits for the object.
	MediaCredits externalRef4.MediaCredits `json:"media_credits" xml:"credit,omitempty"`

	// MediaDescription is a short description describing the media object typically a sentence in length.
	MediaDescription *externalRef4.MediaDescription `json:"media_description" xml:"http://search.yahoo.com/mrss/ description,omitempty"`

	// MediaEmbed allows inclusion of player-specific information in the form of key-value (Param) pairs.
	MediaEmbed *externalRef4.MediaEmbed `json:"media_embed" xml:"http://search.yahoo.com/mrss/ embed,omitempty"`

	// MediaHashes a list of hashes for the object.
	MediaHashes externalRef4.MediaHashes `json:"media_hashes" xml:"hash,omitempty"`

	// MediaKeywords are highly relevant keywords describing the media object with typically a maximum of 10 words. The keywords and phrases should be comma-delimited.
	MediaKeywords *externalRef4.MediaKeywords `json:"media_keywords" xml:"http://search.yahoo.com/mrss/ keywords,omitempty"`

	// MediaLicense link to specify the machine-readable license associated with the content.
	MediaLicense *externalRef4.MediaLicense `json:"media_license" xml:"http://search.yahoo.com/mrss/ license,omitempty"`

	// MediaPeerLink contains P2P link.
	MediaPeerLink *externalRef4.MediaPeerLink `json:"media_peerlink" xml:"http://search.yahoo.com/mrss/ peerLink,omitempty"`

	// MediaPlayer allows the media object to be accessed through a web browser media player console.
	MediaPlayer *externalRef4.MediaPlayer `json:"media_player" xml:"http://search.yahoo.com/mrss/ player,omitempty"`

	// MediaPrice includes pricing information about a media object. If this tag is not present, the media object is supposed to be free.
	MediaPrice *externalRef4.MediaPrice `json:"media_price" xml:"http://search.yahoo.com/mrss/ price,omitempty"`

	// MediaRating allows the permissible audience to be declared. If this element is not included, it assumes that no restrictions are necessary.
	MediaRating *externalRef4.MediaRating `json:"media_rating" xml:"http://search.yahoo.com/mrss/ rating,omitempty"`

	// MediaResponses allows inclusion of a list of all media responses a media object has received.
	MediaResponses externalRef4.MediaResponses `json:"media_responses" xml:"http://search.yahoo.com/mrss/ response,omitempty"`

	// MediaRestriction allows restrictions to be placed on the aggregator rendering the media in the feed.
	MediaRestriction *externalRef4.MediaRestriction `json:"media_restriction" validate:"omitempty,validateFn" xml:"http://search.yahoo.com/mrss/ restriction,omitempty"`

	// MediaRights specifies the rights information of a media object.
	MediaRights *externalRef4.MediaRights `json:"media_rights" xml:"http://search.yahoo.com/mrss/ rights,omitempty"`

	// MediaScenes specifies various scenes within a media object.
	MediaScenes externalRef4.MediaScenes `json:"media_scenes" xml:"http://search.yahoo.com/mrss/ scene,omitempty"`

	// MediaStatus specifies the status of a media object -- whether it's still active or it has been blocked/deleted.
	MediaStatus *externalRef4.MediaStatus `json:"media_status" xml:"http://search.yahoo.com/mrss/ status,omitempty"`

	// MediaSubTitle contains subtitle/CC link.
	MediaSubTitle *externalRef4.MediaSubTitle `json:"media_subtitle,omitempty" xml:"http://search.yahoo.com/mrss/ subTitle,omitempty"`

	// MediaTexts a list of texts for the object.
	MediaTexts externalRef4.MediaTexts `json:"media_texts" xml:"text,omitempty"`

	// MediaThumbnails a list of thumbnails for the object.
	MediaThumbnails externalRef4.MediaThumbnails `json:"media_thumbnails" xml:"thumbnail,omitempty"`

	// MediaTitle is the title of the particular media object.
	MediaTitle    *externalRef4.MediaTitle `json:"media_title" xml:"http://search.yahoo.com/mrss/ title,omitempty"`
	SourceAccount []externalRef5.Account   `json:"SourceAccount,omitempty" xml:"https://source.scripting.com/ account,omitempty"`

	// SourceArchive is links to the calendar-structured archive for the feed.  The folder pointed to by this address contains one folder for each year, 2009, 2010, 2011, etc. Each of those folders contains one folder for each month, 01, 02, 03, 04, 05, 06, 07, 08, 09, 10, 11, 12. The month folders must be zero-padded to two places. Folders may be missing, indicating that there is no archived content for the month. Each of the month folders contains folders for the days of the month. Day folder names are also zero-padded to two places and may be missing if there were no updates on the given day. Each day folder contains a file named rss.xml, unless the optional <source:filename> sub-element is supplied, which overrides the default. This makes it possible for a single calendar structure to store the archive of more than one feed.
	SourceArchive *externalRef5.Archive `json:"archive,omitempty" xml:"https://source.scripting.com/ archive,omitempty"`

	// SourceBlogroll points to the blogroll for the site associated with the feed, an OPML subscription list.
	SourceBlogroll *externalRef5.Blogroll `json:"blogroll,omitempty" validate:"omitempty,url" xml:"https://source.scripting.com/ blogroll,omitempty"`

	// SourceCloud provides a lot of information about the cloud server in a verbose way, specifying the domain, port, path and protocol.
	SourceCloud *externalRef5.Cloud `json:"cloud,omitempty" validate:"omitempty,url" xml:"https://source.scripting.com/ cloud,omitempty"`

	// SourceLikes is an instance of the the scripting.com likes software (a Node application) or a server that emulates its API.
	// Feed readers can use the server URL to form a like icon for each item that integrates with other feed readers. Perhaps the beginning of a way to build a connection between people who read a blog via various feed reader software. A demo app provides example code in JavaScript.
	SourceLikes *externalRef5.Likes `json:"likes,omitempty" xml:"https://source.scripting.com/ likes,omitempty"`

	// SourceLocalTime is a simple entirely human-readable way for the editor of the site to see what time, in his or her time zone, the feed was last updated. Must-have for debugging and sanity-preservation if you have trouble converting GMT to local time in your head (as I do). The format here is entirely up to the editor of the site.
	SourceLocalTime *externalRef5.LocalTime `json:"localTime,omitempty" xml:"https://source.scripting.com/ localTime,omitempty"`

	// SourceSelf is the canonical URL for the feed.
	SourceSelf             *externalRef5.Self              `json:"self,omitempty" validate:"omitempty,url" xml:"https://source.scripting.com/ self,omitempty"`
	SourceSubscriptionList []externalRef5.SubscriptionList `json:"SourceSubscriptionList,omitempty" xml:"https://source.scripting.com/ subscriptionList,omitempty"`

	// Attributes are any additional attributes of the element.
	Attributes []xml.Attr `json:"attributes" xml:",any,attr"`

	// Authors a list of persons who maintain authorship of the feed.
	Authors Authors `json:"authors,omitempty" validate:"gt=0,dive,validateFn" xml:"http://www.w3.org/2005/Atom author,omitempty"`

	// Categories a list of categories associated with the feed.
	Categories Categories `json:"categories,omitempty" validate:"dive,validateFn" xml:"category,omitempty"`

	// Contributors a list of persons who contributed to the feed.
	Contributors Contributors `json:"contributors,omitempty" validate:"omitempty,gt=0,dive,validateFn" xml:"http://www.w3.org/2005/Atom contributor,omitempty"`

	// DcContributor is an entity responsible for making contributions to the resource.
	// The guidelines for using names of persons or organizations as creators apply to contributors.
	DcContributor externalRef2.Contributor `json:"dc_contributor,omitempty" xml:"http://purl.org/dc/elements/1.1/ contributor,omitempty"`

	// DcCoverage is the spatial or temporal topic of the resource, spatial applicability of the resource, or jurisdiction under which the resource is relevant.
	// Spatial topic and spatial applicability may be a named place or a location specified by its geographic coordinates. Temporal topic may be a named period, date, or date range. A jurisdiction may be a named administrative entity or a geographic place to which the resource applies. Recommended practice is to use a controlled vocabulary such as the Getty Thesaurus of Geographic Names [TGN]. Where appropriate, named places or time periods may be used in preference to numeric identifiers such as sets of coordinates or date ranges. Because coverage is so broadly defined, it is preferable to use the more specific subproperties Temporal Coverage and Spatial Coverage.
	DcCoverage externalRef2.Coverage `json:"dc_coverage,omitempty" xml:"http://purl.org/dc/elements/1.1/ coverage,omitempty"`

	// DcCreator is an entity responsible for making the resource.
	// Recommended practice is to identify the creator with a URI. If this is not possible or feasible, a literal value that identifies the creator may be provided.
	DcCreator externalRef2.Creator `json:"dc_creator,omitempty" xml:"http://purl.org/dc/elements/1.1/ creator,omitempty"`

	// DcDate is a point or period of time associated with an event in the lifecycle of the resource.
	// Date may be used to express temporal information at any level of granularity. Recommended practice is to express the date, date/time, or period of time according to ISO 8601-1 [ISO 8601-1] or a published profile of the ISO standard, such as the W3C Note on Date and Time Formats [W3CDTF] or the Extended Date/Time Format Specification [EDTF]. If the full date is unknown, month and year (YYYY-MM) or just year (YYYY) may be used. Date ranges may be specified using ISO 8601 period of time specification in which start and end dates are separated by a '/' (slash) character. Either the start or end date may be missing.
	DcDate externalRef2.Date `json:"dc_date,omitempty" xml:"http://purl.org/dc/elements/1.1/ date,omitempty"`

	// DcDescription is an account of the resource.
	// Description may include but is not limited to: an abstract, a table of contents, a graphical representation, or a free-text account of the resource.
	DcDescription externalRef2.Description `json:"dc_description,omitempty" xml:"http://purl.org/dc/elements/1.1/ description,omitempty"`

	// DcFormat is the file format, physical medium, or dimensions of the resource.
	// Recommended practice is to use a controlled vocabulary where available. For example, for file formats one could use the list of Internet Media Types [MIME]. Examples of dimensions include size and duration.
	DcFormat externalRef2.Format `json:"dc_format,omitempty" xml:"http://purl.org/dc/elements/1.1/ format,omitempty"`

	// DcIdentifier is an unambiguous reference to the resource within a given context.
	// Recommended practice is to identify the resource by means of a string conforming to an identification system. Examples include International Standard Book Number (ISBN), Digital Object Identifier (DOI), and Uniform Resource Name (URN). Persistent identifiers should be provided as HTTP URIs.
	DcIdentifier externalRef2.Identifier `json:"dc_identifier,omitempty" xml:"http://purl.org/dc/elements/1.1/ identifier,omitempty"`

	// DcLanguage is a language of the resource.
	// Recommended practice is to use either a non-literal value representing a language from a controlled vocabulary such as ISO 639-2 or ISO 639-3, or a literal value consisting of an IETF Best Current Practice 47 [IETF-BCP47] language tag.
	DcLanguage externalRef2.Language `json:"dc_language,omitempty" xml:"http://purl.org/dc/elements/1.1/ language,omitempty"`

	// DcPublisher is an entity responsible for making the resource available.
	DcPublisher externalRef2.Publisher `json:"dc_publisher,omitempty" xml:"http://purl.org/dc/elements/1.1/ publisher,omitempty"`

	// DcRelation is a related resource.
	// Recommended practice is to identify the related resource by means of a URI. If this is not possible or feasible, a string conforming to a formal identification system may be provided.
	DcRelation externalRef2.Relation `json:"dc_relation,omitempty" xml:"http://purl.org/dc/elements/1.1/ relation,omitempty"`

	// DcRights is information about rights held in and over the resource.
	// Typically, rights information includes a statement about various property rights associated with the resource, including intellectual property rights. Recommended practice is to refer to a rights statement with a URI. If this is not possible or feasible, a literal value (name, label, or short text) may be provided.
	DcRights externalRef2.Rights `json:"dc_rights,omitempty" xml:"http://purl.org/dc/elements/1.1/ rights,omitempty"`

	// DcSource is a related resource from which the described resource is derived.
	// This property is intended to be used with non-literal values. The described resource may be derived from the related resource in whole or in part. Best practice is to identify the related resource by means of a URI or a string conforming to a formal identification system.
	DcSource externalRef2.Source `json:"dc_source,omitempty" xml:"http://purl.org/dc/elements/1.1/ source,omitempty"`

	// DcSubject is a topic of the resource.
	// Recommended practice is to refer to the subject with a URI. If this is not possible or feasible, a literal value that identifies the subject may be provided. Both should preferably refer to a subject in a controlled vocabulary.
	DcSubject externalRef2.Subject `json:"dc_subject,omitempty" xml:"http://purl.org/dc/elements/1.1/ subject,omitempty"`

	// DcTitle is a name given to the resource.
	DcTitle externalRef2.Title `json:"dc_title,omitempty" xml:"http://purl.org/dc/elements/1.1/ title,omitempty"`

	// DcType is the nature or genre of the resource.
	// Recommended practice is to use a controlled vocabulary such as the DCMI Type Vocabulary [DCMI-TYPE]. To describe the file format, physical medium, or dimensions of the resource, use the property Format.
	DcType externalRef2.Type `json:"dc_type,omitempty" xml:"http://purl.org/dc/elements/1.1/ type,omitempty"`

	// Entries is the list of <entry> elements for the feed.
	Entries []Entry `json:"entry,omitempty" validate:"dive,validateFn" xml:"entry,omitempty"`

	// Generator is an element identifies the agent used to generate a feed.
	Generator *Generator `json:"generator,omitempty" xml:"http://www.w3.org/2005/Atom generator,omitempty"`

	// Icon is an element that contains a URI to an icon suitable for representing a feed.
	Icon *Icon `json:"icon,omitempty" xml:"http://www.w3.org/2005/Atom icon,omitempty"`

	// Links a list of links associated with the feed.
	Links Links `json:"links,omitempty" validate:"dive,validateFn" xml:"link,omitempty"`

	// Logo is an element that contains a URI to an logo suitable for representing a feed.
	Logo *Logo `json:"logo,omitempty" validate:"omitempty" xml:"http://www.w3.org/2005/Atom logo,omitempty"`

	// Namespaces contains all namespaces in use by this RSS feed.
	Namespaces []externalRef0.Namespace `json:"namespaces,omitempty" xml:"-"`

	// Published is an element of type Date construct indicating an instant in time associated with an event early in the life cycle of the entry.
	Published *Published `json:"published,omitempty" xml:"http://www.w3.org/2005/Atom published,omitempty"`

	// Rights is an element of type Text construct that conveys information about rights held in and over an entry or feed.
	Rights *Rights `json:"rights,omitempty" xml:"http://www.w3.org/2005/Atom rights,omitempty"`

	// Subtitle is an element of type Text construct that conveys a human-readable subtitle for an entry or feed.
	Subtitle *Subtitle `json:"subtitle,omitempty" xml:"http://www.w3.org/2005/Atom subtitle,omitempty"`

	// Title is an element of type Text construct that conveys a human-readable title for an entry or feed.
	Title Title `json:"title" validate:"required" xml:"http://www.w3.org/2005/Atom title"`

	// Updated is an element of type Date construct indicating the most recent instant in time when an entry or feed was modified in a way the publisher considers significant.
	Updated Updated `json:"updated" validate:"required" xml:"http://www.w3.org/2005/Atom updated"`
}

// FeedMetadata is the feed metadata.
type FeedMetadata struct {
	// Base establishes the base URI (or IRI) for resolving any relative references found within the effective scope of the xml:base attribute.
	Base *string `json:"base,omitempty" validate:"omitempty" xml:"xml:base,attr,omitempty"`

	// ID is an element that conveys a permanent, universally unique identifier for an entry or feed.
	ID ID `json:"id" validate:"required" xml:"http://www.w3.org/2005/Atom id"`

	// Lang indicates the natural language for the element and its descendents.
	Lang *string `json:"lang,omitempty" validate:"omitempty,iso3166_1_alpha2|iso3166_1_alpha3|bcp47_language_tag" xml:"xml:lang,attr,omitempty"`

	// Attributes are any additional attributes of the element.
	Attributes []xml.Attr `json:"attributes" xml:",any,attr"`

	// Authors a list of persons who maintain authorship of the feed.
	Authors Authors `json:"authors,omitempty" validate:"gt=0,dive,validateFn" xml:"http://www.w3.org/2005/Atom author,omitempty"`

	// Categories a list of categories associated with the feed.
	Categories Categories `json:"categories,omitempty" validate:"dive,validateFn" xml:"category,omitempty"`

	// Contributors a list of persons who contributed to the feed.
	Contributors Contributors `json:"contributors,omitempty" validate:"omitempty,gt=0,dive,validateFn" xml:"http://www.w3.org/2005/Atom contributor,omitempty"`

	// Generator is an element identifies the agent used to generate a feed.
	Generator *Generator `json:"generator,omitempty" xml:"http://www.w3.org/2005/Atom generator,omitempty"`

	// Icon is an element that contains a URI to an icon suitable for representing a feed.
	Icon *Icon `json:"icon,omitempty" xml:"http://www.w3.org/2005/Atom icon,omitempty"`

	// Links a list of links associated with the feed.
	Links Links `json:"links,omitempty" validate:"dive,validateFn" xml:"link,omitempty"`

	// Logo is an element that contains a URI to an logo suitable for representing a feed.
	Logo *Logo `json:"logo,omitempty" validate:"omitempty" xml:"http://www.w3.org/2005/Atom logo,omitempty"`

	// Published is an element of type Date construct indicating an instant in time associated with an event early in the life cycle of the entry.
	Published *Published `json:"published,omitempty" xml:"http://www.w3.org/2005/Atom published,omitempty"`

	// Rights is an element of type Text construct that conveys information about rights held in and over an entry or feed.
	Rights *Rights `json:"rights,omitempty" xml:"http://www.w3.org/2005/Atom rights,omitempty"`

	// Subtitle is an element of type Text construct that conveys a human-readable subtitle for an entry or feed.
	Subtitle *Subtitle `json:"subtitle,omitempty" xml:"http://www.w3.org/2005/Atom subtitle,omitempty"`

	// Title is an element of type Text construct that conveys a human-readable title for an entry or feed.
	Title Title `json:"title" validate:"required" xml:"http://www.w3.org/2005/Atom title"`

	// Updated is an element of type Date construct indicating the most recent instant in time when an entry or feed was modified in a way the publisher considers significant.
	Updated Updated `json:"updated" validate:"required" xml:"http://www.w3.org/2005/Atom updated"`
}

// Generator is an element identifies the agent used to generate a feed.
type Generator struct {
	// Base establishes the base URI (or IRI) for resolving any relative references found within the effective scope of the xml:base attribute.
	Base *string `json:"base,omitempty" validate:"omitempty" xml:"xml:base,attr,omitempty"`

	// Lang indicates the natural language for the element and its descendents.
	Lang *string `json:"lang,omitempty" validate:"omitempty,iso3166_1_alpha2|iso3166_1_alpha3|bcp47_language_tag" xml:"xml:lang,attr,omitempty"`

	// Attributes are any additional attributes of the element.
	Attributes []xml.Attr `json:"attributes" xml:",any,attr"`
	URI        *string    `json:"uri,omitempty" validate:"omitempty,url" xml:"uri,attr,omitempty"`

	// Value is the element value.
	Value   string  `json:"value" xml:",chardata"`
	Version *string `json:"version,omitempty" xml:"version,attr,omitempty"`
}

// ID is an element that conveys a permanent, universally unique identifier for an entry or feed.
type ID struct {
	// Base establishes the base URI (or IRI) for resolving any relative references found within the effective scope of the xml:base attribute.
	Base *string `json:"base,omitempty" validate:"omitempty" xml:"xml:base,attr,omitempty"`

	// Lang indicates the natural language for the element and its descendents.
	Lang *string `json:"lang,omitempty" validate:"omitempty,iso3166_1_alpha2|iso3166_1_alpha3|bcp47_language_tag" xml:"xml:lang,attr,omitempty"`

	// Attributes are any additional attributes of the element.
	Attributes []xml.Attr `json:"attributes" xml:",any,attr"`

	// Value is the value of the ID
	Value string `json:"value" validate:"required,absolute_uri|urn_rfc2141|uuid" xml:",chardata"`
}

// Icon is an element that contains a URI to an icon suitable for representing a feed.
type Icon struct {
	// Base establishes the base URI (or IRI) for resolving any relative references found within the effective scope of the xml:base attribute.
	Base *string `json:"base,omitempty" validate:"omitempty" xml:"xml:base,attr,omitempty"`

	// Lang indicates the natural language for the element and its descendents.
	Lang *string `json:"lang,omitempty" validate:"omitempty,iso3166_1_alpha2|iso3166_1_alpha3|bcp47_language_tag" xml:"xml:lang,attr,omitempty"`

	// Attributes are any additional attributes of the element.
	Attributes []xml.Attr `json:"attributes" xml:",any,attr"`

	// Value is the value as a valid IRI.
	Value string `json:"value" xml:",chardata"`
}

// Link defines a relationship between a web resource (such as a page) and an RSS channel or item.
type Link struct {
	// Base establishes the base URI (or IRI) for resolving any relative references found within the effective scope of the xml:base attribute.
	Base *string `json:"base,omitempty" validate:"omitempty" xml:"xml:base,attr,omitempty"`

	// Lang indicates the natural language for the element and its descendents.
	Lang *string `json:"lang,omitempty" validate:"omitempty,iso3166_1_alpha2|iso3166_1_alpha3|bcp47_language_tag" xml:"xml:lang,attr,omitempty"`

	// UndefinedContent represents additional undefined, unstructed text content for the element.
	UndefinedContent *UndefinedContent `json:"undefined_content,omitempty" xml:",chardata"`

	// Attributes are any additional attributes of the element.
	Attributes []xml.Attr `json:"attributes" xml:",any,attr"`

	// Href contains the URL of the related resource.
	Href string `json:"href" validate:"required,url|hostname" xml:"href,attr"`

	// HrefLang identifies the language used by the related resource using an HTML language code.
	HrefLang *string `json:"hreflang,omitempty" validate:"omitempty,rfc3066lang" xml:"hreflang,attr,omitempty"`

	// Length contains the resource's size, in bytes.
	Length *int `json:"length,omitempty" validate:"omitempty,number" xml:"length,attr,omitempty"`

	// Rel contains a keyword that identifies the nature of the relationship between the linked resouce and the element.
	Rel *LinkRel `json:"rel,omitempty" validate:"omitempty,oneof=alternate enclosure related self via hub edit next standout http://schemas.google.com/g/2005#feed" xml:"rel,attr,omitempty"`

	// Title provides a human-readable description of the resource.
	Title *string `json:"title,omitempty" validate:"omitnil,required" xml:"title,attr,omitempty"`

	// Type identifies the resource's MIME media type.
	Type *string `json:"type,omitempty" validate:"omitnil,mimetype_string" xml:"type,attr,omitempty"`
}

// LinkRel contains a keyword that identifies the nature of the relationship between the linked resouce and the element.
type LinkRel string

// Links a list of links associated with the feed.
type Links = []Link

// Logo is an element that contains a URI to an logo suitable for representing a feed.
type Logo struct {
	// Base establishes the base URI (or IRI) for resolving any relative references found within the effective scope of the xml:base attribute.
	Base *string `json:"base,omitempty" validate:"omitempty" xml:"xml:base,attr,omitempty"`

	// Lang indicates the natural language for the element and its descendents.
	Lang *string `json:"lang,omitempty" validate:"omitempty,iso3166_1_alpha2|iso3166_1_alpha3|bcp47_language_tag" xml:"xml:lang,attr,omitempty"`

	// Attributes are any additional attributes of the element.
	Attributes []xml.Attr `json:"attributes" xml:",any,attr"`
	Value      string     `json:"value" xml:",chardata"`
}

// PersonConstruct describes a person, corporation, or similar entity
type PersonConstruct struct {
	// Base establishes the base URI (or IRI) for resolving any relative references found within the effective scope of the xml:base attribute.
	Base *string `json:"base,omitempty" validate:"omitempty" xml:"xml:base,attr,omitempty"`

	// Extensions records any elements that are unknown extensions to the schema.
	Extensions []externalRef0.Extension `json:"extensions,omitempty" xml:",any"`

	// Lang indicates the natural language for the element and its descendents.
	Lang *string `json:"lang,omitempty" validate:"omitempty,iso3166_1_alpha2|iso3166_1_alpha3|bcp47_language_tag" xml:"xml:lang,attr,omitempty"`

	// Attributes are any additional attributes of the element.
	Attributes []xml.Attr `json:"attributes" xml:",any,attr"`

	// Email is an element that conveys an email address.
	Email *string `json:"email,omitempty" validate:"omitempty,email" xml:"email,omitempty"`

	// Name is an element that conveys a human-readable name.
	Name string `json:"name" validate:"required" xml:"name"`

	// URI is an element that conveys an IRI (URI).
	URI *string `json:"uri,omitempty" validate:"omitempty" xml:"uri,omitempty"`
}

// Published is an element of type Date construct indicating an instant in time associated with an event early in the life cycle of the entry.
type Published = DateConstruct

// Rights is an element of type Text construct that conveys information about rights held in and over an entry or feed.
type Rights = TextConstruct

// Source contains the metadata from the source feed for the entry.
type Source = FeedMetadata

// StandaloneEntry is a document whose root element is atom:entry rather than atom:feed. Kept as a distinct wrapper rather than giving Entry itself a namespace-declaring MarshalXML, so the common case (Entry nested inside Feed.Entries) stays simple and un-verbose.
type StandaloneEntry struct {
	// Base establishes the base URI (or IRI) for resolving any relative references found within the effective scope of the xml:base attribute.
	Base             *string `json:"base,omitempty" validate:"omitempty" xml:"xml:base,attr,omitempty"`
	DefaultNamespace *string `json:"DefaultNamespace,omitempty" xml:"-"`

	// Extensions records any elements that are unknown extensions to the schema.
	Extensions []externalRef0.Extension `json:"extensions,omitempty" xml:",any"`

	// ID is an element that conveys a permanent, universally unique identifier for an entry or feed.
	ID ID `json:"id" validate:"required" xml:"http://www.w3.org/2005/Atom id"`

	// Lang indicates the natural language for the element and its descendents.
	Lang *string `json:"lang,omitempty" validate:"omitempty,iso3166_1_alpha2|iso3166_1_alpha3|bcp47_language_tag" xml:"xml:lang,attr,omitempty"`

	// MediaBackLinks allows inclusion of all the URLs pointing to a media object.
	MediaBackLinks externalRef4.MediaBacklinks `json:"media_backlinks,omitempty" xml:"http://search.yahoo.com/mrss/ backLink,omitempty"`

	// MediaCategory allows a taxonomy to be set that gives an indication of the type of media content, and its particular contents.
	MediaCategory *externalRef4.MediaCategory `json:"media_category" xml:"http://search.yahoo.com/mrss/ category,omitempty"`

	// MediaComments is a list of comments the media object has received.
	MediaComments externalRef4.MediaComments `json:"media_comments"`

	// MediaCommunity stands for the community related content. This allows inclusion of the user perception about a media object in the form of view count, ratings and tags.
	MediaCommunity *externalRef4.MediaCommunity `json:"media_community" xml:"http://search.yahoo.com/mrss/ community,omitempty"`

	// MediaCopyright is copyright information for the media object.
	MediaCopyright *externalRef4.MediaCopyright `json:"media_copyright" xml:"media copyright,omitempty"`

	// MediaCredits a list of credits for the object.
	MediaCredits externalRef4.MediaCredits `json:"media_credits" xml:"credit,omitempty"`

	// MediaDescription is a short description describing the media object typically a sentence in length.
	MediaDescription *externalRef4.MediaDescription `json:"media_description" xml:"http://search.yahoo.com/mrss/ description,omitempty"`

	// MediaEmbed allows inclusion of player-specific information in the form of key-value (Param) pairs.
	MediaEmbed *externalRef4.MediaEmbed `json:"media_embed" xml:"http://search.yahoo.com/mrss/ embed,omitempty"`

	// MediaGroup allows grouping of <media:content> elements that are effectively the same content, yet different representations. For instance: the same song recorded in both the WAV and MP3 format.
	MediaGroup *externalRef4.MediaGroup `json:"media_group,omitempty" xml:"http://search.yahoo.com/mrss/ group,omitempty"`

	// MediaHashes a list of hashes for the object.
	MediaHashes externalRef4.MediaHashes `json:"media_hashes" xml:"hash,omitempty"`

	// MediaKeywords are highly relevant keywords describing the media object with typically a maximum of 10 words. The keywords and phrases should be comma-delimited.
	MediaKeywords *externalRef4.MediaKeywords `json:"media_keywords" xml:"http://search.yahoo.com/mrss/ keywords,omitempty"`

	// MediaLicense link to specify the machine-readable license associated with the content.
	MediaLicense *externalRef4.MediaLicense `json:"media_license" xml:"http://search.yahoo.com/mrss/ license,omitempty"`

	// MediaPeerLink contains P2P link.
	MediaPeerLink *externalRef4.MediaPeerLink `json:"media_peerlink" xml:"http://search.yahoo.com/mrss/ peerLink,omitempty"`

	// MediaPlayer allows the media object to be accessed through a web browser media player console.
	MediaPlayer *externalRef4.MediaPlayer `json:"media_player" xml:"http://search.yahoo.com/mrss/ player,omitempty"`

	// MediaPrice includes pricing information about a media object. If this tag is not present, the media object is supposed to be free.
	MediaPrice *externalRef4.MediaPrice `json:"media_price" xml:"http://search.yahoo.com/mrss/ price,omitempty"`

	// MediaRating allows the permissible audience to be declared. If this element is not included, it assumes that no restrictions are necessary.
	MediaRating *externalRef4.MediaRating `json:"media_rating" xml:"http://search.yahoo.com/mrss/ rating,omitempty"`

	// MediaResponses allows inclusion of a list of all media responses a media object has received.
	MediaResponses externalRef4.MediaResponses `json:"media_responses" xml:"http://search.yahoo.com/mrss/ response,omitempty"`

	// MediaRestriction allows restrictions to be placed on the aggregator rendering the media in the feed.
	MediaRestriction *externalRef4.MediaRestriction `json:"media_restriction" validate:"omitempty,validateFn" xml:"http://search.yahoo.com/mrss/ restriction,omitempty"`

	// MediaRights specifies the rights information of a media object.
	MediaRights *externalRef4.MediaRights `json:"media_rights" xml:"http://search.yahoo.com/mrss/ rights,omitempty"`

	// MediaScenes specifies various scenes within a media object.
	MediaScenes externalRef4.MediaScenes `json:"media_scenes" xml:"http://search.yahoo.com/mrss/ scene,omitempty"`

	// MediaStatus specifies the status of a media object -- whether it's still active or it has been blocked/deleted.
	MediaStatus *externalRef4.MediaStatus `json:"media_status" xml:"http://search.yahoo.com/mrss/ status,omitempty"`

	// MediaSubTitle contains subtitle/CC link.
	MediaSubTitle *externalRef4.MediaSubTitle `json:"media_subtitle,omitempty" xml:"http://search.yahoo.com/mrss/ subTitle,omitempty"`

	// MediaTexts a list of texts for the object.
	MediaTexts externalRef4.MediaTexts `json:"media_texts" xml:"text,omitempty"`

	// MediaThumbnails a list of thumbnails for the object.
	MediaThumbnails externalRef4.MediaThumbnails `json:"media_thumbnails" xml:"thumbnail,omitempty"`

	// MediaTitle is the title of the particular media object.
	MediaTitle *externalRef4.MediaTitle `json:"media_title" xml:"http://search.yahoo.com/mrss/ title,omitempty"`

	// SourceComments are links to comments for this item.
	SourceComments *externalRef5.Comments `json:"comments,omitempty" xml:"https://source.scripting.com/ comments,omitempty"`

	// SourceInReplyTo identifies the item that this item is in reply to.
	SourceInReplyTo *externalRef5.InReplyTo `json:"inReplyTo,omitempty" xml:"https://source.scripting.com/ inReplyTo,omitempty"`

	// SourceLinkFill is the unshortened version of <link>.
	SourceLinkFill *externalRef5.LinkFull `json:"linkFull,omitempty" xml:"https://source.scripting.com/ linkFull,omitempty"`

	// SourceMarkdown is the source of the item-level description sub-element using Markdown to encode styling and links. If your feed presenter can understand Markdown, you should use this as the source for the display of the item.
	SourceMarkdown *externalRef5.Markdown `json:"markdown,omitempty" xml:"https://source.scripting.com/ markdown,omitempty"`
	SourceOutline  *externalRef5.Outline  `json:"outline,omitempty" xml:"https://source.scripting.com/ outline,omitempty"`

	// Alt is the meters above the local reference ellipsoid.
	Alt *externalRef1.Altitude `json:"alt,omitempty" xml:"http://www.w3.org/2003/01/geo/wgs84_pos# alt,omitempty"`

	// Attributes are any additional attributes of the element.
	Attributes []xml.Attr `json:"attributes" xml:",any,attr"`

	// Authors a list of persons who maintain authorship of the feed.
	Authors Authors `json:"authors,omitempty" validate:"gt=0,dive,validateFn" xml:"http://www.w3.org/2005/Atom author,omitempty"`

	// Box is a bounding box as two coordinate pairs: the lower (southwest) corner, then the upper (northeast) corner (georss:box).
	Box *externalRef3.Box `json:"box,omitempty" xml:"http://www.georss.org/georss box"`

	// Categories a list of categories associated with the feed.
	Categories Categories `json:"categories,omitempty" validate:"dive,validateFn" xml:"category,omitempty"`

	// Circle a center point plus a radius in meters (georss:circle).
	Circle *externalRef3.Circle `json:"circle,omitempty" xml:"http://www.georss.org/georss circle"`

	// Content either contains or links to the content of the entry.
	Content *Content `json:"content,omitempty" validate:"omitempty,validateFn" xml:"http://www.w3.org/2005/Atom content,omitempty"`

	// Contributors a list of persons who contributed to the feed.
	Contributors Contributors `json:"contributors,omitempty" validate:"omitempty,gt=0,dive,validateFn" xml:"http://www.w3.org/2005/Atom contributor,omitempty"`

	// DcContributor is an entity responsible for making contributions to the resource.
	// The guidelines for using names of persons or organizations as creators apply to contributors.
	DcContributor externalRef2.Contributor `json:"dc_contributor,omitempty" xml:"http://purl.org/dc/elements/1.1/ contributor,omitempty"`

	// DcCoverage is the spatial or temporal topic of the resource, spatial applicability of the resource, or jurisdiction under which the resource is relevant.
	// Spatial topic and spatial applicability may be a named place or a location specified by its geographic coordinates. Temporal topic may be a named period, date, or date range. A jurisdiction may be a named administrative entity or a geographic place to which the resource applies. Recommended practice is to use a controlled vocabulary such as the Getty Thesaurus of Geographic Names [TGN]. Where appropriate, named places or time periods may be used in preference to numeric identifiers such as sets of coordinates or date ranges. Because coverage is so broadly defined, it is preferable to use the more specific subproperties Temporal Coverage and Spatial Coverage.
	DcCoverage externalRef2.Coverage `json:"dc_coverage,omitempty" xml:"http://purl.org/dc/elements/1.1/ coverage,omitempty"`

	// DcCreator is an entity responsible for making the resource.
	// Recommended practice is to identify the creator with a URI. If this is not possible or feasible, a literal value that identifies the creator may be provided.
	DcCreator externalRef2.Creator `json:"dc_creator,omitempty" xml:"http://purl.org/dc/elements/1.1/ creator,omitempty"`

	// DcDate is a point or period of time associated with an event in the lifecycle of the resource.
	// Date may be used to express temporal information at any level of granularity. Recommended practice is to express the date, date/time, or period of time according to ISO 8601-1 [ISO 8601-1] or a published profile of the ISO standard, such as the W3C Note on Date and Time Formats [W3CDTF] or the Extended Date/Time Format Specification [EDTF]. If the full date is unknown, month and year (YYYY-MM) or just year (YYYY) may be used. Date ranges may be specified using ISO 8601 period of time specification in which start and end dates are separated by a '/' (slash) character. Either the start or end date may be missing.
	DcDate externalRef2.Date `json:"dc_date,omitempty" xml:"http://purl.org/dc/elements/1.1/ date,omitempty"`

	// DcDescription is an account of the resource.
	// Description may include but is not limited to: an abstract, a table of contents, a graphical representation, or a free-text account of the resource.
	DcDescription externalRef2.Description `json:"dc_description,omitempty" xml:"http://purl.org/dc/elements/1.1/ description,omitempty"`

	// DcFormat is the file format, physical medium, or dimensions of the resource.
	// Recommended practice is to use a controlled vocabulary where available. For example, for file formats one could use the list of Internet Media Types [MIME]. Examples of dimensions include size and duration.
	DcFormat externalRef2.Format `json:"dc_format,omitempty" xml:"http://purl.org/dc/elements/1.1/ format,omitempty"`

	// DcIdentifier is an unambiguous reference to the resource within a given context.
	// Recommended practice is to identify the resource by means of a string conforming to an identification system. Examples include International Standard Book Number (ISBN), Digital Object Identifier (DOI), and Uniform Resource Name (URN). Persistent identifiers should be provided as HTTP URIs.
	DcIdentifier externalRef2.Identifier `json:"dc_identifier,omitempty" xml:"http://purl.org/dc/elements/1.1/ identifier,omitempty"`

	// DcLanguage is a language of the resource.
	// Recommended practice is to use either a non-literal value representing a language from a controlled vocabulary such as ISO 639-2 or ISO 639-3, or a literal value consisting of an IETF Best Current Practice 47 [IETF-BCP47] language tag.
	DcLanguage externalRef2.Language `json:"dc_language,omitempty" xml:"http://purl.org/dc/elements/1.1/ language,omitempty"`

	// DcPublisher is an entity responsible for making the resource available.
	DcPublisher externalRef2.Publisher `json:"dc_publisher,omitempty" xml:"http://purl.org/dc/elements/1.1/ publisher,omitempty"`

	// DcRelation is a related resource.
	// Recommended practice is to identify the related resource by means of a URI. If this is not possible or feasible, a string conforming to a formal identification system may be provided.
	DcRelation externalRef2.Relation `json:"dc_relation,omitempty" xml:"http://purl.org/dc/elements/1.1/ relation,omitempty"`

	// DcRights is information about rights held in and over the resource.
	// Typically, rights information includes a statement about various property rights associated with the resource, including intellectual property rights. Recommended practice is to refer to a rights statement with a URI. If this is not possible or feasible, a literal value (name, label, or short text) may be provided.
	DcRights externalRef2.Rights `json:"dc_rights,omitempty" xml:"http://purl.org/dc/elements/1.1/ rights,omitempty"`

	// DcSource is a related resource from which the described resource is derived.
	// This property is intended to be used with non-literal values. The described resource may be derived from the related resource in whole or in part. Best practice is to identify the related resource by means of a URI or a string conforming to a formal identification system.
	DcSource externalRef2.Source `json:"dc_source,omitempty" xml:"http://purl.org/dc/elements/1.1/ source,omitempty"`

	// DcSubject is a topic of the resource.
	// Recommended practice is to refer to the subject with a URI. If this is not possible or feasible, a literal value that identifies the subject may be provided. Both should preferably refer to a subject in a controlled vocabulary.
	DcSubject externalRef2.Subject `json:"dc_subject,omitempty" xml:"http://purl.org/dc/elements/1.1/ subject,omitempty"`

	// DcTitle is a name given to the resource.
	DcTitle externalRef2.Title `json:"dc_title,omitempty" xml:"http://purl.org/dc/elements/1.1/ title,omitempty"`

	// DcType is the nature or genre of the resource.
	// Recommended practice is to use a controlled vocabulary such as the DCMI Type Vocabulary [DCMI-TYPE]. To describe the file format, physical medium, or dimensions of the resource, use the property Format.
	DcType externalRef2.Type `json:"dc_type,omitempty" xml:"http://purl.org/dc/elements/1.1/ type,omitempty"`

	// Elev contains “common” GPS elevation readings, i.e. height in meters referenced to the WGS84 ellipsoid. This is a reading that should be easy to get from any GPS device.
	Elev           *float64 `json:"elev,omitempty" xml:"http://www.georss.org/georss elev"`
	FeatureName    *string  `json:"featureName,omitempty" xml:"http://www.georss.org/georss featurename,omitempty"`
	FeatureTypeTag *string  `json:"featureTypeTag,omitempty" xml:"http://www.georss.org/georss featuretypetag,omitempty"`

	// Floor contains the floor number of a building. In some countries the numbering is different than in other countries, but since we’ll know the location of the building, it should be fairly unambiguous. The definition of “floor” as used in GeoRSS is consistent with the IETF[3] and NENA definitions as required for the Next Generation 911 system in the US.
	Floor *int `json:"floor,omitempty" xml:"http://www.georss.org/georss floor"`

	// Lat is the latitude in decimal degress
	Lat externalRef1.Latitude `json:"lat" validate:"required,gte=-90,lte=90" xml:"http://www.w3.org/2003/01/geo/wgs84_pos# lat"`

	// Line is an ordered sequence of two or more coordinate pairs (a LineString, georss:line).
	Line externalRef3.Line `json:"line,omitempty" xml:"http://www.georss.org/georss line"`

	// Links a list of links associated with the feed.
	Links Links `json:"links,omitempty" validate:"dive,validateFn" xml:"link,omitempty"`

	// Lon is the longitude in decimal degress
	Lon externalRef1.Longitude `json:"lon" validate:"required,gte=-180,lte=180" xml:"http://www.w3.org/2003/01/geo/wgs84_pos# long"`

	// Namespaces contains all namespaces in use by this RSS feed.
	Namespaces []externalRef0.Namespace `json:"namespaces,omitempty" xml:"-"`

	// Point a single coordinate pair (georss:point).
	Point *externalRef3.Point `json:"point,omitempty" xml:"http://www.georss.org/georss point"`

	// Polygon a closed linear ring -- four or more coordinate pairs, with the first and last identical.
	Polygon externalRef3.Polygon `json:"polygon,omitempty" xml:"http://www.georss.org/georss polygon"`

	// Published is an element of type Date construct indicating an instant in time associated with an event early in the life cycle of the entry.
	Published *Published `json:"published,omitempty" xml:"http://www.w3.org/2005/Atom published,omitempty"`

	// Radius indicates the size in meters of a radius or buffer around the geometry object, for example, radius of circular area around a point geometry.
	Radius          *float64 `json:"radius,omitempty" xml:"http://www.georss.org/georss radius"`
	RelationshipTag *string  `json:"relationshipTag,omitempty" xml:"http://www.georss.org/georss relationshiptag,omitempty"`

	// Rights is an element of type Text construct that conveys information about rights held in and over an entry or feed.
	Rights *Rights `json:"rights,omitempty" xml:"http://www.w3.org/2005/Atom rights,omitempty"`

	// Source contains the metadata from the source feed for the entry.
	Source *Source `json:"source,omitempty" validate:"omitempty"`

	// Summary is an element of type Text construct that conveys a short summary, abstract, or excerpt of an entry.
	Summary *Summary `json:"summary,omitempty" xml:"http://www.w3.org/2005/Atom summary,omitempty"`

	// Title is an element of type Text construct that conveys a human-readable title for an entry or feed.
	Title Title `json:"title" validate:"required" xml:"http://www.w3.org/2005/Atom title"`

	// Updated is an element of type Date construct indicating the most recent instant in time when an entry or feed was modified in a way the publisher considers significant.
	Updated Updated `json:"updated" validate:"required" xml:"http://www.w3.org/2005/Atom updated"`

	// Where wraps exactly one of the four GML geometries (georss:where).
	Where *externalRef3.Where `json:"where,omitempty" xml:"http://www.georss.org/georss where"`
}

// Subtitle is an element of type Text construct that conveys a human-readable subtitle for an entry or feed.
type Subtitle = TextConstruct

// Summary is an element of type Text construct that conveys a short summary, abstract, or excerpt of an entry.
type Summary = TextConstruct

// TextConstruct contains human-readable text, usually in small quantities.
type TextConstruct struct {
	// Base establishes the base URI (or IRI) for resolving any relative references found within the effective scope of the xml:base attribute.
	Base *string `json:"base,omitempty" validate:"omitempty" xml:"xml:base,attr,omitempty"`

	// Lang indicates the natural language for the element and its descendents.
	Lang *string `json:"lang,omitempty" validate:"omitempty,iso3166_1_alpha2|iso3166_1_alpha3|bcp47_language_tag" xml:"xml:lang,attr,omitempty"`

	// Attributes are any additional attributes of the element.
	Attributes []xml.Attr `json:"attributes" xml:",any,attr"`

	// Type represents what the content of the element is.
	Type *TextConstructType `json:"type,omitempty" validate:"omitnil,oneof=text html xhtml" xml:"type,attr,omitempty"`

	// Value is the value of the element for type=text/html.
	Value string `json:"value" validate:"required_if=Type html|required_if=Type text"`

	// XHTML is the value of the element for type=xhtml
	XHTML *string `json:"xhtml,omitempty" validate:"required_if=Type xhtml"`
}

// TextConstructType represents what the content of the element is.
type TextConstructType string

// Title is an element of type Text construct that conveys a human-readable title for an entry or feed.
type Title = TextConstruct

// UndefinedContent represents additional undefined, unstructed text content for the element.
type UndefinedContent = string

// Updated is an element of type Date construct indicating the most recent instant in time when an entry or feed was modified in a way the publisher considers significant.
type Updated = DateConstruct
